#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Dizionario PATTERN -> ALTERNATIVE (Parte 5: valutazioni e giudizi frequenti)"""

EVALUATION_PATTERNS = {

# ── 114x ──
"Li vedo bene soprattutto": [
    "Li immagino perfetti soprattutto", "Funzionano al meglio soprattutto",
    "Danno il massimo soprattutto", "Brillano particolarmente",
    "Li trovo ideali soprattutto", "Rendono al massimo soprattutto",
    "Esprimono il loro meglio soprattutto", "Li apprezzo di più soprattutto",
    "Sono al top soprattutto", "Li preferisco soprattutto",
    "Calzano a pennello soprattutto", "Li sceglierei soprattutto",
    "Sono perfetti soprattutto", "Li consiglierei soprattutto",
    "Trovano il loro habitat soprattutto", "Si esprimono al meglio soprattutto",
    "Sono nel loro elemento soprattutto", "Li trovo perfetti soprattutto",
    "L'ideale è usarli soprattutto", "Danno il loro meglio soprattutto",
    "Li indosserei soprattutto", "Sono al meglio soprattutto",
    "Si adattano alla perfezione soprattutto", "Li vivo al meglio soprattutto",
    "Raggiungono l'eccellenza soprattutto", "Li frequento soprattutto",
    "Li sento perfetti soprattutto", "Il loro terreno ideale è soprattutto",
    "Sono a casa loro soprattutto", "Li porto con più piacere soprattutto",
    "Li trovo nel loro elemento soprattutto", "Funzionano da applauso soprattutto",
    "Li apprezzo in modo speciale soprattutto", "Toccano il massimo soprattutto",
    "Si distinguono soprattutto", "Li prediligo soprattutto",
    "Sono particolarmente azzeccati", "Li trovo vincenti soprattutto",
    "Si fanno valere soprattutto", "Li sento centrati soprattutto",
    "Esprimono tutta la loro forza soprattutto", "Li trovo nella loro dimensione migliore soprattutto",
    "Li giudico al massimo soprattutto", "Sono una scelta vincente soprattutto",
    "Li classifico come perfetti soprattutto", "Trovano la loro dimensione soprattutto",
    "Li penso ideali soprattutto", "Li trovo giusti soprattutto",
    "Li considero al meglio soprattutto", "Si valorizzano soprattutto",
    "Sono una scelta forte soprattutto", "Li vedo nel loro habitat soprattutto",
    "Li scelgo con convinzione soprattutto", "Sono la scelta giusta soprattutto",
    "Li trovo nel pieno del loro potenziale", "Danno il meglio di sé soprattutto",
    "Li scelgo d'istinto soprattutto", "Si rivelano perfetti soprattutto",
    "Li trovo impeccabili soprattutto", "Raggiungono il pieno soprattutto",
    "Esprimono il meglio soprattutto", "Sono una garanzia soprattutto",
    "Li trovo calzanti soprattutto", "Li reputo perfetti soprattutto",
    "Sono al massimo del loro potenziale soprattutto", "Li sento nella loro dimensione giusta soprattutto",
    "Funzionano benissimo soprattutto", "Li indosserei con convinzione soprattutto",
    "Si esprimono alla grande soprattutto", "Li immagino nel loro contesto ideale soprattutto",
    "Si fanno notare soprattutto", "Li apprezzo al meglio soprattutto",
    "Toccano il vertice soprattutto", "Li trovo eccellenti soprattutto",
    "Si rivelano vincenti soprattutto", "Sono in gran forma soprattutto",
    "Li reputo ideali soprattutto", "Li trovo nella loro migliore versione soprattutto",
    "Sono al top della resa soprattutto", "Li considero una scelta forte soprattutto",
    "Li penso nel loro ambiente naturale soprattutto", "Li apprezzo con convinzione soprattutto",
    "Li ritengo perfetti soprattutto", "Esprimono la loro essenza soprattutto",
    "Si distinguono per intensità soprattutto", "Li trovo al loro apice soprattutto",
    "Sono nel loro regno soprattutto", "Li vedo al massimo della resa soprattutto",
    "Si valorizzano al meglio soprattutto", "Li trovo straordinariamente adatti soprattutto",
    "Sono una scelta eccellente soprattutto", "Li sento perfettamente in contesto soprattutto",
    "Li considero ideali soprattutto", "Si esprimono con tutta la loro forza soprattutto",
    "Rendono benissimo soprattutto", "Li trovo nella condizione perfetta soprattutto",
    "Sono al massimo dell'espressione soprattutto", "Li vedo nella loro luce migliore soprattutto",
    "Li apprezzo in pieno soprattutto", "Funzionano come un orologio soprattutto",
    "Li trovo centrati alla perfezione soprattutto", "Si fanno valere davvero soprattutto",
    "Sono nella loro forma migliore soprattutto", "Li considero nel loro meglio soprattutto",
    "Li trovo superbi soprattutto", "Li vedo al loro meglio soprattutto",
    "Brillano con intensità soprattutto", "Esprimono forza soprattutto",
    "Si rivelano al top soprattutto", "Sono al loro massimo soprattutto",
    "Li sento assolutamente centrati soprattutto", "Li trovo nel loro punto forte soprattutto",
    "Si confermano perfetti soprattutto", "Li apprezzo totalmente soprattutto",
    "Rendono alla grande soprattutto", "Raggiungono il massimo della qualità soprattutto",
],

# ── 100x ──
"È uno di quei modelli che": [
    "È il tipo di modello che", "Rientra nella categoria di occhiali che",
    "È quel genere di paio che", "Fa parte di quei modelli che",
    "Appartiene a quella classe di occhiali che", "È nell'olimpo dei modelli che",
    "Rientra tra quei paia che", "È un esponente di quella famiglia che",
    "Si colloca tra quei modelli che", "È uno di quei pezzi che",
    "Rientra nel novero di quei modelli che", "È quel tipo di paio che",
    "Fa parte di quella categoria che", "È un classico esempio di modello che",
    "Si posiziona tra quei modelli che", "È il classico paio che",
    "Rientra tra quei prodotti che", "Appartiene a quel tipo di occhiali che",
    "È un rappresentante di quei modelli che", "È di quella stirpe di paia che",
    "Si iscrive nella lista dei modelli che", "È uno di quei pezzi speciali che",
    "È un esempio perfetto di modello che", "Rientra tra quei design che",
    "Fa parte di quei pochi paia che", "Appartiene a quella schiera di modelli che",
    "È il tipo di paio che", "Si classifica tra quei modelli che",
    "È un modello che", "Rientra nel genere di paia che",
    "È quel classico tipo di occhiale che", "Si iscrive tra quei modelli che",
    "È un paio che", "Fa parte di quella selezione di modelli che",
    "Rientra nella famiglia dei paia che", "È del tipo di modello che",
    "Appartiene a quei design particolari che", "Si posiziona tra quei paia che",
    "È un esemplare di quel genere che", "Rientra tra quei modelli interessanti che",
    "È un caso di paio che", "Fa parte di quei modelli particolari che",
    "È un occhiale che", "Si annovera tra quei modelli che",
    "Rientra tra quei paia speciali che", "È il caso di modello che",
    "Appartiene a quei modelli rari che", "È uno di quei design che",
    "Si inserisce tra quei modelli che", "È un pezzo che",
    "È tra quei modelli che", "Rientra nella specie di paia che",
    "È uno dei modelli che", "Fa parte di quei design rari che",
    "È un paio del tipo che", "Si colloca tra quei design che",
    "Appartiene ai modelli che", "Rientra tra quei paia con la capacità di",
    "È il genere di occhiale che", "È di quel genere di paia che",
    "Fa parte di quei modelli con la qualità di", "Si iscrive tra quei paia che",
    "Appartiene alla famiglia di modelli che", "È quel tipo di design che",
    "Rientra tra quei modelli con il dono di", "È un paio del genere che",
    "Si inserisce nella categoria dei paia che", "È un modello nella schiera di quelli che",
    "Fa parte di quei paia con il merito di", "È tra quei design che",
    "Rientra nella tipologia di modelli che", "È del genere di paia che",
    "Appartiene a quei modelli con la caratteristica che", "È un paio con il pregio che",
    "Si situa tra quei modelli che", "Fa parte di quei paia capaci di",
    "È un modello del tipo che", "È nella schiera dei modelli che",
    "Rientra tra quei paia notevoli che", "È il tipo di design che",
    "Appartiene a quei paia con la forza di", "Si posiziona nella categoria dei modelli che",
    "È un esempio di paio che", "Rientra nel campo dei modelli che",
    "Fa parte di quei paia con il potere di", "È il genere di modello che",
    "Si colloca nella fascia dei modelli che", "È un pezzo nella categoria di quelli che",
    "Rientra tra i modelli con il merito di", "È del tipo di paio che",
    "Si inserisce tra i modelli che", "Appartiene alla tipologia di paia che",
    "Fa parte di quei design capaci di", "È nella lista dei modelli che",
    "È un modello raro del genere che", "Rientra tra quei paia con la stoffa che",
    "È del genere di modello che", "Si classifica tra i paia che",
    "È un esemplare di modello che", "Rientra nei modelli con il talento di",
    "Appartiene a quei paia con l'abilità di", "È uno di quei pezzi rari che",
],

# ── 78x ──
"Ci sono diversi elementi riusciti": [
    "Molti aspetti funzionano bene", "Diverse componenti sono azzeccate",
    "Parecchi dettagli sono centrati", "Vari elementi colpiscono nel segno",
    "Ci sono molte cose riuscite", "Diversi aspetti sono ben calibrati",
    "Più di un elemento funziona a dovere", "Molte scelte stilistiche sono centrate",
    "Diversi punti di forza emergono", "Ci sono più elementi convincenti",
    "Vari aspetti sono nella giusta direzione", "Parecchie scelte sono riuscite",
    "Diverse cose funzionano come dovrebbero", "Molti dettagli sono al posto giusto",
    "Ci sono vari aspetti positivi", "Diversi elementi mostrano cura",
    "Più cose funzionano che no", "Molte componenti sono curate",
    "Diversi aspetti sono promettenti", "Ci sono elementi che brillano",
    "Vari punti meritano menzione positiva", "Parecchi aspetti sono ben pensati",
    "Diverse qualità emergono", "Molti aspetti convincono",
    "Ci sono diversi pregi notevoli", "Vari dettagli sono apprezzabili",
    "Parecchie cose sono nella direzione giusta", "Diversi elementi meritano plauso",
    "Molte caratteristiche sono riuscite", "Ci sono punti di forza evidenti",
    "Diversi aspetti sono ben risolti", "Vari elementi mostrano qualità",
    "Parecchi dettagli sono curati", "Più elementi funzionano che non",
    "Diversi meriti sono evidenti", "Ci sono aspetti davvero convincenti",
    "Molti punti sono positivi", "Vari aspetti sono ben eseguiti",
    "Diversi dettagli sono apprezzabili", "Ci sono qualità tangibili",
    "Parecchi elementi sono nella nota giusta", "Molte scelte sono corrette",
    "Diversi punti di forza sono visibili", "Ci sono meriti concreti",
    "Vari aspetti funzionano con efficacia", "Più elementi riescono che falliscono",
    "Diversi dettagli impressionano positivamente", "Molti aspetti sono nella norma alta",
    "Ci sono diversi punti degni di nota", "Vari elementi convincono senza dubbio",
    "Parecchie cose sono da apprezzare", "Diversi aspetti sono lodevoli",
    "Molti elementi raggiungono il segno", "Ci sono aspetti che meritano",
    "Diversi dettagli sono nel segno giusto", "Vari punti sono positivi",
    "Parecchi elementi sono ben fatti", "Più aspetti positivi che negativi",
    "Diversi pregi sono evidenti", "Molte cose sono nelle giuste proporzioni",
    "Ci sono vari aspetti da valorizzare", "Diversi dettagli sono nella fascia alta",
    "Vari elementi sono nel loro meglio", "Parecchi aspetti sono ben calibrati",
    "Diversi punti forti emergono chiaramente", "Molti elementi sono apprezzabili",
    "Ci sono diversi aspetti che funzionano bene", "Vari dettagli mostrano cura",
    "Diversi aspetti sono nella direzione corretta", "Parecchi elementi sono riconoscibilmente riusciti",
    "Molti dettagli sono nella nota alta", "Ci sono diversi aspetti ben pensati",
    "Vari elementi sono nella giusta misura", "Diverse componenti funzionano a dovere",
    "Parecchi aspetti mostrano ricerca", "Molti elementi sono equilibrati",
    "Diversi aspetti risultano convincenti", "Ci sono elementi meritevoli di nota",
    "Vari pregi sono tangibili", "Parecchi dettagli sono da sottolineare",
],

# ── 64x ──
"Sono uno di quei paia che": [
    "Rientrano tra quei paia che", "Appartengono alla categoria di paia che",
    "Si collocano tra quei modelli che", "Fanno parte di quella famiglia di occhiali che",
    "Sono del tipo di paia che", "Si iscrivono tra quei paia che",
    "Si posizionano tra quei modelli che", "Entrano nella lista dei paia che",
    "Sono nella schiera dei modelli che", "Rientrano nel gruppo di paia che",
    "Appartengono a quei modelli che", "Fanno parte di quei paia che",
    "Si collocano nella fascia dei modelli che", "Sono un esempio di paia che",
    "Si inseriscono tra quei paia che", "Rientrano nella tipologia di paia che",
    "Appartengono alla famiglia dei modelli che", "Sono nella categoria dei paia che",
    "Si annoverano tra quei paia che", "Sono del genere di modelli che",
    "Fanno parte della schiera di paia che", "Si classificano tra quei paia che",
    "Rientrano nella cerchia di modelli che", "Sono un esempio di quei paia che",
    "Appartengono a quella tipologia di paia che", "Si iscrivono nella lista dei modelli che",
    "Si posizionano nella categoria dei paia che", "Rientrano tra quei modelli speciali che",
    "Si situano tra quei paia che", "Entrano nella categoria dei modelli che",
    "Sono tra quei paia che", "Si inseriscono nella collocazione dei modelli che",
    "Fanno parte di quei modelli particolari che", "Rientrano nel novero dei paia che",
    "Si collocano tra i paia che", "Appartengono ai paia che",
    "Sono nella fascia dei modelli che", "Si iscrivono tra quei modelli che",
    "Rientrano tra quelle proposte che", "Si posizionano tra i paia che",
    "Fanno parte dei modelli che", "Si classificano tra i paia che",
    "Entrano nel novero dei paia che", "Sono tra i modelli che",
    "Si inseriscono tra i modelli che", "Rientrano nella gamma dei paia che",
    "Appartengono alla gamma di paia che", "Si collocano nella gamma dei modelli che",
    "Fanno parte della gamma di modelli che", "Si annoverano tra i modelli che",
    "Sono un caso di paia che", "Rientrano tra i modelli con la specificità che",
    "Si posizionano nella lista dei paia che", "Appartengono a quei design che",
    "Entrano nella famiglia dei modelli che", "Si iscrivono nella cerchia dei paia che",
    "Sono nella lista di quei paia che", "Rientrano nella famiglia di modelli che",
    "Fanno parte di quei design che", "Si inseriscono nel gruppo dei paia che",
    "Sono del tipo che", "Si collocano nella tipologia dei paia che",
    "Rientrano tra i design che", "Appartengono alla lista dei paia che",
],

# ── 61x ──
"Non arrivo al massimo dei voti perché": [
    "Non do il massimo perché", "Il punteggio pieno manca perché",
    "Non raggiungo la perfezione perché", "La stella mancante è dovuta al fatto che",
    "Non assegno il voto pieno perché", "Il massimo non arriva perché",
    "Non concedo la valutazione massima perché", "Il voto non è pieno perché",
    "Il punteggio non tocca il tetto perché", "Non premio con il massimo perché",
    "Non do cinque stelle perché", "Il voto pieno sfugge perché",
    "Non arrivo al tetto della scala perché", "La valutazione massima manca perché",
    "Il massimo dei voti si allontana perché", "Non confermo il punteggio pieno perché",
    "Il voto resta sotto il massimo perché", "Non assegno la valutazione più alta perché",
    "Non gli do il cinque perché", "Il punteggio resta un gradino sotto il massimo perché",
    "La perfezione nel voto si allontana perché", "Non arrivo alla valutazione piena perché",
    "Il cinque non arriva perché", "Non concedo il punteggio massimo perché",
    "Il voto non tocca il limite perché", "Non premio al massimo perché",
    "Non raggiunge il cinque perché", "Il voto massimo non è giustificato perché",
    "Non assegno cinque stelle perché", "Il punteggio non raggiunge il vertice perché",
    "Il massimo è irraggiungibile perché", "Non si arriva al cinque perché",
    "La valutazione non è massima perché", "Il voto si ferma prima del cinque perché",
    "Non attribuisco il cinque perché", "Il punteggio pieno non c'è perché",
    "Il voto non raggiunge la capienza massima perché", "Non do il voto più alto perché",
    "Non arrivo al vertice della scala perché", "Il massimo del punteggio manca perché",
    "Non concedo il massimo perché", "La valutazione non arriva al massimo perché",
    "Il punteggio si ferma un gradino sotto perché", "Non assegno il cinque pieno perché",
    "Il voto resta alto ma non massimo perché", "Non tocco il cinque perché",
    "La valutazione non è la più alta perché", "Non premio con cinque stelle perché",
    "Il voto si ferma prima del massimo perché", "Non raggiungo il cinque perché",
    "Il voto massimo non si materializza perché", "Non arrivo al cinque pieno perché",
    "La valutazione rimane sotto il massimo perché", "Non do la valutazione piena perché",
    "Il punteggio si ferma sotto il tetto perché", "Il cinque sfugge perché",
    "Non do il massimo della scala perché", "Il voto non arriva al cinque perché",
    "Non concedo la valutazione più alta perché", "La valutazione si ferma prima della massima perché",
    "Non attribuisco il punteggio pieno perché",
],

}
