#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Dizionario PATTERN -> ALTERNATIVE (Parte 12: pattern residui finali 20x+)"""

RESIDUAL_FINAL = {

"Li ho portati durante un weekend a Bologna.": [
    "Li ho portati durante un fine settimana fuori città.",
    "Li ho indossati durante un weekend in trasferta.",
    "Li ho usati per un fine settimana fuori porta.",
    "Li ho portati per un weekend in giro.",
    "Li ho indossati per un fine settimana di svago.",
    "Li ho usati durante un weekend di svago.",
    "Li ho portati per un fine settimana in un'altra città.",
    "Li ho indossati durante un weekend fuori casa.",
    "Li ho usati per un fine settimana di relax.",
    "Li ho portati durante un weekend lungo.",
    "Li ho indossati per un fine settimana di esplorazione.",
    "Li ho usati durante un weekend in viaggio.",
    "Li ho portati per un fine settimana in giro per la città.",
    "Li ho indossati durante un weekend di passeggiate.",
    "Li ho usati per un fine settimana fuori dalla routine.",
    "Li ho portati durante un weekend esplorativo.",
    "Li ho indossati per un fine settimana in centro.",
    "Li ho usati durante un weekend all'aria aperta.",
    "Li ho portati per un fine settimana di svago e relax.",
    "Li ho indossati per un weekend in una città diversa.",
    "Li ho usati per un fine settimana fuori dal solito.",
    "Li ho portati durante un weekend in esplorazione.",
    "Li ho indossati per un fine settimana rilassante.",
    "Li ho usati durante un weekend fuori dalle solite rotte.",
    "Li ho portati per un fine settimana di divertimento.",
    "Li ho indossati per un weekend fuori dal quotidiano.",
    "Li ho usati per un fine settimana intenso.",
    "Li ho portati durante un weekend speciale.",
    "Li ho indossati per un fine settimana pieno di impegni.",
    "Li ho usati durante un weekend in libertà.",
],

"La prima volta li ho indossati di sera,": [
    "La prima volta che li ho messi è stata di sera,",
    "Li ho provati per la prima volta in una serata,",
    "La prima indossata è avvenuta di sera,",
    "Li ho messi per la prima volta una sera,",
    "La prima esperienza con loro è stata serale,",
    "Li ho indossati la prima volta un tardo pomeriggio,",
    "La prima prova è avvenuta la sera,",
    "Li ho provati inizialmente di sera,",
    "La prima volta che li ho portati è stata in serata,",
    "Li ho messi la prima volta alla sera,",
    "La prima esperienza è stata serale,",
    "Li ho indossati la prima volta nel tardo pomeriggio,",
    "La prima prova è stata di sera,",
    "Li ho provati per la prima volta alla sera,",
    "La prima indossata è stata serale,",
    "Li ho messi per la prima volta in una tarda serata,",
    "La prima volta è stata di sera tardi,",
    "Li ho indossati la prima volta all'imbrunire,",
    "La prima prova l'ho fatta di sera,",
    "Li ho provati per la prima volta verso sera,",
    "La prima volta li ho messi la sera,",
    "Li ho indossati inizialmente la sera,",
    "La prima esperienza con me è stata serale,",
],

"È uno di quei modelli che vanno capiti prima di essere giudicati.": [
    "È un modello che richiede comprensione prima di essere valutato.",
    "È il tipo di modello che va vissuto prima di essere giudicato.",
    "È un modello che chiede pazienza prima di un giudizio.",
    "È il tipo di paio che va conosciuto prima di esprimere un parere.",
    "È un modello che richiede tempo per essere apprezzato.",
    "È il genere di modello che va provato prima di giudicarlo.",
    "È un paio che richiede comprensione prima del giudizio.",
    "È il tipo di modello che va sperimentato prima di valutarlo.",
    "È un modello che chiede di essere capito prima di essere classificato.",
    "È il genere di paio che va frequentato prima di giudicarlo.",
    "È un modello che richiede familiarità prima del giudizio.",
    "È il tipo di modello che va vissuto prima di poterlo valutare.",
    "È un paio che chiede conoscenza prima di un verdetto.",
    "È il genere di modello che va compreso prima di essere apprezzato.",
    "È un modello che richiede esperienza prima del giudizio finale.",
    "È il tipo di paio che va capito nella sua totalità prima di giudicarlo.",
    "È un modello che chiede tempo e pazienza prima di un parere.",
    "È il genere di modello che va esplorato prima del verdetto.",
    "È un paio che richiede attenzione prima di essere giudicato.",
    "È il tipo di modello che va addomesticato prima di un giudizio.",
    "È un modello che chiede di essere conosciuto nel tempo.",
    "È il genere di paio che va apprezzato con calma.",
    "È un modello che ha bisogno di tempo per essere capito.",
],

"Ha una presenza che non dipende dal logo,": [
    "Ha un impatto che non dipende dal marchio,",
    "Ha un carattere che non è legato al logo,",
    "Ha una personalità indipendente dal brand,",
    "Ha una forza visiva che non passa dal logo,",
    "Ha un'autorità che non deriva dal marchio,",
    "Ha una presenza che prescinde dal logo,",
    "Ha un impatto che non è questione di logo,",
    "Ha un carattere che va oltre il marchio,",
    "Ha una personalità che non si basa sul logo,",
    "Ha una forza che non dipende dall'etichetta,",
    "Ha un'autorità che non è legata al brand,",
    "Ha una presenza che non ha bisogno del logo,",
    "Ha un impatto che non è frutto del marchio,",
    "Ha un carattere indipendente dall'etichetta,",
    "Ha una personalità che non si riduce al logo,",
    "Ha una forza che prescinde dal brand,",
    "Ha un'autorità innata, non da logo,",
    "Ha una presenza che si impone senza il marchio,",
    "Ha un impatto che non viene dal logo,",
    "Ha un carattere che non necessita del marchio,",
    "Ha una personalità autonoma dal logo,",
    "Ha una forza comunicativa che va oltre il brand,",
    "Ha un'autorità che non dipende dall'etichetta,",
],

"Non sono perfetti in assoluto,": [
    "Non sono impeccabili,",
    "Non raggiungono la perfezione,",
    "Non sono privi di difetti,",
    "Non sono flawless,",
    "Non toccano la perfezione assoluta,",
    "Non sono senza imperfezioni,",
    "Non sono al 100%,",
    "Non sono esenti da difetti,",
    "Non sono la perfezione incarnata,",
    "Non brillano di perfezione,",
    "Non sono il paio perfetto,",
    "Non sono completamente privi di limiti,",
    "Non sono del tutto privi di pecche,",
    "Non raggiungono la perfezione totale,",
    "Non sono al di sopra di ogni critica,",
    "Non mancano di qualche imperfezione,",
    "Non sono esenti da qualche limite,",
    "Non sono il paio dei sogni in assoluto,",
    "Non sono perfetti al 100%,",
    "Non si può dire che siano perfetti,",
    "Non sono senza macchia,",
    "Non raggiungono l'eccellenza assoluta,",
    "Non si arriva alla perfezione pura,",
],

"Per questo resta un sì con riserva.": [
    "Per questo il giudizio è un sì con qualche nota.",
    "Per questo è un sì con qualche cautela.",
    "Per questo il verdetto è un sì condizionato.",
    "Per questo la mia risposta è un sì parziale.",
    "Per questo il mio parere è un sì con qualche ma.",
    "Per questo è un sì con qualche riserva.",
    "Per questo il giudizio è un sì temperato.",
    "Per questo la risposta è un sì non incondizionato.",
    "Per questo il verdetto è un sì con qualche clausola.",
    "Per questo è un sì con qualche distinguo.",
    "Per questo il mio giudizio è un sì con sfumature.",
    "Per questo la risposta resta un sì con margine.",
    "Per questo è un sì con qualche avvertenza.",
    "Per questo il parere è un sì ragionato.",
    "Per questo il verdetto è un sì moderato.",
    "Per questo è un sì con qualche postilla.",
    "Per questo la risposta è un sì attento.",
    "Per questo il giudizio è un sì meditato.",
    "Per questo è un sì con qualche nota di cautela.",
    "Per questo il mio parere è un sì informato.",
    "Per questo il verdetto è un sì con qualche distinguo.",
    "Per questo è un sì con qualche precisazione.",
    "Per questo la risposta è un sì con qualche puntualizzazione.",
],

"Non è tanto una questione di moda, quanto di qualcosa che ti rappresenta.": [
    "Non è tanto una questione di tendenza, quanto di identità.",
    "Non riguarda la moda, ma il modo in cui ti rappresentano.",
    "Non è una questione di trend, ma di come ti raccontano.",
    "Non è tanto moda quanto espressione personale.",
    "Non è una questione di tendenza, ma di ciò che comunichi.",
    "Non riguarda la moda in sé, ma la tua identità.",
    "Non è tanto una questione di trend, quanto di rappresentazione.",
    "Non è moda: è trovare qualcosa che parla di te.",
    "Non è una questione di tendenza, ma di rispecchiamento.",
    "Non riguarda il fashion, ma il modo in cui definisci te stesso.",
    "Non è tanto moda, quanto un pezzo che ti appartiene.",
    "Non è una questione di tendenze, ma di autenticità.",
    "Non riguarda la moda del momento, ma la tua identità.",
    "Non è tanto una questione di stile, quanto di identità autentica.",
    "Non è moda: è qualcosa che dice chi sei.",
    "Non riguarda le tendenze, ma il modo in cui ti esprimi.",
    "Non è tanto una questione di trend, quanto di personalità.",
    "Non è moda: è un pezzo che ti definisce.",
    "Non riguarda la moda in senso stretto, ma il tuo modo di raccontarti.",
    "Non è tanto una questione di stile, quanto di espressione personale.",
    "Non è moda: è identità.",
    "Non riguarda le tendenze, ma ciò che senti tuo.",
    "Non è tanto una questione di tendenza, quanto di espressione.",
],

"e il colpo d'occhio è buono, ma non trascina.": [
    "e l'impatto visivo è positivo, ma non entusiasma.",
    "e la prima impressione è buona, ma non soggioga.",
    "e l'effetto visivo è gradevole, ma non conquista.",
    "e il colpo d'occhio funziona, ma non rapisce.",
    "e l'impatto iniziale è buono, ma non travolge.",
    "e la resa visiva è positiva, ma non emoziona.",
    "e l'effetto iniziale piace, ma non incanta.",
    "e il primo impatto è buono, ma non folgorante.",
    "e la resa d'impatto è positiva, ma non magnetica.",
    "e l'effetto visivo è gradevole, ma non travolgente.",
    "e il colpo d'occhio funziona, ma senza rapire.",
    "e l'impatto è buono, ma non da innamoramento.",
    "e la prima impressione è positiva, ma non esplosiva.",
    "e l'effetto iniziale è valido, ma non irresistibile.",
    "e il colpo d'occhio è promettente, ma non magnetico.",
    "e l'impatto visivo è gradevole, ma non trascinante.",
    "e la resa d'impatto è positiva, ma senza magia.",
    "e il primo effetto è buono, ma non folgorante.",
    "e l'impressione iniziale è positiva, ma non rapisce.",
    "e il colpo d'occhio funziona, ma non soggioga.",
    "e l'impatto è buono, ma manca quel quid in più.",
    "e la prima impressione è positiva, ma non irresistibile.",
    "e il colpo d'occhio è gradevole, ma non conquista.",
],

"Hanno quel tipo di design che non chiede attenzione, la merita.": [
    "Hanno un design che non chiede attenzione: la guadagna.",
    "Il loro design non reclama attenzione: la conquista.",
    "Hanno un design che non cerca l'attenzione: la ottiene autonomamente.",
    "Il design non si impone: si fa notare con merito.",
    "Hanno un design che non urla per l'attenzione: la merita silenziosamente.",
    "Il loro design non cerca visibilità: la guadagna per qualità.",
    "Hanno un design che non chiede di essere guardato: merita di esserlo.",
    "Il design non cerca i riflettori: li merita naturalmente.",
    "Hanno un design che non si propone: si impone da solo.",
    "Il loro design non reclama sguardi: li attira con merito.",
    "Hanno un design che non fa rumore: parla da solo.",
    "Il design non cerca attenzione in modo forzato: la conquista.",
    "Hanno un design che non si pubblicizza: si fa apprezzare.",
    "Il loro design non si sforza di farsi notare: accade naturalmente.",
    "Hanno un design che non pretende di essere visto: si fa vedere.",
    "Il design non chiede il palcoscenico: lo occupa con naturalezza.",
    "Hanno un design che non invoca attenzione: la riceve per merito.",
    "Il loro design non fa campagna per sé: si impone da solo.",
    "Hanno un design che non cerca consenso: lo ottiene con la qualità.",
    "Il design non reclama spazio: lo occupa con eleganza.",
    "Hanno un design che non si esibisce: si fa apprezzare spontaneamente.",
    "Il loro design non chiede visibilità: la merita per qualità intrinseca.",
    "Hanno un design che non insegue attenzione: la guadagna silenziosamente.",
],

"senza bisogno di costruirgli attorno un outfit studiato.": [
    "senza dover costruire un outfit apposta attorno a loro.",
    "senza necessità di un outfit studiato.",
    "senza bisogno di un look costruito ad hoc.",
    "senza doverci costruire un look specifico attorno.",
    "senza necessità di un outfit pensato apposta.",
    "senza bisogno di costruire un look particolare.",
    "senza dover pianificare un outfit attorno al paio.",
    "senza necessità di un guardaroba costruito attorno.",
    "senza bisogno di un look architettato apposta.",
    "senza doverci costruire un outfit apposito.",
    "senza necessità di un look curato nei minimi dettagli.",
    "senza bisogno di abbinarci un outfit pensato.",
    "senza dover creare un look specifico per loro.",
    "senza necessità di costruire il resto del look attorno.",
    "senza bisogno di un outfit coordinato con precisione.",
    "senza doverci costruire un look studiato.",
    "senza necessità di un abbinamento ricercato.",
    "senza bisogno di un outfit elaborato.",
    "senza dover orchestrare il resto del look.",
    "senza necessità di un outfit calcolato.",
    "senza bisogno di un look meditato.",
    "senza doverci costruire attorno un outfit complesso.",
    "senza necessità di un look architettato.",
],

"questa cosa alla lunga pesa un po'.": [
    "a lungo andare questa cosa si sente.",
    "col tempo questa cosa pesa.",
    "alla lunga questo aspetto emerge.",
    "nel lungo periodo questa cosa pesa.",
    "con l'uso prolungato questa cosa si nota.",
    "alla lunga questo dettaglio pesa.",
    "col passare del tempo questa cosa diventa un peso.",
    "nel lungo uso questa cosa si fa sentire.",
    "alla lunga questo elemento diventa un limite.",
    "col tempo questa cosa diventa più evidente.",
    "nel lungo periodo questo aspetto diventa un peso.",
    "alla lunga questa cosa non passa inosservata.",
    "col uso ripetuto questa cosa pesa.",
    "nel lungo termine questo dettaglio diventa un fattore.",
    "alla lunga questa cosa comincia a pesare.",
    "col tempo questo aspetto diventa un limite.",
    "nel lungo periodo questa cosa si fa notare.",
    "alla lunga questo elemento si fa sentire.",
    "col passare del tempo questo dettaglio pesa.",
    "nel lungo uso questo aspetto emerge.",
    "alla lunga questa cosa diventa un punto debole.",
    "col tempo questa cosa diventa un nodo.",
    "nel lungo periodo questo dettaglio emerge.",
],

"lavorano insieme in un modo che mi piace molto.": [
    "lavorano in sinergia in un modo che trovo molto piacevole.",
    "si combinano in un modo che mi piace particolarmente.",
    "collaborano in un modo che apprezzo molto.",
    "interagiscono in un modo che mi convince molto.",
    "funzionano insieme in un modo che mi soddisfa molto.",
    "si integrano in un modo che trovo molto riuscito.",
    "si armonizzano in un modo che mi piace davvero tanto.",
    "dialogano in un modo che trovo molto coerente.",
    "si fondono in un modo che apprezzo molto.",
    "si completano in un modo che mi piace molto.",
    "collaborano in un modo che trovo molto efficace.",
    "interagiscono in un modo che mi soddisfa particolarmente.",
    "lavorano in armonia in un modo che trovo molto bello.",
    "si combinano in un modo che apprezzo particolarmente.",
    "funzionano insieme in un modo che mi convince davvero.",
    "si integrano in un modo che mi piace molto.",
    "si armonizzano in un modo che mi convince molto.",
    "dialogano in un modo che apprezzo molto.",
    "si fondono in un modo che mi piace molto.",
    "si completano in un modo che trovo molto efficace.",
    "collaborano in armonia in un modo che mi soddisfa.",
    "interagiscono in un modo che trovo molto riuscito.",
    "lavorano in sinergia in un modo che mi piace davvero.",
],

"ha trovato il suo senso in modo molto naturale.": [
    "ha trovato la sua ragion d'essere in modo molto spontaneo.",
    "ha acquisito significato in modo del tutto naturale.",
    "ha trovato il suo posto in modo naturale e fluido.",
    "ha assunto il suo senso senza alcuna forzatura.",
    "ha trovato la sua identità in modo molto organico.",
    "ha acquisito il suo ruolo in modo spontaneo.",
    "ha trovato il suo equilibrio in modo naturale.",
    "ha assunto il suo significato senza sforzo.",
    "ha trovato la sua dimensione in modo molto naturale.",
    "ha acquisito la sua ragion d'essere in modo fluido.",
    "ha trovato il suo spazio in modo del tutto organico.",
    "ha assunto il suo senso in modo spontaneo e naturale.",
    "ha trovato la sua collocazione in modo molto naturale.",
    "ha acquisito senso in modo graduale e spontaneo.",
    "ha trovato il suo posto senza alcuna forzatura.",
    "ha assunto il suo ruolo in modo del tutto naturale.",
    "ha trovato il suo senso con estrema naturalezza.",
    "ha acquisito significato senza nessuno sforzo.",
    "ha trovato la sua dimensione in modo spontaneo.",
    "ha assunto la sua identità in modo naturale.",
    "ha trovato il suo equilibrio senza forzature.",
    "ha acquisito il suo posto in modo organico.",
    "ha trovato il suo senso con naturalezza disarmante.",
],

"Il risultato finale ha un'energia che mi piace.": [
    "Il risultato complessivo ha un'energia che apprezzo.",
    "L'effetto finale ha un'energia che mi convince.",
    "Il risultato ha un'energia che trovo molto gradevole.",
    "L'insieme ha un'energia che mi attrae.",
    "Il risultato complessivo ha una vitalità che mi piace.",
    "L'effetto ha un'energia che apprezzo molto.",
    "Il risultato finale emana un'energia che mi convince.",
    "L'insieme ha una vitalità che trovo piacevole.",
    "Il risultato ha un'energia che mi soddisfa.",
    "L'effetto complessivo ha un'energia che apprezzo.",
    "Il risultato finale ha una forza che mi piace.",
    "L'insieme emana un'energia che mi convince.",
    "Il risultato ha una vitalità che trovo attraente.",
    "L'effetto finale ha una forza che apprezzo.",
    "Il risultato complessivo ha un dinamismo che mi piace.",
    "L'insieme ha un'energia che mi soddisfa.",
    "Il risultato ha una carica che mi convince.",
    "L'effetto ha una vitalità che apprezzo.",
    "Il risultato finale ha un dinamismo che mi attrae.",
    "L'insieme ha una forza che trovo molto gradevole.",
    "Il risultato complessivo ha una carica che mi piace.",
    "L'effetto finale ha un vigore che apprezzo.",
    "Il risultato ha un'energia che mi piace molto.",
],

"non basta per salvarlo nel mio uso quotidiano.": [
    "non è sufficiente a giustificarlo nel mio uso di tutti i giorni.",
    "non basta a salvarlo nella mia routine.",
    "non è abbastanza per renderlo parte del mio uso quotidiano.",
    "non basta a integrarlo nella mia vita di ogni giorno.",
    "non è sufficiente per il mio uso quotidiano.",
    "non basta a farlo entrare nella mia routine.",
    "non è abbastanza per giustificarlo nella pratica quotidiana.",
    "non basta a renderlo il mio paio di tutti i giorni.",
    "non è sufficiente a inserirlo nella mia rotazione regolare.",
    "non basta a salvarlo nel mio utilizzo quotidiano.",
    "non è abbastanza per il mio uso di tutti i giorni.",
    "non basta a integrarlo nella mia routine d'uso.",
    "non è sufficiente per farlo diventare un paio quotidiano.",
    "non basta a renderlo parte della mia rotazione giornaliera.",
    "non è abbastanza per salvarlo nell'uso quotidiano.",
    "non basta a giustificarlo nella pratica di ogni giorno.",
    "non è sufficiente a renderlo un paio della mia routine.",
    "non basta a farlo rientrare nel mio uso regolare.",
    "non è abbastanza per integrarlo nella mia vita quotidiana.",
    "non basta a salvarlo nella mia selezione di ogni giorno.",
    "non è sufficiente a farlo entrare nella mia routine quotidiana.",
    "non basta per renderlo il mio compagno quotidiano.",
    "non è abbastanza per giustificarlo nel mio uso giornaliero.",
],

"e tutto il resto perde forza.": [
    "e il resto diventa secondario.",
    "e tutto il resto sbiadisce.",
    "e il resto passa in secondo piano.",
    "e tutto il resto perde rilievo.",
    "e il resto diventa meno importante.",
    "e tutto il resto perde peso.",
    "e il resto svuota di significato.",
    "e tutto il resto arretra.",
    "e il resto perde di importanza.",
    "e tutto il resto si ridimensiona.",
    "e il resto perde centralità.",
    "e tutto il resto diventa marginale.",
    "e il resto perde incisività.",
    "e tutto il resto perde rilevanza.",
    "e il resto si riduce a contorno.",
    "e tutto il resto sfuma.",
    "e il resto perde consistenza.",
    "e tutto il resto perde impatto.",
    "e il resto diventa rumore di fondo.",
    "e tutto il resto perde significato.",
    "e il resto perde la sua importanza.",
    "e tutto il resto diventa trascurabile.",
    "e il resto perde la sua forza.",
],

}
