#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Dizionario PATTERN -> ALTERNATIVE (Parte 15: residui ad alta frequenza 31x-13x)"""

FINAL_HIGH = {

"Quando un modello continua a convincermi dopo più uscite, per me ha già vinto.": [
    "Se un paio mi piace ancora dopo tante uscite, il giudizio è definitivo.",
    "Se un modello regge dopo molti utilizzi, per me è promosso.",
    "Quando un paio mi convince ancora dopo settimane, per me è un successo.",
    "Se un modello continua a funzionare dopo tante prove, il verdetto è positivo.",
    "Se un paio resiste alla prova del tempo, per me non c'è altro da dire.",
    "Un modello che piace ancora dopo molte uscite ha superato ogni test.",
    "Se dopo tanti utilizzi lo scelgo ancora volentieri, per me ha vinto.",
    "Un paio che continua a convincermi nel tempo è già promosso.",
    "Se un modello regge l'uso prolungato, per me il discorso è chiuso.",
    "Quando un paio funziona ancora dopo settimane d'uso, il giudizio è netto.",
    "Se un modello tiene dopo tante uscite, per me è la conferma definitiva.",
    "Un paio che convince nel tempo ha già detto tutto.",
    "Se dopo molte uscite lo scelgo ancora, per me il verdetto è chiaro.",
    "Quando un modello piace anche dopo l'entusiasmo iniziale, è un vero successo.",
    "Se un paio regge la prova del quotidiano, per me è vincente.",
    "Un modello che convince ancora dopo tanti utilizzi merita rispetto.",
    "Se dopo settimane lo indosso ancora volentieri, per me è il miglior test.",
    "Quando un paio supera la fase della novità e piace ancora, è promosso.",
],

"Mi sembra un modello con pregi chiari e limiti altrettanto leggibili.": [
    "Mi pare un modello con punti di forza evidenti e difetti altrettanto visibili.",
    "Mi sembra un paio con qualità chiare e limiti altrettanto evidenti.",
    "Lo vedo come un modello con pregi innegabili e difetti comprensibili.",
    "Mi pare un paio con virtù chiare e limiti ben definiti.",
    "Lo considero un modello con qualità evidenti e limiti prevedibili.",
    "Mi sembra un paio che mostra pregi e difetti con uguale chiarezza.",
    "Lo vedo come un modello con punti di forza e limiti entrambi leggibili.",
    "Mi pare un paio con qualità nette e difetti altrettanto chiari.",
    "Lo considero un modello con pregi evidenti e limiti altrettanto visibili.",
    "Mi sembra un paio le cui qualità e i cui limiti sono entrambi trasparenti.",
    "Lo vedo come un modello con virtù innegabili e difetti comprensibili.",
    "Mi pare un paio con pregi e limiti entrambi in bella vista.",
    "Lo considero un modello le cui qualità e le cui riserve sono entrambe evidenti.",
    "Mi sembra un paio con punti forti e punti deboli entrambi visibili.",
    "Lo vedo come un modello trasparente nei pregi e nei limiti.",
    "Mi pare un paio con qualità e difetti entrambi ben definiti.",
    "Lo considero un modello con pregi chiari e riserve altrettanto leggibili.",
    "Mi sembra un paio il cui bilancio tra pregi e limiti è evidente.",
],

"Mi aspettavo un modello interessante, non uno che mi venisse voglia di rimettere subito.": [
    "Pensavo a un modello interessante, non a uno che volessi indossare di nuovo immediatamente.",
    "Mi aspettavo un modello valido, non uno che mi facesse venire voglia di rimetterlo subito.",
    "Immaginavo un modello curioso, non uno che mi avrebbe conquistato al primo utilizzo.",
    "Pensavo sarebbe stato interessante, non che mi sarebbe venuta voglia di rimetterlo subito.",
    "Mi aspettavo un modello apprezzabile, non uno che mi facesse desiderare di riusarlo immediatamente.",
    "Pensavo a un buon modello, non a uno che volessi indossare di continuo.",
    "Immaginavo un modello piacevole, non uno da rimettere con entusiasmo subito dopo.",
    "Mi aspettavo un modello dignitoso, non uno che mi avrebbe fatto venire voglia di rimetterlo al volo.",
    "Pensavo fosse un modello discreto, non uno da indossare di nuovo subito.",
    "Mi aspettavo un modello gradevole, non uno da cui non volessi più separarmi.",
    "Immaginavo un modello buono, non uno che mi facesse venire voglia di usarlo di continuo.",
    "Pensavo sarebbe stato carino, non che mi avrebbe conquistato fino a volerlo rimettere subito.",
    "Mi aspettavo un buon prodotto, non uno da indossare con entusiasmo ogni volta.",
    "Immaginavo un modello valido, non uno che mi facesse tornare la voglia di usarlo immediatamente.",
    "Pensavo a un modello corretto, non a uno che mi avrebbe fatto desiderare di rimetterlo subito.",
    "Mi aspettavo qualcosa di interessante, non di trovare un paio da cui non staccarmi.",
    "Immaginavo un modello apprezzabile, non uno da rimettere con piacere ogni volta.",
    "Pensavo a un modello gradevole, non a uno che mi facesse venire voglia di rimetterlo al volo.",
],

"Lo promuovo senza esitazioni, con la sola avvertenza che va capito prima di essere davvero amato.": [
    "Lo promuovo senza dubbi, con la sola nota che richiede tempo per essere apprezzato davvero.",
    "Lo consiglio senza riserve, avvertendo solo che va compreso prima di essere amato.",
    "Lo promuovo pienamente, con l'unica nota che serve pazienza per amarlo davvero.",
    "Lo consiglio con convinzione, premettendo solo che va capito prima di innamorarsene.",
    "Lo promuovo senza esitare, precisando solo che richiede conoscenza prima di conquistare.",
    "Lo consiglio senza riserve, con la sola premessa che si apprezza col tempo.",
    "Lo promuovo volentieri, avvertendo solo che il suo fascino si rivela gradualmente.",
    "Lo consiglio con sicurezza, premettendo solo che va vissuto per essere amato.",
    "Lo promuovo senza dubbi, con l'unica nota che il suo valore emerge col tempo.",
    "Lo consiglio pienamente, avvertendo solo che va conosciuto prima di innamorarsene.",
    "Lo promuovo con convinzione, precisando solo che serve tempo per apprezzarlo a fondo.",
    "Lo consiglio senza esitare, con la sola premessa che va capito per essere apprezzato.",
    "Lo promuovo volentieri, premettendo solo che il suo fascino non è immediato.",
    "Lo consiglio con sicurezza, avvertendo solo che richiede qualche utilizzo per essere amato.",
    "Lo promuovo senza riserve, con l'unica nota che chiede tempo per rivelare il suo valore.",
    "Lo consiglio pienamente, precisando solo che va conosciuto per essere davvero apprezzato.",
    "Lo promuovo con entusiasmo, avvertendo solo che il suo fascino si svela poco a poco.",
    "Lo consiglio senza dubbi, premettendo solo che serve pazienza per coglierne il valore.",
],

"Sono uno di quei paia che ti fanno venire voglia di uscire anche solo per indossarli.": [
    "Sono di quei paia che ti spingono a uscire anche solo per il piacere di indossarli.",
    "Sono il tipo di paia che ti fanno inventare una scusa per uscire.",
    "Sono di quei paia che ti motivano a uscire solo per il gusto di portarli.",
    "Sono il genere di paia che ti fanno venire voglia di trovare un'occasione per metterli.",
    "Sono di quei paia che ti spingono fuori casa anche solo per sfoggiare.",
    "Sono il tipo di paia che ti fanno desiderare di uscire solo per indossarli.",
    "Sono di quei paia che ti inventano un'uscita solo per essere portati.",
    "Sono il genere di paia che ti fanno cercare un pretesto per uscire.",
    "Sono di quei paia che ti danno una ragione in più per uscire.",
    "Sono il tipo di paia che ti spingono a trovare un'occasione per usarli.",
    "Sono di quei paia che rendono qualsiasi uscita un po' più piacevole.",
    "Sono il genere di paia che ti fanno venire voglia di uscire prima del previsto.",
    "Sono di quei paia che ti fanno desiderare di trovare un motivo per uscire.",
    "Sono il tipo di paia che ti fanno venir voglia di organizzare qualcosa solo per metterli.",
    "Sono di quei paia che ti spingono a uscire anche quando non ne avresti bisogno.",
    "Sono il genere di paia che ti danno la motivazione giusta per uscire.",
    "Sono di quei paia che ti fanno venire voglia di vivere fuori casa.",
    "Sono il tipo di paia che ti fanno inventare uscite pur di portarli.",
],

"Non cerco mai l'effetto influencer, cerco il paio giusto.": [
    "Non cerco l'effetto social, cerco il paio che mi rappresenti.",
    "Non inseguo le tendenze degli influencer, cerco quello che mi sta bene.",
    "Non cerco lo stile da Instagram, cerco il paio che funziona davvero.",
    "Non voglio l'effetto scenico, voglio il paio che mi calza.",
    "Non cerco l'effetto wow dei social, cerco ciò che funziona nel quotidiano.",
    "Non inseguo l'estetica da influencer, cerco la sostanza.",
    "Non cerco l'apparenza da trend, cerco il paio che mi accompagna.",
    "Non voglio sembrare un influencer, voglio solo il paio giusto per me.",
    "Non cerco il colpo d'occhio da social, cerco la qualità vera.",
    "Non inseguo l'effetto da vetrina, cerco ciò che mi sta davvero bene.",
    "Non cerco l'approvazione social, cerco il paio che mi convince addosso.",
    "Non voglio l'effetto da trend, voglio ciò che funziona nella mia vita.",
    "Non cerco lo stile da content creator, cerco il paio che mi calza.",
    "Non inseguo le mode dei social, cerco la mia personale soddisfazione.",
    "Non cerco l'effetto da story, cerco il paio che mi fa sentire a posto.",
    "Non voglio l'effetto da post virale, voglio il paio che mi rappresenta.",
    "Non cerco l'estetica patinata, cerco il paio che funziona su di me.",
    "Non inseguo tendenze altrui, cerco il paio che parla di me.",
],

"Sono riuscito a volergli bene solo da fermo, non indossandolo.": [
    "Li ho apprezzati solo guardandoli, non portandoli.",
    "Sono riuscito ad amarli solo da fermo, non addosso.",
    "Li ho trovati belli solo in mano, non sul viso.",
    "Sono riuscito ad apprezzarli solo da fermi, non indossati.",
    "Li ho amati solo guardandoli, non portandoli addosso.",
    "Sono riuscito a trovarli belli solo nella custodia, non sul viso.",
    "Li ho apprezzati come oggetto, non come accessorio portato.",
    "Sono riuscito ad amarli solo come oggetto, non come paio indossato.",
    "Li ho trovati affascinanti solo da fermi, non addosso.",
    "Sono riuscito a volergli bene solo in teoria, non nella pratica.",
    "Li ho apprezzati solo esteticamente, non nell'uso.",
    "Sono riuscito ad amarli solo guardandoli sul tavolo, non allo specchio.",
    "Li ho trovati belli solo come oggetto, non come paio da portare.",
    "Sono riuscito ad apprezzarli solo quando non li indossavo.",
    "Li ho amati solo da lontano, non da vicino sul viso.",
    "Sono riuscito a trovarli belli solo come pezzo d'esposizione.",
    "Li ho apprezzati solo come design, non come esperienza d'uso.",
    "Sono riuscito ad amarli solo in foto, non addosso.",
],

"Ho voluto insistere, ma il dialogo non è mai partito davvero.": [
    "Ho provato a dargli tempo, ma l'intesa non è mai scattata.",
    "Ho insistito a lungo, ma la connessione non è mai arrivata.",
    "Ho voluto perseverare, ma il feeling non è mai nato.",
    "Ho provato a forzare, ma il rapporto non si è mai avviato.",
    "Ho insistito con pazienza, ma l'alchimia non è mai scattata.",
    "Ho voluto dargli un'altra chance, ma l'intesa non è mai arrivata.",
    "Ho provato a perseverare, ma il dialogo non si è mai aperto.",
    "Ho insistito oltre il ragionevole, ma il feeling non è mai arrivato.",
    "Ho voluto forzare la convivenza, ma non ha mai funzionato.",
    "Ho provato e riprovato, ma la scintilla non è mai scoccata.",
    "Ho insistito con ostinazione, ma il rapporto non è mai decollato.",
    "Ho voluto dargli più tempo del dovuto, ma niente da fare.",
    "Ho provato a insistere, ma la sintonia non è mai nata.",
    "Ho insistito oltre il necessario, ma l'intesa resta un miraggio.",
    "Ho voluto perseverare, ma il feeling non si è mai stabilito.",
    "Ho provato a dargli fiducia, ma il discorso non è mai decollato.",
    "Ho insistito con buona volontà, ma la connessione non è mai arrivata.",
    "Ho voluto crederci, ma il rapporto non è mai sbocciato.",
],

"Lo considero riuscito a metà: interessante, ma non spontaneo.": [
    "Lo considero un mezzo successo: intrigante, ma non immediato.",
    "Lo giudico riuscito a metà: affascinante, ma non naturale.",
    "Lo considero parzialmente riuscito: interessante, ma non fluido.",
    "Lo giudico un mezzo successo: curioso, ma non spontaneo.",
    "Lo considero a metà tra il successo e il tentativo: interessante, ma costruito.",
    "Lo giudico parzialmente riuscito: attraente, ma non immediato.",
    "Lo considero riuscito solo in parte: intrigante, ma non naturale.",
    "Lo giudico un successo parziale: affascinante, ma non spontaneo.",
    "Lo considero a metà: il design intriga, l'uso non convince.",
    "Lo giudico riuscito per metà: interessante sulla carta, meno nella pratica.",
    "Lo considero un prodotto a metà strada: curioso, ma non fluido.",
    "Lo giudico parzialmente: l'idea è buona, l'esecuzione meno.",
    "Lo considero un mezzo traguardo: affascinante, ma non disinvolto.",
    "Lo giudico a metà: intrigante come concept, meno come esperienza.",
    "Lo considero un successo parziale: il potenziale c'è, la naturalezza meno.",
    "Lo giudico riuscito solo in parte: curioso, ma non rilassato.",
    "Lo considero un buon tentativo non del tutto realizzato.",
    "Lo giudico un'idea riuscita a metà: bella, ma non spontanea.",
],

"Resto in una zona di mezzo: li rispetto, non li inseguo.": [
    "Mi trovo in una posizione intermedia: li stimo, ma non li desidero.",
    "Resto in un equilibrio neutro: li apprezzo, non li cerco.",
    "Sono in una terra di mezzo: li riconosco, non li inseguo.",
    "Mi trovo a metà strada: li rispetto, non li bramo.",
    "Resto in un limbo: li valuto, non li desidero.",
    "Sono in una posizione mediana: li stimo, non li cerco.",
    "Mi trovo in bilico: li apprezzo, non li inseguo.",
    "Resto in un'area grigia: li riconosco, non li bramo.",
    "Sono in una zona intermedia: li stimo, non li desidero.",
    "Mi trovo in equilibrio: li apprezzo intellettualmente, non li cerco.",
    "Resto a metà: li rispetto come prodotto, non li inseguo come paio.",
    "Sono in un punto neutro: li valuto, non li cerco attivamente.",
    "Mi trovo tra rispetto e indifferenza: li stimo, non li desidero.",
    "Resto in una posizione di mezzo: li apprezzo, non li bramo.",
    "Sono in un'area di rispetto senza passione.",
    "Mi trovo in una zona neutra: li riconosco, non li cerco.",
    "Resto tra il sì e il boh: li apprezzo, ma non li desidero.",
    "Sono in un territorio medio: li rispetto, non li rincorro.",
],

"Peccato, perché l'idea di fondo mi piaceva parecchio.": [
    "Un vero peccato, perché il concept mi entusiasmava.",
    "Peccato davvero, perché l'idea alla base mi convinceva molto.",
    "Un peccato, perché il concept di partenza mi piaceva molto.",
    "Peccato, perché l'ispirazione di fondo era davvero buona.",
    "Un vero peccato, perché il progetto alla base mi attraeva.",
    "Peccato davvero, perché l'idea originale mi aveva convinto.",
    "Un peccato, perché la visione di fondo era la mia.",
    "Peccato, perché il concept mi aveva conquistato sulla carta.",
    "Un vero peccato, perché l'idea di partenza era brillante.",
    "Peccato davvero, perché il progetto mi entusiasmava.",
    "Un peccato, perché l'ispirazione alla base era convincente.",
    "Peccato, perché il concept originale mi piaceva davvero tanto.",
    "Un vero peccato, perché l'idea alla base meritava di più.",
    "Peccato davvero, perché la visione di fondo era ottima.",
    "Un peccato, perché l'idea mi aveva conquistato in partenza.",
    "Peccato, perché il progetto di base era davvero promettente.",
    "Un vero peccato, perché l'ispirazione originale era quella giusta.",
    "Peccato davvero, perché il concept mi aveva colpito molto.",
],

"Ho quarantadue anni e di solito diffido dei modelli troppo costruiti.": [
    "Ho quarantadue anni e tendenzialmente non mi fido dei modelli troppo elaborati.",
    "A quarantadue anni, ho imparato a diffidare dei modelli troppo costruiti.",
    "Ho quarantadue anni e solitamente evito i modelli troppo lavorati.",
    "Alla mia età, diffido istintivamente dei modelli troppo costruiti.",
    "Ho quarantadue anni e non mi lascio convincere facilmente dai modelli troppo elaborati.",
    "A quarantadue anni, ho sviluppato una certa diffidenza verso i modelli troppo costruiti.",
    "Ho quarantadue anni e preferisco la semplicità ai modelli troppo lavorati.",
    "Alla mia età, i modelli troppo costruiti mi lasciano perplesso.",
    "Ho quarantadue anni e l'esperienza mi ha insegnato a diffidare del troppo costruito.",
    "A quarantadue anni, preferisco la sostanza ai modelli troppo elaborati.",
    "Ho quarantadue anni e solitamente mi tengo alla larga dai modelli troppo lavorati.",
    "Alla mia età, non cerco più modelli troppo costruiti.",
    "Ho quarantadue anni e di solito scelgo la sobrietà rispetto alla costruzione eccessiva.",
    "A quarantadue anni, so riconoscere quando un modello è troppo costruito per me.",
    "Ho quarantadue anni e mi sono stancato dei modelli troppo elaborati.",
    "Alla mia età, preferisco modelli più naturali e meno costruiti.",
    "Ho quarantadue anni e cerco la semplicità, non la costruzione.",
    "A quarantadue anni, la mia esperienza mi allontana dai modelli troppo elaborati.",
],

"Ogni tanto lo trovo centrato, ogni tanto mi sembra chiedere troppo al resto del look.": [
    "A volte lo trovo perfetto, altre volte mi sembra esigere troppo dal resto dell'outfit.",
    "Talvolta lo trovo centrato, talvolta mi pare chiedere troppo al look.",
    "A volte lo giudico equilibrato, altre volte pretenzioso rispetto al resto.",
    "Talvolta funziona perfettamente, talvolta sembra esigere troppo dal contesto.",
    "A volte lo trovo in equilibrio, altre volte fuori scala rispetto al look.",
    "Talvolta mi sembra centrato, talvolta sovradimensionato rispetto all'insieme.",
    "A volte lo trovo giusto, altre volte domina troppo rispetto al look.",
    "Talvolta lo giudico equilibrato, talvolta troppo esigente verso il resto.",
    "A volte ci sta perfettamente, altre volte chiede troppo all'outfit.",
    "Talvolta lo trovo armonioso, talvolta sbilanciato rispetto al look.",
    "A volte funziona, altre volte sembra chiedere troppo al contesto.",
    "Talvolta mi sembra in equilibrio, talvolta troppo presente rispetto al look.",
    "A volte lo trovo centrato, altre volte sento che esige troppo dall'insieme.",
    "Talvolta è nel punto giusto, talvolta pretende troppo dal resto.",
    "A volte lo giudico perfetto, altre volte troppo dominante nel look.",
    "Talvolta funziona bene, talvolta sembra troppo per il contesto.",
    "A volte lo trovo in armonia, altre volte chiede troppo al look.",
    "Talvolta lo giudico centrato, talvolta sovraccaricante per l'insieme.",
],

"A forza di provarne, ho capito che il dettaglio fa più della moda.": [
    "Dopo averne provati tanti, ho capito che il dettaglio conta più della moda.",
    "Con l'esperienza, ho capito che i dettagli valgono più delle tendenze.",
    "Dopo molte prove, ho imparato che il dettaglio fa la differenza più della moda.",
    "A forza di provarli, ho capito che il dettaglio batte la moda.",
    "Con tanti tentativi, ho imparato che conta più il dettaglio della tendenza.",
    "Dopo averne testati molti, ho capito che il dettaglio è più importante della moda.",
    "A forza di provare modelli, ho imparato che il dettaglio supera la moda.",
    "Con l'esperienza di tanti paia, ho capito che il dettaglio fa la differenza.",
    "Dopo molte esperienze, ho imparato che il dettaglio pesa più della tendenza.",
    "A forza di provarli, ho capito che il dettaglio vale più di ogni tendenza.",
    "Con tanti modelli provati, ho imparato che il dettaglio è tutto.",
    "Dopo averne provati diversi, ho capito che il dettaglio supera ogni tendenza.",
    "A forza di provarne, ho capito che il dettaglio è ciò che resta.",
    "Con l'esperienza ho imparato che il dettaglio batte qualsiasi moda.",
    "Dopo tanti tentativi, ho capito che il dettaglio è ciò che conta davvero.",
    "A forza di provare, ho imparato che il dettaglio è più della moda.",
    "L'esperienza mi ha insegnato che il dettaglio vale più della tendenza.",
    "Dopo molti paia, ho capito che il dettaglio fa più di qualsiasi moda.",
],

}
