#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Dizionario PATTERN -> ALTERNATIVE (Parte 13: pattern residui 28x-17x)"""

RESIDUAL_EXTRA1 = {

"Forse su un altro volto il bilancio cambierebbe anche parecchio.": [
    "Su un viso diverso il giudizio potrebbe cambiare molto.",
    "Con altri lineamenti il bilancio potrebbe essere ben diverso.",
    "Su un altro tipo di volto la valutazione cambierebbe parecchio.",
    "Su altri tratti del viso il giudizio sarebbe probabilmente diverso.",
    "Con una diversa struttura facciale il bilancio cambierebbe.",
    "Su un volto diverso dal mio la resa potrebbe essere molto diversa.",
    "Con lineamenti differenti il giudizio potrebbe ribaltarsi.",
    "Su un'altra struttura del viso il bilancio sarebbe diverso.",
    "Con un viso diverso il risultato potrebbe cambiare radicalmente.",
    "Su altri lineamenti il giudizio potrebbe spostarsi di molto.",
    "Con un volto diverso l'esperienza potrebbe essere un'altra.",
    "Su un altro viso il bilancio potrebbe essere l'opposto.",
    "Con tratti diversi il giudizio cambierebbe considerevolmente.",
    "Su un viso con altra struttura il bilancio sarebbe diverso.",
    "Con lineamenti diversi la resa potrebbe cambiare in modo significativo.",
    "Su un volto diverso il rapporto con questo paio cambierebbe.",
    "Con un altro tipo di viso il giudizio sarebbe probabilmente un altro.",
    "Su lineamenti diversi il bilancio potrebbe spostarsi parecchio.",
    "Con un viso di forma diversa la valutazione cambierebbe.",
    "Su un altro volto il giudizio potrebbe oscillare molto.",
    "Con tratti facciali diversi il bilancio sarebbe probabilmente un altro.",
    "Su un viso con proporzioni diverse la resa cambierebbe.",
    "Con un altro tipo di lineamenti il bilancio potrebbe essere opposto.",
    "Su un volto di struttura diversa il giudizio cambierebbe notevolmente.",
    "Con un altro viso l'intero bilancio potrebbe ribaltarsi.",
    "Su lineamenti differenti la resa sarebbe probabilmente un'altra.",
    "Con un diverso tipo di volto il giudizio cambierebbe parecchio.",
    "Su un'altra faccia il bilancio potrebbe essere molto diverso.",
],

"Resto in quella zona grigia in cui apprezzo più di quanto desideri.": [
    "Rimango in quella terra di mezzo dove apprezzo più di quanto bramare.",
    "Mi trovo in un punto dove l'apprezzamento supera il desiderio.",
    "Resto in una zona ambigua: apprezzo, ma non desidero intensamente.",
    "Mi trovo a un bivio tra apprezzamento e desiderio non pieno.",
    "Rimango in quell'area dove l'apprezzamento c'è, il desiderio meno.",
    "Resto dove il rispetto supera il desiderio.",
    "Mi trovo in quella zona in cui capisco il valore ma non lo bramo.",
    "Rimango in un punto dove l'apprezzamento non diventa desiderio.",
    "Resto dove il giudizio è positivo ma il desiderio non è totale.",
    "Mi trovo in quell'area tra il rispetto e il desiderio non pieno.",
    "Rimango dove apprezzo con la testa ma non desidero con il cuore.",
    "Resto in quel punto dove il valore è chiaro ma il desiderio no.",
    "Mi trovo dove l'apprezzamento razionale supera la voglia istintiva.",
    "Rimango in quella zona dove il giudizio è buono ma il desiderio tiepido.",
    "Resto dove la stima c'è, il desiderio ardente meno.",
    "Mi trovo dove l'apprezzamento è intellettuale più che viscerale.",
    "Rimango in quel territorio dove apprezzo senza desiderare pienamente.",
    "Resto in un'area dove il riconoscimento c'è, la voglia resta parziale.",
    "Mi trovo dove il giudizio è rispettoso ma il desiderio non è acceso.",
    "Rimango dove l'apprezzamento è sincero ma il desiderio non totale.",
    "Resto in un punto dove capisco il valore senza bramare l'oggetto.",
    "Mi trovo in quella zona dove l'ammirazione non si trasforma in voglia.",
    "Rimango dove il rispetto è alto ma il desiderio non è al passo.",
    "Resto in quell'area dove il giudizio positivo non si traduce in desiderio.",
    "Mi trovo dove l'apprezzamento è genuino ma il desiderio resta a metà.",
],

"Mi lascia quella soddisfazione rara di aver scelto qualcosa con un'identità precisa.": [
    "Mi dà la rara soddisfazione di aver scelto qualcosa con una personalità definita.",
    "Mi regala quella sensazione rara di aver trovato qualcosa con un'anima propria.",
    "Mi lascia la soddisfazione, rara, di aver scelto un prodotto con identità.",
    "Mi dà quel raro piacere di aver scelto qualcosa con un carattere chiaro.",
    "Mi regala la soddisfazione insolita di aver trovato un paio con personalità.",
    "Mi lascia quella sensazione poco comune di aver scelto qualcosa con una voce.",
    "Mi dà la rara gioia di aver trovato un prodotto con un'identità forte.",
    "Mi regala quel senso raro di aver scelto qualcosa di definito.",
    "Mi lascia la soddisfazione non comune di aver trovato un paio con un'anima.",
    "Mi dà quella rara sensazione di aver scelto qualcosa con una direzione.",
    "Mi regala il raro piacere di aver trovato un prodotto con un carattere.",
    "Mi lascia quel senso raro di aver scelto qualcosa con una propria identità.",
    "Mi dà la soddisfazione insolita di aver trovato qualcosa con personalità.",
    "Mi regala quella sensazione rara di aver scelto un prodotto con una sua voce.",
    "Mi lascia il piacere raro di aver trovato qualcosa con un'identità netta.",
    "Mi dà quel senso raro di aver scelto qualcosa di autentico.",
    "Mi regala la soddisfazione rara di aver trovato un paio con identità propria.",
    "Mi lascia quella gioia insolita di aver scelto qualcosa con un carattere.",
    "Mi dà la soddisfazione rara di aver trovato un prodotto con un'anima.",
    "Mi regala il raro piacere di aver scelto qualcosa con una personalità definita.",
    "Mi lascia la rara sensazione di aver trovato un paio con identità chiara.",
    "Mi dà quel piacere insolito di aver scelto qualcosa con un'anima propria.",
    "Mi regala la soddisfazione poco comune di aver trovato qualcosa con carattere.",
],

"Non è amore cieco, ma è un sì convinto.": [
    "Non è entusiasmo acritico, ma è una conferma piena.",
    "Non è fanatismo, ma è un giudizio molto positivo.",
    "Non è un sì cieco, ma è un sì solido.",
    "Non è adorazione incondizionata, ma è un sì forte.",
    "Non è un trasporto irrazionale, ma è un giudizio molto positivo.",
    "Non è un'esaltazione cieca, ma è un'approvazione autentica.",
    "Non è entusiasmo acritico, ma è un sì ragionato e pieno.",
    "Non è un amore irrazionale, ma è un giudizio molto positivo.",
    "Non è un'adorazione cieca, ma è un sì pieno e convinto.",
    "Non è fanatismo, ma è un'approvazione solida.",
    "Non è entusiasmo senza ragione, ma è un sì motivato.",
    "Non è un sì cieco, ma è un sì profondo.",
    "Non è un trasporto acritico, ma è un giudizio molto favorevole.",
    "Non è adorazione senza criterio, ma è un'approvazione sincera.",
    "Non è un amore cieco: è un sì ragionato e forte.",
    "Non è entusiasmo irrazionale, ma è un sì autentico.",
    "Non è un sì incondizionato, ma è un sì molto forte.",
    "Non è fanatismo: è un'approvazione lucida e convinta.",
    "Non è un trasporto cieco, ma è un sì maturo.",
    "Non è adorazione: è un giudizio positivo e ragionato.",
    "Non è un amore irriflessivo, ma è un sì pieno.",
    "Non è entusiasmo cieco: è un sì consapevole.",
    "Non è un sì acritico, ma è un sì vero.",
],

"e ogni volta che lo metto penso a questo prima che al design. Peccato, perché qualche qualità ce l'ha.": [
    "e ogni volta che lo indosso, questo pensiero viene prima del design. Peccato, perché le qualità non mancano.",
    "e ad ogni utilizzo penso prima a questo che al design. Un peccato, perché le qualità ci sono.",
    "e questo pensiero mi accompagna ogni volta che lo metto, oscurando il design. Peccato, perché il valore c'è.",
    "e quando lo indosso, questo aspetto prevale sul design. Un peccato, dato che le qualità non mancano.",
    "e ogni volta questo pensiero supera l'apprezzamento del design. Peccato, perché avrebbe le carte in regola.",
    "e ad ogni indossata questo è il primo pensiero. Peccato, perché il design merita.",
    "e questo mi distrae dal design ogni volta. Un peccato, perché le qualità ci sono eccome.",
    "e quando lo metto penso a questo prima di tutto. Peccato, perché ha le sue qualità.",
    "e ogni volta che lo indosso questo aspetto domina. Un peccato, perché il design è valido.",
    "e ad ogni utilizzo questo prevale sul resto. Peccato, perché di qualità ne ha.",
    "e quando lo metto questo pensiero è il primo. Un peccato, dato che non manca di qualità.",
    "e ogni volta questo mi infastidisce più di quanto dovrebbe. Peccato, perché il prodotto ha il suo valore.",
    "e questo mi accompagna ad ogni indossata. Un peccato, perché le potenzialità ci sono.",
    "e ad ogni utilizzo penso prima a questo. Peccato, perché le qualità sono evidenti.",
    "e quando lo rimetto, questo è il primo pensiero che mi viene. Un peccato, perché il resto funziona.",
    "e ogni volta che lo indosso questo aspetto prevale. Peccato, perché il valore intrinseco c'è.",
    "e ad ogni indossata questo pesa. Peccato, perché per il resto è un buon prodotto.",
    "e quando lo porto questo pensiero domina. Un peccato vero, perché di qualità ne ha diverse.",
    "e ogni volta che lo metto questo mi preoccupa prima del design. Peccato, perché le qualità non mancano.",
    "e ad ogni utilizzo questo aspetto è il primo che noto. Peccato, dato che il design è interessante.",
    "e quando lo indosso penso prima a questo che al resto. Peccato, perché ha il suo fascino.",
],

"Tra quelli che possiedo, questo è entrato molto in fretta tra i preferiti.": [
    "Tra i miei paia, questo è diventato preferito in tempi record.",
    "Nella mia collezione, è entrato rapidamente nella rosa dei preferiti.",
    "Tra quelli che ho, è salito velocemente in cima alle preferenze.",
    "Tra i miei occhiali, è diventato un favorito in pochissimo tempo.",
    "Nella mia rotazione, è entrato tra i preferiti quasi subito.",
    "Tra i miei paia, è diventato un prediletto in modo molto rapido.",
    "Nella mia collezione, ha conquistato i vertici in poco tempo.",
    "Tra quelli che possiedo, è salito rapidamente nella classifica personale.",
    "Tra i miei occhiali, è entrato tra i top quasi immediatamente.",
    "Nella mia selezione, è diventato un favorito in brevissimo tempo.",
    "Tra quelli che ho, ha scalato le preferenze alla velocità della luce.",
    "Tra i miei paia, è diventato uno dei preferiti in tempi rapidissimi.",
    "Nella mia collezione è entrato subito tra i favoriti.",
    "Tra quelli che possiedo, ha guadagnato la posizione di favorito molto in fretta.",
    "Tra i miei, è diventato tra i prediletti in un battito d'occhio.",
    "Nella mia rotazione è salito in alto molto velocemente.",
    "Tra quelli che ho, è diventato subito uno dei preferiti.",
    "Tra i miei paia è entrato nella cerchia dei favoriti quasi subito.",
    "Nella mia selezione ha conquistato un posto tra i preferiti in fretta.",
    "Tra quelli che possiedo è diventato un punto di riferimento molto rapidamente.",
],

"Per me resta sospeso tra idea riuscita e uso intermittente.": [
    "Per me oscilla tra un'idea riuscita e un uso non costante.",
    "Per me è a metà tra una buona idea e un uso saltuario.",
    "Per me resta in bilico tra una concezione riuscita e un uso discontinuo.",
    "Per me sta tra un progetto valido e un utilizzuo irregolare.",
    "Per me è sospeso tra una buona esecuzione e un uso a singhiozzo.",
    "Per me oscilla tra un design riuscito e un utilizzo non regolare.",
    "Per me resta a metà: l'idea è buona, l'uso non è costante.",
    "Per me è in bilico tra una riuscita progettuale e un uso saltuario.",
    "Per me sta tra una concezione vincente e un utilizzo discontinuo.",
    "Per me è sospeso tra una buona realizzazione e un uso irregolare.",
    "Per me oscilla tra un'idea centrata e un uso non continuativo.",
    "Per me resta tra un progetto riuscito e un utilizzo a fasi alterne.",
    "Per me è a metà strada tra una buona esecuzione e un uso discontinuo.",
    "Per me sta in bilico tra un design valido e un uso non frequente.",
    "Per me oscilla tra una realizzazione riuscita e un uso incostante.",
    "Per me resta tra un'idea vincente e un utilizzo non assiduo.",
    "Per me è sospeso tra una buona idea e un uso che non diventa abitudine.",
    "Per me sta tra una concezione riuscita e un uso che non si stabilizza.",
    "Per me oscilla tra un progetto valido e un utilizzo non regolare.",
    "Per me è in bilico: l'idea è buona ma l'uso resta intermittente.",
],

"Non li boccio, ma richiedono il volto e lo stile giusto.": [
    "Non li scarto, ma esigono il viso e lo stile adatto.",
    "Non li rifiuto, ma chiedono i lineamenti e il look giusto.",
    "Non li bocciò, ma necessitano del volto e dello stile giusto.",
    "Non li escludo, ma richiedono la faccia e il look adatto.",
    "Non li scarto, ma vanno bene solo con il viso e lo stile giusto.",
    "Non li rifiuto, ma domandano il volto e l'attitudine giusta.",
    "Non li escludo, ma necessitano dei lineamenti e del look adatto.",
    "Non li scarto, ma chiedono il volto giusto e lo stile giusto.",
    "Non li rifiuto, ma esigono la struttura del viso e il look adatto.",
    "Non li bocciò, ma hanno bisogno del volto e dello stile giusto.",
    "Non li escludo, ma richiedono i tratti e il look adeguato.",
    "Non li scarto, ma necessitano della faccia e dello stile giusto.",
    "Non li rifiuto, ma chiedono il volto adatto e l'attitudine giusta.",
    "Non li escludo, ma esigono lineamenti e stile compatibili.",
    "Non li scarto, ma vanno bene solo con certi lineamenti e un certo stile.",
    "Non li rifiuto, ma richiedono il tipo di viso e di stile giusto.",
    "Non li bocciò, ma chiedono lineamenti e look adeguati.",
    "Non li escludo, ma necessitano del viso e dell'attitudine giusta.",
    "Non li scarto, ma esigono il volto e il contesto stilistico giusto.",
    "Non li rifiuto, ma hanno bisogno del viso e dello stile adatto.",
],

"Sono validi, solo meno immediati di quanto sperassi.": [
    "Sono validi, ma meno immediati di quanto immaginassi.",
    "Sono buoni, solo meno istantanei di quanto mi aspettassi.",
    "Sono validi, ma richiedono più tempo di quanto sperassi.",
    "Sono buoni, solo meno rapidi nel convincere di quanto credessi.",
    "Sono validi, ma meno immediati nella resa di quanto immaginavo.",
    "Sono buoni, solo più lenti nel convincere di quanto sperassi.",
    "Sono validi, ma la resa è meno immediata del previsto.",
    "Sono buoni, solo meno istintivi di quanto mi aspettassi.",
    "Sono validi, ma la gratificazione è meno rapida di quanto sperassi.",
    "Sono buoni, solo più graduali nel convincere di quanto credessi.",
    "Sono validi, ma meno instantanei di quanto immaginassi.",
    "Sono buoni, solo meno diretti di quanto mi aspettavo.",
    "Sono validi, ma richiedono pazienza più di quanto sperassi.",
    "Sono buoni, solo meno rapidi nell'impatto di quanto credessi.",
    "Sono validi, ma la loro bontà emerge meno velocemente del previsto.",
    "Sono buoni, solo meno fulminei di quanto speravo.",
    "Sono validi, ma l'impatto è meno rapido di quanto immaginassi.",
    "Sono buoni, solo meno immediati nella resa di quanto credessi.",
    "Sono validi, ma la conquista è più lenta di quanto sperassi.",
    "Sono buoni, solo più lenti nel rivelarsi di quanto mi aspettassi.",
],

"E infatti la differenza, come spesso accade, la fa il modo in cui si appoggia sul viso.": [
    "E in effetti, come spesso succede, la differenza la fa come si posa sul viso.",
    "E di fatto, come accade spesso, ciò che conta è come si posiziona sul volto.",
    "E in realtà, come capita spesso, è il modo in cui si appoggia al viso a fare la differenza.",
    "E infatti, come è tipico, la differenza sta in come si posano sul viso.",
    "E di fatto, come succede spesso, è la resa sul viso a fare la differenza.",
    "E in effetti, come al solito, la differenza vera la fa la calzata sul viso.",
    "E di fatto, come quasi sempre, ciò che conta è come siedono sul volto.",
    "E in realtà, come capita spesso, è il rapporto col viso a fare la differenza.",
    "E infatti, come spesso avviene, la differenza è data da come si posano sul volto.",
    "E di fatto, come succede quasi sempre, è la resa sul viso a decidere tutto.",
    "E in effetti, come è normale, la differenza la fa il modo in cui vivono sul viso.",
    "E di fatto, come spesso capita, il modo in cui si appoggiano al viso cambia tutto.",
    "E in realtà, come spesso succede, è la calzata sul viso a essere determinante.",
    "E infatti, come al solito, il modo in cui stanno sul viso fa tutta la differenza.",
    "E di fatto, come è tipico, la differenza è nella resa sul volto.",
    "E in effetti, come capita di frequente, è il rapporto con il viso a decidere.",
    "E di fatto, come quasi sempre, è il modo in cui si posano a fare la differenza.",
    "E in realtà, come spesso capita, è la resa sulla faccia a cambiare tutto.",
    "E infatti, come spesso accade, ciò che conta è come si appoggiano al volto.",
    "E di fatto, come succede di continuo, la differenza la fa la posizione sul viso.",
],

"Sul lungo periodo la fascinazione iniziale non basta.": [
    "Col tempo la fascinazione iniziale non è sufficiente.",
    "A lungo andare il fascino iniziale da solo non basta.",
    "Nel lungo periodo l'entusiasmo iniziale non regge.",
    "Col passare del tempo la fascinazione di partenza non è sufficiente.",
    "A distanza di tempo il fascino iniziale non basta più.",
    "Nel lungo termine l'attrattiva iniziale non è abbastanza.",
    "Col tempo il fascino della prima impressione si esaurisce.",
    "A lungo andare la fascinazione di partenza non sostiene.",
    "Nel lungo periodo il fascino iniziale perde forza.",
    "Col passare del tempo l'entusiasmo iniziale non basta.",
    "A distanza di tempo la fascinazione iniziale non è sufficiente.",
    "Nel lungo termine il fascino di partenza non regge da solo.",
    "Col tempo l'attrattiva iniziale non è abbastanza.",
    "A lungo andare il fascino del primo impatto non basta.",
    "Nel lungo periodo l'entusiasmo iniziale da solo non sostiene.",
    "Col passare del tempo il fascino iniziale non è più sufficiente.",
    "A distanza di settimane la fascinazione iniziale si affievolisce.",
    "Nel lungo termine l'attrazione iniziale non basta a mantenere.",
    "Col tempo il fascino iniziale non è più abbastanza.",
    "A lungo andare il primo entusiasmo non sostiene il giudizio.",
],

"Non compro per collezione, compro per uso reale.": [
    "Non compro per collezionare, compro per usare davvero.",
    "Non acquisto per accumulo, acquisto per impiego reale.",
    "Non compro per fare collezione, compro per portarli.",
    "Non acquisto per accumulare, acquisto per l'uso quotidiano.",
    "Non compro per il cassetto, compro per l'uso reale.",
    "Non acquisto per la vetrina, acquisto per l'uso effettivo.",
    "Non compro per aggiungere alla collezione, compro per usarli.",
    "Non acquisto per accumulo, ma per utilizzo reale.",
    "Non compro per il piacere della collezione, ma per l'uso.",
    "Non acquisto per la quantità, ma per la praticità d'uso.",
    "Non compro per accumulare, compro per indossare.",
    "Non acquisto per collezionare, acquisto per vivere.",
    "Non compro per il numero, compro per il valore d'uso.",
    "Non acquisto per la collezione, ma per l'uso concreto.",
    "Non compro per avere più paia, compro per usarli davvero.",
    "Non acquisto per accumulo, ma per l'uso reale e quotidiano.",
    "Non compro per il gusto di avere, compro per il gusto di usare.",
    "Non acquisto mai per collezione: ogni paio deve guadagnarsi il suo posto.",
    "Non compro per accumulare: ogni paio deve essere usato.",
    "Non acquisto per il piacere di possedere, ma per quello di portare.",
],

"Non mi crea rifiuto, ma neanche quella serenità che mi fa pensare di aver trovato il paio giusto.": [
    "Non mi respinge, ma non mi dà nemmeno la serenità del paio trovato.",
    "Non lo rifiuto, ma non provo nemmeno la tranquillità del paio giusto.",
    "Non mi crea fastidio, ma nemmeno la pace del paio ideale.",
    "Non mi respinge, ma non mi dà quella sicurezza del paio perfetto.",
    "Non lo rifiuto, ma non sento nemmeno la serenità del paio giusto.",
    "Non mi crea disagio, ma nemmeno la certezza del paio ideale.",
    "Non mi respinge, ma non provo la tranquillità del paio trovato.",
    "Non lo rifiuto, ma non mi dà la serenità di aver trovato il paio giusto.",
    "Non mi crea antipatia, ma non mi dà la pace della scelta giusta.",
    "Non mi respinge, ma non mi trasmette la sicurezza del paio ideale.",
    "Non lo rifiuto, ma non sento la serenità della scelta giusta.",
    "Non mi crea fastidio, ma non mi dà la certezza del paio giusto.",
    "Non mi respinge, ma non provo quella pace del paio ideale.",
    "Non lo rifiuto, ma non mi trasmette la tranquillità della scelta giusta.",
    "Non mi crea antipatia, ma non mi dà la serenità del paio trovato.",
    "Non mi respinge, ma non sento la sicurezza di aver trovato il paio giusto.",
    "Non lo rifiuto, ma non provo la certezza della scelta ideale.",
    "Non mi crea disagio, ma non mi dà la pace del paio perfetto.",
    "Non mi respinge, ma non mi dà la tranquillità del paio ideale.",
    "Non lo rifiuto, ma non sento la serenità della scelta perfetta.",
],

"Qui non è questione di moda, è proprio questione di faccia e struttura.": [
    "Qui non si parla di moda, si parla di lineamenti e struttura.",
    "Non è una questione di tendenza: è una questione di viso e proporzioni.",
    "Qui la moda c'entra poco: contano la faccia e la struttura.",
    "Non si tratta di moda, ma di compatibilità con il volto.",
    "Qui il tema non è la moda, ma il rapporto con il viso.",
    "Non è questione di tendenze: è questione di lineamenti.",
    "Qui la moda non è il punto: contano faccia e struttura.",
    "Non si parla di stile ma di compatibilità con i lineamenti.",
    "Qui il discorso non è di moda, è di viso e proporzioni.",
    "Non è una questione di fashion: è una questione di faccia.",
    "Qui la moda non conta: conta come stanno sul viso.",
    "Non si tratta di tendenze, ma di rapporto con la struttura del volto.",
    "Qui il punto non è la moda: è il rapporto con i lineamenti.",
    "Non è questione di stile: è questione di faccia e proporzioni.",
    "Qui la moda è secondaria: conta la resa sul viso.",
    "Non si parla di trend, ma di compatibilità facciale.",
    "Qui il tema è il viso, non la moda.",
    "Non è questione di tendenza: è questione di lineamenti e struttura.",
    "Qui la moda non c'entra: è una questione puramente di viso.",
    "Non si tratta di stile: si tratta di faccia e struttura.",
],

"e da lì in poi non recupera più. Per altri magari sì, per me no.": [
    "e da quel punto non si riprende. Forse per altri sì, per me no.",
    "e da lì non c'è più recupero. Per altri potrebbe essere diverso.",
    "e da quel momento non si riprende più. Per qualcun altro magari sì.",
    "e da quel punto il giudizio non risale. Per altri forse sì, per me no.",
    "e da lì non si rialza. Per altri potrebbe funzionare, per me no.",
    "e da quel punto non torna più su. Per altri forse, per me no.",
    "e da lì in poi la questione è chiusa. Per altri magari è diverso.",
    "e da quel momento la cosa non migliora. Per altri potrebbe, per me no.",
    "e da lì non c'è più rimedio. Per altri forse sì, per me no.",
    "e da quel punto il bilancio non migliora. Per altri magari è diverso.",
    "e da lì non si riprende più. Per altri magari funziona, per me no.",
    "e da quel momento il giudizio è definito. Per altri potrebbe essere diverso.",
    "e da lì non c'è modo di recuperare. Per altri forse, per me no.",
    "e da quel punto non risale. Per qualcuno forse sì, per me no.",
    "e da lì in poi la cosa si chiude. Per altri magari è diverso.",
    "e da quel momento non c'è più margine. Per altri potrebbe esserci.",
    "e da lì non si rimonta. Per altri forse funziona, per me no.",
    "e da quel punto il conto è chiuso. Per altri magari è aperto.",
    "e da lì il bilancio non migliora più. Per altri forse sì, per me no.",
    "e da quel momento il giudizio resta negativo. Per altri magari no.",
],

"Mi ritrovo a correggerli o pensarci più di quanto vorrei.": [
    "Finisco per aggiustarli o pensarci più del dovuto.",
    "Mi trovo a sistemarli o a pensarci più di quanto servirebbe.",
    "Mi ritrovo a regolarli o pensarci più del necessario.",
    "Finisco per correggerli o a rifletterci sopra più del dovuto.",
    "Mi trovo a sistemarli o a pensarci troppo spesso.",
    "Mi ritrovo a aggiustarli o a rifletterci più di quanto vorrei.",
    "Finisco per regolarli o pensarci più di quanto desidererei.",
    "Mi trovo a correggerli o a occuparmene più del previsto.",
    "Mi ritrovo a sistemarli o pensarci più del necessario.",
    "Finisco per aggiustarli o pensarci troppo.",
    "Mi trovo a regolarli o a pensarci più del dovuto.",
    "Mi ritrovo a correggerli o a preoccuparmene più di quanto vorrei.",
    "Finisco per sistemarli o rifletterci più del necessario.",
    "Mi trovo a aggiustarli o a pensarci più di quanto servirebbe.",
    "Mi ritrovo a regolarli o a rifletterci troppo.",
    "Finisco per correggerli o a pensarci più di quanto dovrei.",
    "Mi trovo a sistemarli o a preoccuparmene più del dovuto.",
    "Mi ritrovo a regolarli o a occuparmene più del previsto.",
    "Finisco per aggiustarli o pensarci più di quanto servirebbe.",
    "Mi trovo a correggerli o rifletterci più del necessario.",
],

}
