#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Dizionario PATTERN -> ALTERNATIVE (Parte 16: residui 11x-10x + frammenti template)"""

FINAL_LOW = {

"Ho gusti abbastanza selettivi e faccio pochi acquisti impulsivi.": [
    "Ho gusti precisi e raramente compro d'impulso.",
    "Sono selettivo nei gusti e compro poco d'impulso.",
    "Ho gusti esigenti e non faccio acquisti impulsivi.",
    "Sono piuttosto selettivo e ogni acquisto è ragionato.",
    "Ho gusti precisi e gli acquisti impulsivi non fanno per me.",
    "Sono molto selettivo e ogni scelta è ponderata.",
    "Ho gusti definiti e compro solo dopo riflessione.",
    "Sono esigente nei gusti e ogni acquisto è una decisione presa con calma.",
    "Ho gusti particolari e non compro mai d'impulso.",
    "Sono selettivo per natura e acquisto solo ciò che mi convince davvero.",
    "Ho gusti ben definiti e gli acquisti impulsivi non mi appartengono.",
    "Sono piuttosto esigente e ogni acquisto è frutto di riflessione.",
    "Ho gusti precisi e non mi lascio tentare dagli acquisti impulsivi.",
    "Sono molto selettivo negli acquisti e raramente cedo all'impulso.",
    "Ho gusti chiari e ogni acquisto è una scelta ragionata.",
    "Sono esigente e non compro nulla che non mi abbia davvero convinto.",
    "Ho gusti precisi e non acquisto mai senza pensarci bene.",
    "Sono selettivo e ogni acquisto deve superare il mio scrutinio personale.",
],

"Alla fine li ho rimessi nella custodia e lì sono rimasti.": [
    "Alla fine li ho riposti nella custodia e non li ho più ripresi.",
    "Li ho rimessi nella custodia e lì giacciono da allora.",
    "Li ho riposti e non li ho più tirati fuori.",
    "Alla fine sono tornati nella custodia e non ne sono più usciti.",
    "Li ho messi via e da allora non li ho più cercati.",
    "Alla fine li ho riposti e lì sono rimasti dimenticati.",
    "Sono finiti nella custodia e non ne sono più usciti.",
    "Li ho messi nella custodia e da allora non li ho più toccati.",
    "Alla fine sono tornati nel cassetto e lì sono rimasti.",
    "Li ho riposti e non ho più sentito il bisogno di riprenderli.",
    "Alla fine li ho messi via e il cassetto si è chiuso su di loro.",
    "Sono finiti nella custodia e da allora raccolgono polvere.",
    "Li ho riposti e non li ho più considerati.",
    "Alla fine sono tornati nella custodia senza fare ritorno sul naso.",
    "Li ho messi nella custodia e il capitolo si è chiuso così.",
    "Alla fine sono finiti nel dimenticatoio della custodia.",
    "Li ho riposti e non ho più avuto la voglia di riprenderli.",
    "Sono tornati nella custodia a tempo indeterminato.",
],

"Non sono riuscito a trovare un solo contesto in cui mi sembrassero davvero miei.": [
    "Non ho trovato un solo contesto in cui mi sentissi davvero a mio agio con loro.",
    "Non sono riuscito a trovargli un posto nel mio quotidiano.",
    "Non ho trovato una sola situazione in cui mi convincessero davvero.",
    "Non sono riuscito a trovare un'occasione in cui mi sentissi miei.",
    "Non ho trovato un solo momento in cui mi sembrasse giusto indossarli.",
    "Non sono riuscito a inserirli in nessun contesto della mia vita.",
    "Non ho trovato un singolo momento in cui mi sembrasse il paio giusto.",
    "Non sono riuscito a farli miei in nessun contesto.",
    "Non ho trovato un solo contesto in cui indossarli con naturalezza.",
    "Non sono riuscito a sentirli miei in nessuna situazione.",
    "Non ho trovato un momento in cui mi sembrasse giusto portarli.",
    "Non sono riuscito a farli parte della mia vita in nessun contesto.",
    "Non ho trovato un'occasione in cui mi sentissi naturale con loro.",
    "Non sono riuscito a integrarli in nessun aspetto del mio quotidiano.",
    "Non ho trovato un solo contesto adatto a questo paio.",
    "Non sono riuscito a trovargli una collocazione nel mio uso di tutti i giorni.",
    "Non ho trovato un momento in cui mi sentissi davvero a posto con loro.",
    "Non sono riuscito a farli funzionare in nessun contesto reale.",
],

"Non c'è stata intesa, e a un certo punto è meglio dirlo senza girarci attorno.": [
    "Non c'è stata sintonia, e tanto vale dirlo schiettamente.",
    "Non c'è stato feeling, e a un certo punto bisogna ammetterlo.",
    "Non c'è stata alchimia, e tanto vale essere onesti.",
    "L'intesa non è mai scattata, inutile girarci intorno.",
    "Non c'è stato il click, e a volte è meglio ammetterlo chiaramente.",
    "La sintonia non è mai arrivata, e tanto vale dirlo apertamente.",
    "Non c'è stata connessione, e a un certo punto bisogna prenderne atto.",
    "Il feeling non è mai nato, e tanto vale essere diretti.",
    "Non c'è stata intesa, e credo sia giusto dirlo senza giri di parole.",
    "L'alchimia non è mai scattata, e a un certo punto è meglio essere franchi.",
    "Non c'è stata sintonia, inutile continuare a cercare scuse.",
    "Il click non c'è stato, e tanto vale ammetterlo apertamente.",
    "Non c'è stata connessione, e a un certo punto è meglio dirlo con onestà.",
    "L'intesa non è mai arrivata, e credo sia giusto essere chiari.",
    "Non c'è stato feeling, e tanto vale dirlo senza troppi giri.",
    "La sintonia non è mai scattata, meglio dirlo chiaramente.",
    "Non c'è stata alchimia, e a volte bisogna solo prenderne atto.",
    "Il rapporto non è mai decollato, tanto vale dirlo senza troppe cerimonie.",
],

"Ci vedo valore, semplicemente non sempre per il mio modo di vestirmi o di usarlo.": [
    "Ne riconosco il valore, semplicemente non sempre adatto al mio stile.",
    "Ci vedo del merito, ma non sempre si adatta al mio modo di vestire.",
    "Ne apprezzo il valore, ma non sempre per il mio uso quotidiano.",
    "Ci riconosco del valore, anche se non sempre funziona col mio stile.",
    "Ne vedo i pregi, ma non sempre si adattano al mio guardaroba.",
    "Ci trovo del merito, anche se non sempre per il mio modo di portare.",
    "Ne apprezzo le qualità, ma non sempre per il mio stile personale.",
    "Ci riconosco del valore obiettivo, anche se col mio stile non sempre funziona.",
    "Ne vedo il merito, ma non sempre si integra col mio modo di vestire.",
    "Ci trovo delle qualità, anche se non sempre per il mio uso personale.",
    "Ne riconosco il valore, ma non sempre nella mia quotidianità.",
    "Ci vedo del buono, anche se col mio stile non sempre si sposa.",
    "Ne apprezzo il valore intrinseco, ma non sempre per il mio uso.",
    "Ci riconosco delle qualità, anche se non sempre per come mi vesto.",
    "Ne vedo il valore, ma non sempre per il mio contesto d'uso.",
    "Ci trovo del valore, anche se non si adatta sempre al mio stile.",
    "Ne riconosco il pregio, anche se non sempre per il mio modo di vivere.",
    "Ci vedo delle qualità, anche se non sempre per il mio guardaroba.",
],

"Se devo continuamente adattarmi io al prodotto, qualcosa per me non torna.": [
    "Se devo adattarmi io al prodotto anziché il contrario, qualcosa non va.",
    "Se sono io a dovermi adattare continuamente, il prodotto non funziona.",
    "Se il prodotto richiede continui adattamenti da parte mia, non fa per me.",
    "Se devo continuamente aggiustarmi io, qualcosa nel prodotto non funziona.",
    "Se il prodotto chiede a me di adattarmi, il rapporto è sbagliato.",
    "Se devo fare continui compromessi io, il prodotto non è quello giusto.",
    "Se mi richiede di continuo adattamenti, il prodotto non è per me.",
    "Se sono io a dovermi modellare sul prodotto, qualcosa non torna.",
    "Se il prodotto pretende che mi adatti io, per me non funziona.",
    "Se devo continuamente adattarmi, il prodotto non ha centrato il bersaglio.",
    "Se sono io a dovermi aggiustare, il prodotto non è adatto.",
    "Se il prodotto chiede troppi compromessi, per me non va bene.",
    "Se mi richiede di adattarmi continuamente, il prodotto non è il mio.",
    "Se devo sempre aggiustarmi io al prodotto, qualcosa non quadra.",
    "Se il prodotto mi chiede continui adattamenti, non va nella direzione giusta.",
    "Se sono io a dovermi adattare sempre, il prodotto non è fatto per me.",
    "Se il prodotto esige che io mi adatti, per me il rapporto non funziona.",
    "Se mi chiede costantemente di adattarmi, il prodotto non è quello che cerco.",
],

"Sono il tipo di occhiale che se non combacia al cento per cento non perdona.": [
    "Sono il tipo di occhiale che non ammette mezze misure nella calzata.",
    "Sono quel tipo di occhiale che o funziona alla perfezione o non funziona.",
    "Sono il tipo di occhiale che dev'essere perfetto addosso o non va.",
    "Sono quel genere di occhiale che non perdona le imprecisioni.",
    "Sono il tipo di occhiale che richiede una calzata perfetta per funzionare.",
    "Sono quel tipo di occhiale dove la perfezione è l'unico risultato accettabile.",
    "Sono il tipo di occhiale che o calza alla perfezione o delude.",
    "Sono quel genere di occhiale che non concede margine d'errore.",
    "Sono il tipo di occhiale che non tollera la minima imprecisione.",
    "Sono quel tipo di occhiale che dev'essere perfetto o non funziona.",
    "Sono il tipo di occhiale che richiede una vestibilità impeccabile.",
    "Sono quel genere di occhiale che non ammette compromessi nella calzata.",
    "Sono il tipo di occhiale dove anche mezzo millimetro conta.",
    "Sono quel tipo di occhiale che deve combaciate perfettamente o non convince.",
    "Sono il tipo di occhiale che diventa impietoso se la calzata non è perfetta.",
    "Sono quel genere di occhiale dove tutto deve essere al millimetro.",
    "Sono il tipo di occhiale che non fa sconti sulla precisione della calzata.",
    "Sono quel tipo di occhiale che richiede il match perfetto col viso.",
],

"Li lascio volentieri a chi ha un viso o un gusto più compatibile del mio.": [
    "Li cedo volentieri a chi ha un viso o uno stile più adatto.",
    "Li lascio a chi ha lineamenti o gusti più compatibili.",
    "Li consiglio a chi ha un viso più adatto al loro design.",
    "Li cedo a chi ha una compatibilità migliore con questo tipo di stile.",
    "Li lascio volentieri a chi ha lineamenti più adatti.",
    "Li consiglio a chi ha un viso o un gusto che si sposa meglio.",
    "Li cedo a chi ha un volto più compatibile con questo tipo di occhiale.",
    "Li lascio a chi ha lo stile e i lineamenti giusti per loro.",
    "Li consiglio a chi trova nel proprio viso la giusta corrispondenza.",
    "Li cedo volentieri a chi ha un viso più adatto al loro carattere.",
    "Li lascio a chi ha una compatibilità naturale con questo stile.",
    "Li consiglio a chi ha lineamenti e gusti più affini.",
    "Li cedo a chi ha il viso e lo stile giusti per questo modello.",
    "Li lascio volentieri a chi trova in loro la corrispondenza giusta.",
    "Li consiglio a chi ha un volto e un guardaroba più compatibili.",
    "Li cedo a chi ha la fortuna di avere i lineamenti giusti.",
    "Li lascio a chi ha un viso e uno stile che dialogano meglio con loro.",
    "Li consiglio a chi ha il volto adatto a questo tipo di design.",
],

"È una relazione tiepida, non un rifiuto e neppure un colpo di fulmine.": [
    "È un rapporto tiepido, non un rifiuto né un amore a prima vista.",
    "È una relazione neutra, non un rifiuto ma neanche un entusiasmo.",
    "È un rapporto senza estremi: non li rifiuto, non li amo.",
    "È una relazione in zona grigia: non li scarto, non li abbraccio.",
    "È un rapporto tiepido: non li respingo, non li desidero.",
    "È una relazione senza picchi: né rifiuto né entusiasmo.",
    "È un rapporto di rispetto senza passione.",
    "È una relazione neutra: non c'è rifiuto, ma neanche amore.",
    "È un rapporto tiepido: non li scarto, non li cerco.",
    "È una relazione senza slanci: non li rifiuto, non li bramo.",
    "È un rapporto a temperatura ambiente: non freddo, non caldo.",
    "È una relazione di cortesia, senza rifiuto e senza passione.",
    "È un rapporto senza entusiasmo e senza antipatia.",
    "È una relazione in equilibrio tra indifferenza e rispetto.",
    "È un rapporto che non scalda e non raffredda.",
    "È una relazione educata, senza rifiuto e senza trasporto.",
    "È un rapporto di convivenza, non di passione.",
    "È una relazione tiepida, dove il rifiuto e l'entusiasmo latitano.",
],

"e il prodotto smette di essere solo immagine.": [
    "e il prodotto diventa più di una semplice immagine.",
    "e il prodotto va oltre la sola estetica.",
    "e il prodotto si rivela più di un bel disegno.",
    "e il prodotto supera la dimensione puramente estetica.",
    "e il prodotto smette di essere solo apparenza.",
    "e il prodotto diventa sostanza, non solo forma.",
    "e il prodotto acquista una dimensione concreta.",
    "e il prodotto va oltre il design.",
    "e il prodotto si fa reale, non solo bello.",
    "e il prodotto dimostra di avere sostanza.",
    "e il prodotto mostra di essere più che un bel packaging.",
    "e il prodotto diventa esperienza, non solo immagine.",
    "e il prodotto supera la dimensione visiva.",
    "e il prodotto si fa concreto.",
    "e il prodotto va oltre il colpo d'occhio.",
    "e il prodotto dimostra che c'è sostanza dietro la forma.",
    "e il prodotto si rivela più che decorazione.",
    "e il prodotto diventa qualcosa di vissuto.",
],

"e la differenza rispetto a un paio qualunque si nota.": [
    "e la differenza rispetto a un paio generico si avverte.",
    "e si nota la differenza rispetto a un paio qualsiasi.",
    "e si capisce che non è un paio come gli altri.",
    "e la differenza con i paia comuni si fa evidente.",
    "e si vede che non è un paio banale.",
    "e la distanza da un paio anonimo è chiara.",
    "e si percepisce la differenza rispetto ai paia generici.",
    "e la differenza con un paio ordinario si sente.",
    "e si nota che è un taglio sopra la media.",
    "e la distinzione rispetto a un paio qualunque è tangibile.",
    "e si capisce subito che non è un paio come tanti.",
    "e la differenza con l'ordinario è evidente.",
    "e si avverte la distanza da un paio qualsiasi.",
    "e la differenza rispetto a un paio comune è percepibile.",
    "e si nota che c'è un livello diverso.",
    "e la distinzione rispetto ai paia comuni è chiara.",
    "e si sente che è un paio che ha qualcosa in più.",
    "e la differenza con un paio standard è evidente.",
],

"Dal vivo hanno una misura che le foto non restituiscono bene.": [
    "Dal vivo hanno proporzioni che le foto non rendono.",
    "Di persona hanno una misura che nelle foto si perde.",
    "Dal vivo hanno dimensioni che le foto non catturano.",
    "Di persona hanno una resa che le immagini non comunicano.",
    "Dal vivo hanno una proporzione che le foto non trasmettono.",
    "Di persona hanno un equilibrio che le foto non mostrano.",
    "Dal vivo hanno una presenza che le foto non rendono giustizia.",
    "Di persona hanno dimensioni diverse da come appaiono in foto.",
    "Dal vivo hanno una resa che le immagini non colgono.",
    "Di persona hanno una misura che emerge solo indossandoli.",
    "Dal vivo hanno un impatto che le foto non restituiscono.",
    "Di persona hanno un equilibrio dimensionale che le foto nascondono.",
    "Dal vivo hanno una proporzione che non traspare dalle immagini.",
    "Di persona hanno una resa che supera l'impressione fotografica.",
    "Dal vivo hanno un impatto visivo diverso dalle foto.",
    "Di persona hanno proporzioni che le immagini non rendono.",
    "Dal vivo hanno una presenza fisica che le foto non catturano.",
    "Di persona hanno dimensioni che le foto non trasmettono bene.",
],

"bisogna avere il volto giusto o non c'è mediazione.": [
    "serve il volto giusto, altrimenti non c'è compromesso.",
    "bisogna avere i lineamenti adatti o non funziona.",
    "serve il viso giusto o non c'è scampo.",
    "bisogna avere la struttura facciale adatta o non c'è via di mezzo.",
    "serve il volto compatibile oppure non c'è nulla da fare.",
    "bisogna avere i lineamenti giusti o non c'è alternativa.",
    "serve il viso adatto altrimenti non perdonano.",
    "bisogna avere il volto giusto oppure è un no secco.",
    "serve la struttura facciale giusta o non c'è margine.",
    "bisogna avere i lineamenti compatibili o il risultato delude.",
    "serve il volto adatto, senza concessioni.",
    "bisogna avere il viso giusto o non c'è spazio per compromessi.",
    "serve la corrispondenza giusta col viso o non si salva.",
    "bisogna avere i lineamenti giusti o non c'è speranza.",
    "serve il volto compatibile, punto e basta.",
    "bisogna avere la struttura giusta del viso altrimenti non funziona.",
    "serve il viso giusto, non ammettono mezze misure.",
    "bisogna avere i lineamenti adatti o non c'è mediazione possibile.",
],

}
