#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Dizionario PATTERN -> ALTERNATIVE (Parte 11: pattern residui 23x-20x + frasi attacco/chiusura)"""

RESIDUAL_LOW = {

"È il genere di acquisto che mi fa venire voglia di uscire solo per indossarlo.": [
    "È il tipo di paio che mi fa venire voglia di uscire apposta per portarlo.",
    "Mi fa venir voglia di inventarmi un'occasione pur di indossarlo.",
    "È un acquisto che mi spinge a trovarmi un motivo per uscire.",
    "Mi fa venire voglia di uscire di casa solo per il piacere di portarlo.",
    "È il genere di paio che ti fa cercare un pretesto per uscire.",
    "Mi dà quel tipo di entusiasmo che ti fa inventare occasioni pur di indossarlo.",
    "È un acquisto che mi spinge fuori di casa per il solo gusto di portarlo.",
    "Mi fa venire voglia di crearmi un impegno pur di indossarlo.",
    "È il tipo di acquisto che rende l'uscita un'occasione per indossare.",
    "Mi fa venir voglia di uscire apposta, solo per portarli.",
    "È il genere di paio che trasforma ogni uscita in un'occasione di stile.",
    "Mi spinge a uscire di casa solo per il piacere di averli addosso.",
    "È un paio che ti fa cercare scuse per uscire.",
    "Mi fa venire voglia di crearmi occasioni apposta per indossarli.",
    "È il tipo di acquisto che rende ogni uscita un piacere extra.",
    "Mi fa venire la voglia di uscire solo per il gusto di portarli addosso.",
    "È un paio che ti fa inventare commissioni pur di indossarli.",
    "Mi fa venir voglia di uscire, anche solo per sentirli sul viso.",
    "È il genere di acquisto che trasforma una passeggiata in uno sfoggio.",
    "Mi spinge a uscire trovandomi un pretesto, solo per portarli.",
    "È il tipo di paio che mi fa amare l'uscita di casa.",
    "Mi fa venire voglia di uscire anche senza motivo, solo per indossarli.",
    "È un acquisto che aggiunge un motivo in più per uscire.",
],

"Lo rimetto volentieri e questo per me vale più di mille schede tecniche.": [
    "Lo indosso di nuovo con piacere, e per me è più significativo di qualsiasi specifica tecnica.",
    "Lo rimetto con gioia, e per me conta più di qualsiasi dato tecnico.",
    "Il fatto che lo rimetta volentieri è per me più importante di ogni scheda tecnica.",
    "Lo indosso di nuovo con gusto, e quello vale più di qualsiasi numero.",
    "Lo rimetto con piacere, e per me pesa più di mille caratteristiche tecniche.",
    "La voglia di rimetterlo conta per me più di ogni specifica.",
    "Lo indosso di nuovo con entusiasmo, e questo è il dato che conta.",
    "Lo rimetto con soddisfazione, e per me è il vero indicatore di qualità.",
    "Il piacere nel rimetterlo è per me più eloquente di qualsiasi scheda.",
    "Lo indosso di nuovo volentieri, ed è il giudizio più onesto che posso dare.",
    "Lo rimetto con gusto, e per me è il parametro più affidabile.",
    "La gioia nel rimetterlo è il mio metro di giudizio più sincero.",
    "Lo indosso di nuovo con lo stesso piacere, e quello conta più di tutto.",
    "Lo rimetto con la stessa voglia della prima volta, e per me è il voto vero.",
    "Il piacere nel rimetterlo è per me il criterio che supera ogni dato.",
    "Lo indosso di nuovo con entusiasmo, ed è il segnale più importante.",
    "Lo rimetto volentieri ogni volta, e per me è il giudizio definitivo.",
    "Il desiderio di rimetterlo è per me il criterio più solido che esista.",
    "Lo indosso con piacere rinnovato, e questo per me è tutto.",
    "Lo rimetto con lo stesso entusiasmo, il che per me vale più di ogni analisi.",
    "Il fatto che lo rimetta con gioia è per me più indicativo di ogni specifica.",
    "Lo indosso di nuovo con voglia, e per me è il dato più significativo.",
    "Lo rimetto con soddisfazione rinnovata, il che per me pesa più di tutto.",
],

"Mi hanno dato l'impressione di un prodotto con un punto di vista.": [
    "Mi hanno dato l'idea di un prodotto che ha una sua visione.",
    "Mi hanno trasmesso la sensazione di un prodotto con una direzione chiara.",
    "Mi hanno dato l'impressione di un paio con una filosofia precisa.",
    "Mi hanno comunicato l'idea di un prodotto con un'identità propria.",
    "Mi hanno dato la sensazione di un paio pensato con un punto di vista.",
    "Mi hanno trasmesso l'immagine di un prodotto con una voce specifica.",
    "Mi hanno comunicato l'impressione di un paio con una visione chiara.",
    "Mi hanno dato l'idea di un prodotto con personalità e direzione.",
    "Mi hanno trasmesso la sensazione di un paio con un suo credo estetico.",
    "Mi hanno dato l'impressione di un prodotto con un'intenzione precisa.",
    "Mi hanno comunicato l'idea di un paio con un messaggio stilistico.",
    "Mi hanno dato la sensazione di un prodotto con una proposta chiara.",
    "Mi hanno trasmesso l'idea di un paio con un'anima definita.",
    "Mi hanno comunicato la sensazione di un prodotto con un disegno intenzionale.",
    "Mi hanno dato l'idea di un paio con un pensiero dietro.",
    "Mi hanno trasmesso l'impressione di un prodotto con una posizione estetica.",
    "Mi hanno comunicato l'immagine di un paio con un punto di vista preciso.",
    "Mi hanno dato la sensazione di un prodotto che sa cosa vuole essere.",
    "Mi hanno trasmesso l'idea di un paio con una sua poetica.",
    "Mi hanno comunicato l'impressione di un prodotto con un'identità.",
    "Mi hanno dato l'idea di un paio con una narrazione propria.",
    "Mi hanno trasmesso la sensazione di un prodotto con una sua tesi.",
    "Mi hanno dato l'impressione di un paio che dice qualcosa di suo.",
],

"Non lo boccio, ma non è il paio che cerco istintivamente.": [
    "Non lo bocciò, ma non è il paio che cerco per istinto.",
    "Non lo rifiuto, ma non è quello che cercherei spontaneamente.",
    "Non lo scarto, ma non è il paio verso cui mi orienterei per primo.",
    "Non lo bocciò, ma non è la mia prima scelta istintiva.",
    "Non lo rifiuto, ma non è il paio che cerco d'istinto.",
    "Non lo scarto, ma non è quello che il mio istinto mi suggerisce.",
    "Non lo rifiuto, ma non è il modello che cerco per primo.",
    "Non lo bocciò, ma non è il paio che sceglierei a occhi chiusi.",
    "Non lo scarto, ma non è quello che il mio gusto cerca automaticamente.",
    "Non lo rifiuto, ma non è il modello verso cui graviterei naturalmente.",
    "Non lo bocciò, ma non è il tipo di paio che cerco spontaneamente.",
    "Non lo scarto, ma non è quello a cui il mio istinto mi porta.",
    "Non lo rifiuto, ma non è il paio che sceglierei di getto.",
    "Non lo bocciò, ma non è il modello che mi verrebbe da cercare.",
    "Non lo scarto, ma non è il paio che mi attrae istintivamente.",
    "Non lo rifiuto, ma non è il modello che cerco per natura.",
    "Non lo bocciò, ma non è il tipo che il mio gusto cerca da solo.",
    "Non lo scarto, ma non è il paio che sceglierei senza pensarci.",
    "Non lo rifiuto, ma non è il modello verso cui vado d'istinto.",
    "Non lo bocciò, ma non è quello che cercherei per primo.",
    "Non lo scarto, ma non è il paio che mi viene spontaneo cercare.",
    "Non lo rifiuto, ma non è un modello che il mio gusto cerca naturalmente.",
    "Non lo bocciò, ma non è il paio che sceglierei per istinto di gusto.",
],

"E lo dico da persona che di solito cambia idea solo a fatica.": [
    "E lo dice uno che di solito cambia opinione con molta difficoltà.",
    "E parlo come uno che raramente cambia idea.",
    "E lo dico da uno che non cambia opinione facilmente.",
    "E parlo da persona solitamente testarda nelle proprie opinioni.",
    "E lo afferma uno che difficilmente rivede i propri giudizi.",
    "E lo dico come persona che di solito resta salda nelle proprie idee.",
    "E parlo da uno che non si smuove facilmente dalle proprie convinzioni.",
    "E lo dico da persona che di solito non si lascia convincere facilmente.",
    "E parlo come uno che tiene salde le proprie opinioni.",
    "E lo afferma una persona che di solito non rivede le proprie posizioni.",
    "E lo dico da uno che raramente si ricrede.",
    "E parlo da persona generalmente ferma nelle proprie convinzioni.",
    "E lo dico come uno che di solito resta della stessa idea.",
    "E parlo da uno che non cambia parere senza motivo.",
    "E lo afferma una persona che di solito è coerente nei propri giudizi.",
    "E lo dico da uno che di solito non si smuove dalle proprie posizioni.",
    "E parlo come una persona che raramente si ricrede.",
    "E lo dico da uno che di norma non cambia opinione.",
    "E parlo da uno che ha le proprie certezze e le tiene salde.",
    "E lo afferma una persona generalmente costante nelle proprie idee.",
    "E lo dico da uno che non è facile da convincere.",
    "E parlo come uno che di solito mantiene i propri giudizi.",
    "E lo dico da persona che di norma non rivede facilmente le proprie opinioni.",
],

"Sono uno di quei paia che continuano a crescermi addosso.": [
    "Sono un paio che continua a crescere nell'apprezzamento col tempo.",
    "È un paio che ogni giorno mi piace un po' di più.",
    "Sono un paio la cui bellezza si rivela gradualmente.",
    "È un modello che cresce col tempo anziché stancare.",
    "Sono un paio che guadagna punti ad ogni utilizzo.",
    "È un modello in costante crescita nel mio apprezzamento.",
    "Sono un paio che migliora con la frequentazione.",
    "È un modello che ogni volta mi sorprende in meglio.",
    "Sono un paio la cui qualità emerge col tempo.",
    "È un modello che cresce nell'uso quotidiano.",
    "Sono un paio che si rivela sempre più bello col passare dei giorni.",
    "È un modello in continua ascesa nel mio giudizio.",
    "Sono un paio che non smette di crescere.",
    "È un modello che col tempo acquista sempre più valore ai miei occhi.",
    "Sono un paio la cui bellezza si scopre poco alla volta.",
    "È un modello che matura nel mio apprezzamento col tempo.",
    "Sono un paio che continua a sorprendermi positivamente.",
    "È un modello il cui valore cresce con l'uso.",
    "Sono un paio che scopro di apprezzare sempre di più.",
    "È un modello a lenta combustione, sempre più bello col tempo.",
    "Sono un paio il cui fascino si svela ad ogni utilizzo.",
    "È un modello la cui qualità emerge a ogni contatto.",
    "Sono un paio in costante crescita nella mia considerazione.",
],

"Li ho messi per un pranzo lungo all'aperto.": [
    "Li ho indossati per un pranzo all'aperto che si è prolungato.",
    "Li ho portati durante un lungo pranzo in terrazza.",
    "Li ho provati durante un pranzo all'aperto.",
    "Li ho indossati in occasione di un pranzo informale all'esterno.",
    "Li ho portati per un pranzo che si è trasformato in un pomeriggio all'aperto.",
    "Li ho usati per un pranzo rilassato fuori.",
    "Li ho indossati durante un pranzo conviviale all'aperto.",
    "Li ho portati per un pranzo che è durato tutto il pomeriggio.",
    "Li ho messi per un pranzo nel dehors.",
    "Li ho indossati per una lunga pausa pranzo al sole.",
    "Li ho portati durante un pranzo disteso all'aperto.",
    "Li ho usati per un pranzo in giardino che si è allungato.",
    "Li ho indossati per un pranzo al terrazzo che non finiva più.",
    "Li ho portati per un pranzo estivo all'aperto.",
    "Li ho messi durante un pranzo conviviale fuori.",
    "Li ho indossati per un pranzo sotto il sole.",
    "Li ho portati durante un pranzo all'aria aperta.",
    "Li ho usati per un lungo pranzo in esterno.",
    "Li ho indossati per un pranzo che si è prolungato sotto il cielo.",
    "Li ho portati per un pranzo rilassato in terrazza.",
    "Li ho messi per un pranzo fuori che è durato ore.",
    "Li ho indossati durante un pranzo all'aperto che non voleva finire.",
    "Li ho portati per un pranzo nel cortile.",
],

"Li ho presi in un momento in cui volevo cambiare aria al guardaroba.": [
    "Li ho comprati con la voglia di rinnovare il mio stile.",
    "Li ho scelti nel momento in cui sentivo il bisogno di cambiare qualcosa.",
    "Li ho presi quando volevo dare una svolta al mio guardaroba.",
    "Li ho comprati in un periodo di rinnovamento del look.",
    "Li ho scelti perché volevo cambiare completamente registro stilistico.",
    "Li ho presi con la voglia di portare aria nuova nel mio guardaroba.",
    "Li ho comprati in una fase in cui cercavo qualcosa di diverso.",
    "Li ho scelti quando sentivo il bisogno di un cambiamento di look.",
    "Li ho presi con l'intenzione di rinnovare il mio repertorio.",
    "Li ho comprati in un momento di ricerca di novità per il guardaroba.",
    "Li ho scelti per dare una scossa al mio stile.",
    "Li ho presi quando volevo qualcosa che rompesse con il solito.",
    "Li ho comprati nella fase in cui cercavo qualcosa di fresco.",
    "Li ho scelti perché sentivo il bisogno di qualcosa di nuovo.",
    "Li ho presi in un momento di voglia di cambiamento.",
    "Li ho comprati per aggiornare il mio repertorio di accessori.",
    "Li ho scelti in una fase di rinnovamento personale.",
    "Li ho presi quando il mio guardaroba chiedeva aria nuova.",
    "Li ho comprati perché volevo esplorare un nuovo territorio estetico.",
    "Li ho scelti in un momento di metamorfosi stilistica.",
    "Li ho presi con l'idea di rinnovare la mia immagine.",
    "Li ho comprati quando sentivo la necessità di un cambio di rotta.",
    "Li ho scelti perché il mio guardaroba aveva bisogno di un aggiornamento.",
],

"All'inizio li guardavo con curiosità più che con convinzione,": [
    "Inizialmente li osservavo con curiosità più che con certezza,",
    "All'inizio li guardavo con interesse più che con convinzione,",
    "Inizialmente il mio sguardo era di curiosità più che di certezza,",
    "All'inizio li consideravo con interesse più che con decisione,",
    "Inizialmente li guardavo più con curiosità che con fiducia,",
    "All'inizio il mio approccio era curioso più che convinto,",
    "Inizialmente li osservavo con attenzione più che con entusiasmo,",
    "All'inizio li guardavo con occhio esplorativo più che convinto,",
    "Inizialmente la mia reazione era di curiosità più che di adesione,",
    "All'inizio li consideravo con interesse cauto,",
    "Inizialmente li guardavo più con curiosità che con partecipazione,",
    "All'inizio il mio approccio era di curiosità senza convinzione,",
    "Inizialmente li osservavo con interesse ma senza certezze,",
    "All'inizio li guardavo con spirito esplorativo,",
    "Inizialmente li consideravo con curiosità ma con riserva,",
    "All'inizio li guardavo più con interesse che con adesione,",
    "Inizialmente il mio sguardo era curioso ma non convinto,",
    "All'inizio li osservavo con occhio aperto ma non persuaso,",
    "Inizialmente li guardavo con curiosità più che con aspettativa,",
    "All'inizio li consideravo con interesse esplorativo,",
    "Inizialmente li guardavo con attenzione prudente,",
    "All'inizio li osservavo con curiosità più che con desiderio,",
    "Inizialmente il mio approccio era di studio più che di convinzione,",
],

"Ha delle qualità evidenti, sarebbe disonesto negarlo.": [
    "Ha qualità indiscutibili, sarebbe falso non riconoscerle.",
    "Le sue qualità sono evidenti, non si possono negare.",
    "Ha pregi che sarebbe ingiusto non riconoscere.",
    "Le sue qualità sono innegabili, e sarebbe scorretto non ammetterlo.",
    "Ha doti che parlano da sole, non si possono ignorare.",
    "Le qualità ci sono, e sarebbe disonesto non vederle.",
    "Ha meriti evidenti, non si possono disconoscere.",
    "Le sue qualità sono tangibili, sarebbe ingiusto negarle.",
    "Ha punti di forza che non si possono ignorare.",
    "Le qualità sono sotto gli occhi di tutti, negarlo sarebbe falso.",
    "Ha doti chiare, non si può non vederle.",
    "Le sue qualità sono palesi, non ammetterlo sarebbe scorretto.",
    "Ha meriti che saltano all'occhio, non si possono negare.",
    "Le qualità sono obiettive, sarebbe disonesto non riconoscerle.",
    "Ha punti di forza inequivocabili.",
    "Le sue doti sono evidenti, non si può dire il contrario.",
    "Ha meriti oggettivi, e questo va detto.",
    "Le qualità parlano chiaro, e sarebbe scorretto ignorarle.",
    "Ha pregi che non si possono contestare.",
    "Le sue doti sono lampanti, sarebbe ingiusto non dirlo.",
    "Ha qualità che si vedono, e non sarebbe onesto non menzionarle.",
    "Le sue doti sono evidenti ad occhio nudo.",
    "Ha meriti che vanno riconosciuti con onestà.",
],

"Alla fine resto in equilibrio instabile.": [
    "Alla fine rimango in una posizione incerta.",
    "Il bilancio finale è in equilibrio precario.",
    "Il giudizio resta sospeso tra due direzioni.",
    "Alla fine mi trovo in bilico.",
    "Il verdetto è in equilibrio tra due poli.",
    "Alla fine non riesco a decidere in modo netto.",
    "Il giudizio oscilla senza trovare un punto fermo.",
    "Alla fine la mia posizione resta in stallo.",
    "Il bilancio resta in bilico tra sì e no.",
    "Alla fine mi trovo in una zona grigia.",
    "Il giudizio non si stabilizza in modo netto.",
    "Alla fine il mio parere resta sospeso.",
    "Il bilancio oscilla senza trovare stabilità.",
    "Alla fine il giudizio resta in terra di nessuno.",
    "Mi trovo in una posizione incerta, senza un verdetto netto.",
    "Il mio giudizio resta in bilico tra i due estremi.",
    "Alla fine la mia opinione resta in equilibrio precario.",
    "Il bilancio non trova un punto di caduta definitivo.",
    "Alla fine il parere resta a metà strada.",
    "Il giudizio resta in sospensione senza una direzione chiara.",
    "Alla fine la mia posizione resta indecisa.",
    "Il bilancio non riesce a pendere in una direzione sola.",
    "Alla fine il mio verdetto non trova stabilità.",
],

"Mi danno esattamente quella sensazione di prodotto pensato che speravo di trovare.": [
    "Mi trasmettono proprio quella sensazione di prodotto curato che cercavo.",
    "Mi danno l'impressione di prodotto ragionato che desideravo.",
    "Mi restituiscono la sensazione di prodotto progettato con cura che speravo.",
    "Mi comunicano quel senso di prodotto studiato che stavo cercando.",
    "Mi danno quella percezione di prodotto curato che volevo trovare.",
    "Mi trasmettono la sensazione di prodotto pensato con attenzione che speravo.",
    "Mi restituiscono quel feeling di prodotto meditato che cercavo.",
    "Mi danno esattamente la sensazione di cura nel design che desideravo.",
    "Mi comunicano quel senso di qualità progettuale che stavo cercando.",
    "Mi danno la percezione di un prodotto con un pensiero dietro.",
    "Mi trasmettono la sensazione di prodotto deliberato che speravo di incontrare.",
    "Mi restituiscono quel senso di prodotto intenzionale che cercavo.",
    "Mi comunicano la sensazione di prodotto curato nei dettagli che volevo.",
    "Mi danno quel feeling di progetto ragionato che desideravo trovare.",
    "Mi trasmettono la percezione di prodotto pensato che speravo.",
    "Mi restituiscono la sensazione di prodotto deliberato e curato che cercavo.",
    "Mi comunicano quel tipo di cura progettuale che desideravo.",
    "Mi danno la sensazione di prodotto intelligente che stavo cercando.",
    "Mi trasmettono la percezione di prodotto pensato con criterio che speravo.",
    "Mi restituiscono quel senso di prodotto studiato nel dettaglio che cercavo.",
    "Mi comunicano la sensazione di design intenzionale che desideravo trovare.",
    "Mi danno l'impressione di prodotto curato con dedizione che speravo di incontrare.",
    "Mi trasmettono quella sensazione di qualità progettuale che mi aspettavo.",
],

"Li valuto bene come oggetto, un po' meno come risposta universale.": [
    "Come oggetto sono validi, come scelta per tutti un po' meno.",
    "Li apprezzo come prodotto, meno come soluzione universale.",
    "Come oggetto sono riusciti, come proposta per tutti non del tutto.",
    "Li giudico bene come prodotto, meno come risposta per ogni gusto.",
    "Come oggetto sono di valore, come modello per tutti un po' meno.",
    "Li apprezzo per quello che sono, meno come scelta universale.",
    "Come prodotto li valuto positivamente, come proposta per tutti meno.",
    "Li considero un buon oggetto, meno una soluzione per ogni persona.",
    "Come prodotto sono validi, come risposta universale hanno dei limiti.",
    "Li apprezzo come design, meno come scelta adatta a tutti.",
    "Come oggetto li trovo riusciti, come proposta universale meno.",
    "Li valuto bene in sé, meno come soluzione per tutti.",
    "Come prodotto sono apprezzabili, come risposta a ogni esigenza meno.",
    "Li considero buoni come oggetto, più limitati come scelta universale.",
    "Come design li valuto positivamente, come proposta per tutti no del tutto.",
    "Li apprezzo come realizzazione, meno come soluzione per ogni persona.",
    "Come oggetto meritano rispetto, come proposta universale hanno dei confini.",
    "Li giudico positivamente come prodotto, con riserva come scelta per tutti.",
    "Come design sono validi, come risposta universale hanno qualche limite.",
    "Li considero riusciti come oggetto, meno come proposta per ogni gusto.",
    "Come prodotto sono apprezzabili, come soluzione universale un po' meno.",
    "Li valuto positivamente come design, con qualche riserva sulla universalità.",
    "Come oggetto sono meritevoli, come proposta universale non del tutto.",
],

"Ogni volta che lo rimetto trovo un dettaglio nuovo da apprezzare.": [
    "Ogni volta che lo indosso scopro un aspetto diverso da apprezzare.",
    "Ad ogni utilizzo trovo un elemento nuovo che mi piace.",
    "Ogni volta che lo porto noto qualcosa di diverso e positivo.",
    "Ad ogni indossata scopro un dettaglio che non avevo notato prima.",
    "Ogni volta che lo rimetto trovo un nuovo motivo per apprezzarlo.",
    "Ad ogni utilizzo emerge un aspetto nuovo che mi sorprende.",
    "Ogni volta che lo indosso scopro una sfumatura diversa da apprezzare.",
    "Ad ogni contatto trovo un dettaglio nuovo che mi piace.",
    "Ogni volta che lo porto scopro qualcosa di nuovo nel design.",
    "Ad ogni indossata emerge un elemento che non conoscevo.",
    "Ogni volta che lo rimetto noto un aspetto inedito.",
    "Ad ogni utilizzo trovo un nuovo dettaglio da apprezzare.",
    "Ogni volta che lo indosso mi rivela qualcosa di nuovo.",
    "Ad ogni contatto scopro un aspetto che prima mi era sfuggito.",
    "Ogni volta che lo porto noto un dettaglio inedito.",
    "Ad ogni utilizzo mi offre un angolo nuovo da cui ammirarlo.",
    "Ogni volta che lo rimetto mi regala una scoperta.",
    "Ad ogni indossata emerge qualcosa di diverso e positivo.",
    "Ogni volta che lo indosso trovo una ragione in più per apprezzarlo.",
    "Ad ogni contatto mi svela un dettaglio nuovo.",
    "Ogni volta che lo porto mi sorprende con un aspetto inedito.",
    "Ad ogni utilizzo mi rivela una qualità che prima non avevo colto.",
    "Ogni volta che lo rimetto trovo una sfumatura nuova che mi piace.",
],

"Mi piacciono abbastanza da usarli spesso comunque.": [
    "Mi piacciono a sufficienza da usarli regolarmente.",
    "Li apprezzo abbastanza da metterli spesso.",
    "Mi piacciono quanto basta per usarli di frequente.",
    "Li apprezzo a tal punto da usarli regolarmente.",
    "Mi piacciono abbastanza da inserirli nella rotazione frequente.",
    "Li apprezzo quanto basta per metterli spesso.",
    "Mi piacciono a sufficienza da indossarli con regolarità.",
    "Li apprezzo abbastanza da usarli di frequente.",
    "Mi piacciono quanto basta per tenerli nella rotazione.",
    "Li apprezzo a sufficienza da portarli spesso.",
    "Mi piacciono abbastanza da non lasciarli nel cassetto.",
    "Li apprezzo quanto basta per metterli con frequenza.",
    "Mi piacciono a sufficienza da usarli comunque spesso.",
    "Li apprezzo abbastanza da dargli spazio nella rotazione.",
    "Mi piacciono quanto basta per portarli regolarmente.",
    "Li apprezzo a sufficienza da renderli un paio frequente.",
    "Mi piacciono abbastanza da usarli nella routine.",
    "Li apprezzo quanto serve per metterli con costanza.",
    "Mi piacciono a sufficienza da usarli quasi ogni giorno.",
    "Li apprezzo abbastanza da non rinunciarci spesso.",
    "Mi piacciono quanto basta per usarli con continuità.",
    "Li apprezzo a sufficienza da includere nella selezione frequente.",
    "Mi piacciono abbastanza da tenerli in alta rotazione.",
],

"Dopo qualche settimana di uso,": [
    "Dopo alcune settimane di utilizzo,",
    "A qualche settimana dall'acquisto,",
    "Dopo un po' di settimane di uso quotidiano,",
    "Dopo diverse settimane di impiego,",
    "A distanza di qualche settimana dall'acquisto,",
    "Dopo un paio di settimane di utilizzo,",
    "Dopo qualche settimana di esperienza,",
    "A settimane dall'acquisto,",
    "Dopo un periodo d'uso di qualche settimana,",
    "Dopo alcune settimane di uso regolare,",
    "A qualche settimana dall'inizio dell'uso,",
    "Dopo un po' di uso costante,",
    "A distanza di settimane dall'acquisto,",
    "Dopo alcune settimane di utilizzo costante,",
    "Dopo un paio di settimane di uso,",
    "Dopo qualche settimana di prova sul campo,",
    "A settimane dall'inizio dell'esperienza,",
    "Dopo un periodo consistente di utilizzo,",
    "Dopo qualche settimana di uso quotidiano,",
    "A un po' di settimane dall'acquisto,",
    "Dopo qualche settimana di convivenza,",
    "A qualche settimana di distanza,",
    "Dopo un buon periodo di utilizzo,",
],

"Resto in una zona di mezzo: capisco il progetto, non lo amo del tutto.": [
    "Resto in una posizione intermedia: capisco il progetto, non lo amo completamente.",
    "Mi trovo a metà strada: colgo il senso del design, ma non lo abbraccio del tutto.",
    "Sono in una zona grigia: apprezzo il progetto, non lo amo fino in fondo.",
    "Resto in bilico: comprendo la visione, non la faccio mia del tutto.",
    "Mi trovo in una terra di mezzo: capisco il progetto, non lo sento mio del tutto.",
    "Resto in una posizione mediana: vedo il progetto, non lo vivo completamente.",
    "Mi trovo a metà: colgo il disegno, non lo abbraccio completamente.",
    "Resto in equilibrio: capisco la proposta, non la amo fino in fondo.",
    "Mi trovo in un punto intermedio: comprendo il design, non lo sento del tutto.",
    "Resto in una zona neutra: apprezzo il progetto, non lo amo pienamente.",
    "Mi trovo a metà strada: riconosco il valore, non lo faccio mio del tutto.",
    "Resto in bilico: vedo il disegno, non lo vivo completamente.",
    "Mi trovo in una posizione intermedia: capisco l'idea, non la amo del tutto.",
    "Resto in un limbo: comprendo il progetto, non lo sento fino in fondo.",
    "Mi trovo in un punto medio: apprezzo la visione, non la abbraccio del tutto.",
    "Resto indeciso: capisco il design, non lo amo completamente.",
    "Mi trovo in una zona di confine: vedo il progetto, non lo sento mio.",
    "Resto in una posizione ambivalente: colgo il disegno, non lo amo del tutto.",
    "Mi trovo in equilibrio precario: apprezzo il progetto, ma non lo abbraccio.",
    "Resto in una terra di nessuno: comprendo il design, non lo amo pienamente.",
    "Mi trovo a metà del percorso: capisco il progetto, non lo vivo del tutto.",
    "Resto in un punto sospeso: vedo il disegno, non lo amo fino in fondo.",
    "Mi trovo in una zona intermedia: apprezzo l'idea, non la sento mia del tutto.",
],

"Sono di quei modelli che vanno raccontati dopo qualche utilizzo, non subito.": [
    "Sono modelli che richiedono tempo per essere raccontati.",
    "Sono il tipo di modello che va descritto dopo averlo provato, non al primo sguardo.",
    "Sono paia che si raccontano meglio dopo qualche giorno di uso.",
    "Sono modelli il cui racconto migliora con l'esperienza.",
    "Sono il tipo di paio che va raccontato dopo averlo vissuto.",
    "Sono modelli che si descrivono meglio con qualche utilizzo alle spalle.",
    "Sono paia la cui storia si scrive col tempo.",
    "Sono modelli che richiedono esperienza prima di essere giudicati.",
    "Sono il tipo di paio il cui racconto matura con l'uso.",
    "Sono modelli che vanno scoperti col tempo, non giudicati al volo.",
    "Sono paia che si apprezzano dopo qualche utilizzo, non subito.",
    "Sono modelli la cui storia ha bisogno di tempo per formarsi.",
    "Sono il tipo di paio che va conosciuto prima di essere raccontato.",
    "Sono modelli che richiedono qualche indossata per essere capiti.",
    "Sono paia il cui giudizio matura col tempo.",
    "Sono modelli che si raccontano meglio dopo qualche esperienza.",
    "Sono il tipo di paio che va vissuto prima di essere descritto.",
    "Sono modelli che richiedono pazienza prima di essere compresi.",
    "Sono paia la cui bellezza emerge dopo qualche utilizzo.",
    "Sono modelli che si capiscono davvero solo dopo qualche indossata.",
    "Sono il tipo di paio che chiede tempo prima di essere giudicato.",
    "Sono modelli la cui essenza si svela con l'uso ripetuto.",
    "Sono paia che vanno provati a lungo prima di poter dire la propria.",
],

"Li ho testati in una giornata piena, dal caffè del mattino all'aperitivo.": [
    "Li ho provati in una giornata intera, dalla colazione alla sera.",
    "Li ho portati per una giornata completa, dal mattino fino a sera.",
    "Li ho messi alla prova in una giornata intensa dal mattino all'aperitivo.",
    "Li ho usati dalla mattina al tardo pomeriggio in una giornata piena.",
    "Li ho testati per un'intera giornata, dal caffè mattutino alla sera.",
    "Li ho portati per tutta la giornata, dalla colazione al tramonto.",
    "Li ho indossati in una giornata piena, dalla mattina all'aperitivo serale.",
    "Li ho messi alla prova per un'intera giornata di impegni.",
    "Li ho usati dalla prima colazione alla tarda sera.",
    "Li ho portati in una giornata completa, dal mattino presto alla sera.",
    "Li ho provati durante un'intera giornata piena di impegni.",
    "Li ho indossati dalla mattina all'aperitivo, in una giornata intensa.",
    "Li ho messi alla prova in una giornata che non finiva più.",
    "Li ho testati dalla colazione alla cena in una giornata piena.",
    "Li ho portati per un'intera giornata senza mai toglierli.",
    "Li ho usati per tutto il giorno, dal primo caffè all'ultimo drink.",
    "Li ho indossati dalla mattina alla sera in una giornata intensa.",
    "Li ho provati in una giornata piena dal primo al ultimo impegno.",
    "Li ho portati per tutta una giornata frenetica.",
    "Li ho testati dalla mattina alla sera, in una giornata completa.",
    "Li ho usati per un'intera giornata senza tregua.",
    "Li ho indossati in una maratona giornaliera dalla colazione all'aperitivo.",
    "Li ho portati in una giornata intensa e piena di impegni.",
],

"Si inseriscono bene anche in un guardaroba già pieno di cose diverse.": [
    "Si integrano facilmente anche in un guardaroba già ricco e vario.",
    "Trovano il loro spazio anche in un guardaroba diversificato.",
    "Si ambientano bene anche in un repertorio stilistico già vario.",
    "Si inseriscono senza problemi in un guardaroba eclettico.",
    "Trovano il loro posto anche tra molti stili diversi.",
    "Si integrano facilmente anche in un armadio già pieno di varietà.",
    "Si inseriscono naturalmente in un guardaroba variegato.",
    "Trovano spazio anche in un repertorio stilistico ricco.",
    "Si ambientano bene anche tra capi diversissimi tra loro.",
    "Si integrano senza fatica in un guardaroba già articolato.",
    "Trovano il loro angolo anche in un armadio eterogeneo.",
    "Si inseriscono con disinvoltura in un guardaroba vario.",
    "Trovano posto facilmente anche tra stili molto diversi.",
    "Si integrano bene anche in un guardaroba già complesso.",
    "Si ambientano naturalmente anche in un armadio variegato.",
    "Trovano la loro nicchia anche in un guardaroba eclettico.",
    "Si inseriscono senza sforzo in un repertorio di stili diversi.",
    "Si integrano bene anche in un guardaroba già molto vario.",
    "Trovano il loro ruolo anche tra molti paia diversi.",
    "Si inseriscono armoniosamente in un armadio già ricco.",
    "Si integrano con facilità in un guardaroba dalla grande varietà.",
    "Trovano spazio naturalmente anche tra stili molto differenti.",
    "Si inseriscono bene anche in un guardaroba dal repertorio ampio.",
],

"A volte basta mezzo millimetro nel ponte per spostare tutto.": [
    "A volte mezzo millimetro nel ponte cambia tutto il risultato.",
    "Basta una minima differenza nel ponte per cambiare l'aspetto.",
    "A volte una variazione minima nel ponte ribalta l'effetto.",
    "Basta pochissimo nel ponte per cambiare la resa finale.",
    "A volte una piccola differenza nella misura del ponte altera tutto.",
    "Basta un niente nel ponte per cambiare l'intera percezione.",
    "A volte è una questione di millimetri nel ponte.",
    "Basta una variazione minima nel ponte per spostare l'equilibrio.",
    "A volte la differenza sta in mezzo millimetro di ponte.",
    "Basta poco nel ponte per cambiare il quadro completo.",
    "A volte un dettaglio nel ponte fa tutta la differenza.",
    "Basta una sfumatura nella misura del ponte per ribaltare l'effetto.",
    "A volte è il ponte a fare tutta la differenza sul viso.",
    "Basta una minima variazione del ponte per cambiare tutto.",
    "A volte un piccolo scarto nel ponte altera l'intera resa.",
    "Basta pochissimo nella posizione del ponte per spostare il giudizio.",
    "A volte mezzo millimetro di ponte fa la differenza tra stare bene e no.",
    "Basta un nonnulla nel ponte per cambiare come stanno addosso.",
    "A volte una minima differenza nel ponte cambia radicalmente l'effetto.",
    "Basta un dettaglio nel ponte per alterare tutta la vestibilità.",
    "A volte è questione di dettagli nel ponte per spostare l'equilibrio.",
    "Basta un millimetro nel ponte per cambiare la resa sul viso.",
    "A volte il ponte è la chiave che apre o chiude il giudizio.",
],

"Li ho messi alla prova in più contesti,": [
    "Li ho testati in diversi contesti,",
    "Li ho provati in varie situazioni,",
    "Li ho usati in più occasioni diverse,",
    "Li ho messi alla prova in situazioni diverse,",
    "Li ho portati in contesti differenti,",
    "Li ho testati in varie circostanze,",
    "Li ho provati in più situazioni,",
    "Li ho usati in contesti diversi,",
    "Li ho messi alla prova in diverse occasioni,",
    "Li ho portati in varie situazioni e contesti,",
    "Li ho indossati in contesti differenti,",
    "Li ho provati in più ambiti,",
    "Li ho usati in varie occasioni,",
    "Li ho portati in diverse circostanze,",
    "Li ho testati in ambienti diversi,",
    "Li ho messi alla prova in più occasioni,",
    "Li ho provati in diversi ambienti,",
    "Li ho usati in contesti variegati,",
    "Li ho portati in più situazioni diverse,",
    "Li ho indossati in circostanze differenti,",
    "Li ho messi alla prova in vari ambienti,",
    "Li ho testati in diverse situazioni quotidiane,",
    "Li ho provati in contesti molteplici,",
],

}
