#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Dizionario PATTERN -> ALTERNATIVE (Parte 3: Frasi interne ad alta frequenza)"""

INTERNAL_PATTERNS = {

# ── 122x ──
"mi ha convinto soprattutto il fatto che": [
    "il fattore decisivo per me è stato che", "il punto forte è che",
    "la cosa più convincente è che", "quello che mi ha conquistato è che",
    "il vero punto a favore è che", "il dettaglio che ha fatto la differenza è che",
    "la carta vincente è che", "quello che mi ha fatto propendere è che",
    "il motivo per cui lo apprezzo è che", "il cuore di tutto è che",
    "ciò che pesa di più nel giudizio è che", "la ragione per cui funziona è che",
    "il tratto che colpisce di più è che", "la forza vera sta nel fatto che",
    "la qualità principale è che", "quello che spicca è che",
    "il pregio su cui non transigo è che", "il merito maggiore è che",
    "il valore aggiunto è che", "la cifra stilistica convincente è che",
    "il dato più importante è che", "la qualità che mi trattiene è che",
    "la ragione principale della mia approvazione è che", "la chiave è che",
    "il peso specifico di questo paio sta nel fatto che", "la nota migliore è che",
    "il pregio più tangibile è che", "la qualità più evidente è che",
    "il punto che ho apprezzato di più è che", "il tratto distintivo è che",
    "la combinazione vincente è che", "la ragione per cui lo terrei è che",
    "la dimensione che apprezzo di più è che", "il fulcro dell'esperienza è che",
    "il dato che sposta il giudizio è che", "la scoperta più bella è che",
    "il fattore che ha pesato di più è che", "ciò che mi ha convinto davvero è che",
    "il merito fondamentale è che", "il plus più significativo è che",
    "il dettaglio che conta è che", "quello che resta dopo la prova è che",
    "il punto più riuscito è che", "la nota vincente è che",
    "il fattore chiave è che", "la prima qualità reale è che",
    "la ragione di fondo è che", "il nodo che scioglie tutto è che",
    "il tratto davvero forte è che", "cosa apprezzo più di tutto? Che",
    "il segreto di questo paio è che", "il senso dell'acquisto è che",
    "il centro della questione è che", "la sostanza è che",
    "il peso specifico del giudizio sta nel fatto che", "il vero guadagno è che",
    "il perno del mio giudizio è che", "quello che fa la differenza qui è che",
    "il dettaglio più riuscito è che", "la ragione concreta è che",
    "il criterio che pesa di più è che", "la parte più riuscita è che",
    "il punto fermo è che", "il merito indiscutibile è che",
    "il dato concreto è che", "ciò che funziona meglio è che",
    "la qualità che emerge è che", "il tratto più apprezzabile è che",
    "il pregio che pesa di più è che", "il cardine del giudizio è che",
    "la ragione solida è che", "il fondamento è che",
    "il valore più tangibile è che", "la nota dominante è che",
    "ciò che sposta l'ago della bilancia è che", "il fattore risolutivo è che",
    "il lato più forte è che", "la componente decisiva è che",
    "il punto di forza reale è che", "il dato più eloquente è che",
    "il merito che conta sul serio è che", "ciò che tiene insieme tutto è che",
    "il motivo più concreto è che", "la leva decisiva è che",
    "la parte che funziona meglio è che", "il nocciolo è che",
    "il vantaggio reale è che", "la qualità che resta è che",
    "il punto su cui non si discute è che", "il contributo più prezioso è che",
    "la sostanza vera è che", "il filo rosso è che",
    "l'aspetto che pesa più degli altri è che", "il vero centro del discorso è che",
    "la componente vincente è che", "il lato che apprezzo di più è che",
    "la ragione più solida è che", "il dato che chiude il discorso è che",
    "il nervo scoperto di questo paio è che", "ciò che lo rende speciale è che",
    "il punto cardine è che", "la forza principale è che",
    "il pregio che fa la differenza è che", "il motivo più forte è che",
    "ciò che li rende unici è che", "il cuore della questione è che",
    "il dettaglio più significativo è che", "la parte più efficace è che",
    "quello che ho apprezzato veramente è che", "il tratto più incisivo è che",
    "il fattore più importante è che", "il pregio fondamentale è che",
    "la ragione su cui poggia tutto è che", "il merito che non si può ignorare è che",
    "ciò che rende l'acquisto valido è che", "la qualità portante è che",
    "il motivo centrale è che", "il nucleo del giudizio è che",
    "il punto più importante è che", "la nota che conta è che",
    "il patrimonio di questo paio è che", "il dato più rilevante è che",
    "l'elemento che fa centro è che", "la forza del modello è che",
    "il lato su cui puntare è che", "la dimensione più convincente è che",
],

# ── 122x ──
"Per il mio gusto rendono al massimo": [
    "Nel mio stile funzionano al meglio", "Per come li vedo danno il massimo",
    "Nella mia esperienza rendono al top", "Per il mio tipo di utilizzo eccellono",
    "In base al mio gusto esprimono il loro meglio", "Per quello che cerco funzionano alla grande",
    "Nel mio caso il massimo lo danno", "Secondo il mio metro sono al meglio",
    "Per come li utilizzo rendono benissimo", "Con il mio guardaroba danno il massimo",
    "Per la mia estetica sono perfetti", "Con il mio stile raggiungono l'apice",
    "Nel mio contesto rendono in modo ottimale", "Per i miei canoni danno il meglio",
    "Nel mio uso quotidiano esprimono il massimo", "Al mio polso estetico funzionano alla perfezione",
    "Per i miei standard sono al massimo", "Con il mio tipo di viso rendono al meglio",
    "Nella mia rotazione sono al top", "Per i miei abbinamenti restituiscono al massimo",
    "Con il mio look esprimono il loro potenziale", "Per la mia fisionomia funzionano benissimo",
    "Nel mio ecosistema estetico sono al massimo", "Per come vesto danno il meglio",
    "Con i miei outfit rendono al picco", "Per il mio uso personale sono perfetti",
    "Secondo i miei canoni esprimono il loro meglio", "Per le mie esigenze sono ideali",
    "Con il mio approccio funzionano alla grande", "Per il mio stile di vita danno il non plus ultra",
    "Nella mia combinazione rendono al meglio", "Per il mio livello di utilizzo sono eccellenti",
    "Nel mio caso esprimono una resa alta", "Con il mio tipo di outfit sono al massimo",
    "Per me raggiungono il loro culmine estetico", "Con la mia fisionomia esprimono il meglio",
    "Per come li abbino funzionano splendidamente", "Nella mia quotidianità rendono bene",
    "Per le mie fattezze esprimono il massimo", "Con il mio guardaroba sono al meglio",
    "Per il mio modo di portarli il resa è altissima", "In base ai miei gusti danno una resa superlativa",
    "Con i miei look esprimono il loro massimo", "Nel mio contesto estetico rendono alla perfezione",
    "Per i miei outfit funzionano al meglio", "Con la mia estetica raggiungono il top",
    "Per il mio tipo di stile danno il meglio", "Nel mio caso raggiungono l'espressione migliore",
    "Con il mio approccio estetico rendono in modo eccellente", "Per i miei gusti specifici sono al culmine",
    "Nel mio quotidiano esprimono il non plus ultra", "Per il mio look sono al loro apice",
    "Con il mio stile personale danno il massimo risultato", "Secondo il mio metro personale rendono benissimo",
    "Per come li porto nella quotidianità funzionano al meglio", "In base alla mia esperienza raggiungono il massimo",
    "Con il mio registro estetico sono al top", "Per il mio contesto d'uso esprimono il loro meglio",
    "Nel mio stile quotidiano danno una resa ottima", "Con le mie proporzioni facciali sono ideali",
    "Per il mio approccio alla moda sono al meglio", "Secondo le mie preferenze personali esprimono il culmine",
    "Con i miei abbinamenti collaudati rendono perfettamente", "Per la mia idea di stile sono al loro massimo",
    "Nel mio guardaroba raggiungono la resa migliore", "Con il mio modo di indossarli funzionano alla grande",
    "Per il mio caso specifico sono al loro meglio", "In relazione al mio stile danno il massimo",
    "Con la mia base di outfit rendono eccellentemente", "Per le mie combinazioni esprimono il culmine",
    "Nel mio contesto personale raggiungono il picco", "Per il mio spettro estetico funzionano al top",
    "Con il mio tipo di look esprimono il non plus ultra", "Per le mie preferenze danno una resa superlativa",
    "Nella mia selezione di outfit sono al meglio", "Con il mio stile consolidato rendono alla grande",
    "Per il mio caso personale esprimono il meglio", "In base al mio stile quotidiano funzionano perfettamente",
    "Con la mia estetica personale raggiungono il top", "Per il mio gusto consolidato danno il massimo risultato",
    "Nel mio repertorio estetico sono al massimo", "Con le mie scelte di stile rendono al meglio",
    "Per i miei canoni personali esprimono il culmine", "In relazione ai miei look esprimono il meglio",
    "Con il mio senso estetico renderizzano al massimo", "Per la mia combinazione personale funzionano benissimo",
    "Nel mio registro quotidiano sono al meglio", "Con i miei parametri estetici danno il massimo",
    "Per le mie esigenze di stile esprimono il loro meglio", "Nella mia versione di look sono al top",
    "Con il mio linguaggio estetico rendono eccellentemente", "Per il mio tono personale funzionano perfettamente",
    "In base al mio registro estetico danno il massimo", "Con il mio profilo stilistico sono al culmine",
    "Per come vesto e vivo funzionano alla perfezione", "Con la mia tipologia di look esprimono il meglio",
    "Nel mio quotidiano estetico rendono al massimo", "Per il mio universo stilistico danno una resa eccellente",
    "Con le mie scelte abituali funzionano al meglio", "In ogni mio outfit esprimono il massimo",
    "Per il mio tipo di giornata rendono benissimo", "Con il mio approccio estetico personale sono al top",
    "In relazione alla mia selezione danno il culmine", "Per il mio guardaroba specifico funzionano perfettamente",
    "Con il mio modo di presentarmi rendono al meglio", "Per la mia identità stilistica esprimono il massimo",
    "Nel mio modo di vestire danno una resa superlativa", "Con il mio tipo di estetica sono al massimo",
    "Per il mio contesto di uso reale funzionano alla grande", "Con i miei parametri rendono eccellentemente",
    "Per il mio gusto specifico sono al non plus ultra", "Con il mio taglio di look danno il meglio",
],

# ── 114x ──
"dà identità, ma la cosa migliore è che": [
    "conferisce carattere, e il bello è che", "regala personalità, e il pregio principale è che",
    "dona una marcia in più, e soprattutto", "aggiunge un timbro riconoscibile, e il meglio è che",
    "definisce il look, e il vero plus è che", "dà grinta, e la cosa che apprezzo di più è che",
    "rafforza l'immagine, e il punto forte è che", "imprime uno stile, e la parte migliore è che",
    "porta un'identità chiara, e il merito principale è che", "segna il viso con personalità, e la cosa migliore è che",
    "restituisce un'impronta forte, e soprattutto", "introduce una nota personale, e il dato migliore è che",
    "colora il volto con carattere, e il valore aggiunto è che", "stampa la sua firma, e il bello resta che",
    "parla chiaro in termini di stile, e il top è che", "firma il volto, e la parte più convincente è che",
    "impone la sua personalità, e il vantaggio reale è che", "definisce subito chi li porta, e la sorpresa è che",
    "dà una direzione precisa, e il punto più riuscito è che", "mette un accento sull'immagine, e il meglio è che",
    "crea un'identità visiva, e la cosa più riuscita è che", "caratterizza il viso, e il dato più importante è che",
    "restituisce carattere al look, e la parte migliore è che", "imprime una nota personale, e soprattutto",
    "dona un segno distintivo, e il punto di forza è che", "crea un timbro unico, e il pregio è che",
    "marca il viso con stile, e il bello è che", "aggiunge una dimensione al look, e la forza vera è che",
    "rende il viso riconoscibile, e la parte migliore è che", "regala un accento personale, e il dato forte è che",
    "imprime personalità, e il prezzo in più è che", "definisce il tono del look, e la carta vincente è che",
    "dona un piglio preciso, e il meglio è che", "introduce un tono personale, e il valore è che",
    "porta una firma stilistica, e il plus è che", "dà un'identità inconfondibile, e la parte migliore è che",
    "comunica qualcosa di preciso, e il punto forte è che", "genera un'impressione chiara, e soprattutto",
    "lascia un segno, e il vero grande pregio è che", "racconta qualcosa del portatore, e il bello è che",
    "impone un tono, e la nota migliore è che", "regala un profilo, e il merito maggiore è che",
    "porta un'impronta, e la sorpresa positiva è che", "offre un linguaggio visivo, e il meglio resta che",
    "segna il look con decisione, e la cosa più forte è che", "dona un punto di vista, e soprattutto",
    "costruisce un'identità, e il centro di tutto è che", "mette un sigillo sull'immagine, e il pregio fondamentale è che",
    "crea un punto di riconoscibilità, e il vantaggio è che", "caratterizza lo sguardo, e il punto forte è che",
    "arricchisce il viso, e ciò che mi piace di più è che", "impone il suo carattere, ma il bello è che",
    "presenta un timbro forte, e la cosa più piacevole è che", "rafforza l'immagine personale, e il dato forte è che",
    "porta identità senza imporre, e il meglio è che", "rende il look leggibile, e la parte migliore è che",
    "dona un'aura specifica, e il vero punto a favore è che", "marca il viso senza esagerare, e soprattutto",
    "crea un punto di ancoraggio estetico, e il pregio è che", "firma il look con decisione, e il meglio è che",
    "imprime una nota di carattere, e la cosa che spicca è che", "dona presenza, e il dato più rilevante è che",
    "offre personalità, e lo spirito forte è che", "porta una visione, e il punto più interessante è che",
    "regala un senso di appartenenza stilistica, e il pregio principale è che", "definisce il carattere del look, e soprattutto",
    "introduce un'identità riconoscibile, e il meglio è che", "afferma una personalità precisa, e il bello è che",
    "dà corpo al look, e il pregio reale è che", "crea un'identità coerente, e il vantaggio è che",
    "disegna un profilo definito, e la parte migliore è che", "impone un'estetica chiara, e il punto forte è che",
    "regala una firma leggibile, e il dato che conta è che", "dona un accento puntuale, e il meglio di tutto è che",
    "costruisce una narrativa visiva, e il pregio fondamentale è che", "lascia un'impronta precisa, e soprattutto",
    "porta una direzione stilistica, e il bello è che", "affianca identità e stile, e il pregio esecutivo è che",
    "segna il proprio territorio estetico, e il dato forte è che", "parla con voce propria, e il meglio è che",
    "arricchisce l'immagine con un tratto preciso, e la parte migliore è che", "dona gravità al look, e il pregio maggiore è che",
    "offre un punto di riferimento estetico, e soprattutto", "realizza un'identità tangibile, e il vantaggio è che",
    "marca il look con chiarezza, e il dato più rilevante è che", "firma il volto con stile, e il punto forte è che",
    "garantisce riconoscibilità, e il bello resta che", "esprime un'idea di stile precisa, e il meglio è che",
    "dà peso al look, e il pregio fondamentale è che", "crea un mood definito, e soprattutto",
    "stabilisce un tono, e il merito migliore è che", "trasmette personalità, e la parte più convincente è che",
    "porta un messaggio visivo chiaro, e il plus è che", "offre un senso di completezza, e il punto forte è che",
    "accende il look, e la nota migliore è che", "solleva il profilo del viso, e il bello è che",
    "incastona un'identità nel look, e il punto più riuscito è che", "imprime una visione precisa, e il meglio è che",
    "dona un centro di gravità estetica, e il dato forte è che", "costruisce l'identità del look, e soprattutto",
    "introduce una nota distintiva, e la parte migliore è che", "crea un filo conduttore tra viso e stile, e il bello è che",
    "attribuisce un carattere definito, e il meglio è che", "apporta una nota di personalità, e il pregio è che",
    "regala una direzione estetica precisa, e il plus è che", "porta coerenza al look, e il pregio reale è che",
    "segna l'immagine con grazia, e il dato migliore è che", "dona un'impronta che resta, e soprattutto",
    "rafforza il profilo del look, e il valore aggiunto è che", "aggiunge profondità al look, e la nota forte è che",
    "crea coerenza tra viso e stile, e il pregio è che", "stabilisce le regole del look, e il bello è che",
    "iscrive il suo segno nel look, e il merito è che", "compone un'identità definita, e il dato forte è che",
],

# ── 114x ──
"qui hanno trovato un equilibrio raro.": [
    "il risultato è un bilanciamento davvero riuscito.", "la combinazione funziona in modo sorprendente.",
    "l'armonia raggiunta è notevole.", "la resa complessiva è eccellente.",
    "il mix è calibrato con precisione.", "l'equilibrio è davvero centrato.",
    "il bilanciamento tra gli elementi è notevole.", "la proporzione raggiunta è invidiabile.",
    "la fusione degli elementi è riuscita.", "l'alchimia funziona davvero.",
    "il risultato è una composizione molto armonica.", "la formula è azzeccata.",
    "la sintesi è riuscita in modo brillante.", "il connubio è felice e naturale.",
    "l'accostamento è riuscito senza forzature.", "il compromesso estetico è perfetto.",
    "il dialogo tra i materiali è ottimo.", "la convivenza tra gli elementi funziona bene.",
    "la combinazione raggiunge un livello alto.", "la simbiosi è perfettamente calcolata.",
    "il dosaggio è preciso e convincente.", "il rapporto tra gli elementi è centrato.",
    "la calibrazione è impeccabile.", "la coesistenza funziona a meraviglia.",
    "l'integrazione è sorprendente.", "l'intesa tra materiali e forma è riuscita.",
    "la combo è davvero azzeccata.", "l'armonia tra le parti è rara.",
    "il bilanciamento è di quelli che colpiscono.", "la resa unitaria è davvero convincente.",
    "la composizione raggiunge un punto raro di grazia.", "il dosaggio degli elementi è ben studiato.",
    "il rapporto tra le componenti è riuscito.", "l'intesa tra forma e materia è eccellente.",
    "la miscela è perfettamente bilanciata.", "la sinergia è evidente e funzionale.",
    "il compromesso raggiunto è tra i migliori che abbia visto.", "l'amalgama è convincente.",
    "il dialogo tra design e materiale è centrato.", "il bilanciamento è il tratto più forte.",
    "la proporzione è quella giusta.", "l'intesa tra gli elementi è convincente.",
    "il rapporto tra le parti è precisamente calibrato.", "la chimica funziona.",
    "il gioco di pesi è perfetto.", "l'unione degli elementi è senza sbavature.",
    "la coerenza interna è notevole.", "la combinazione è una delle più riuscite che conosca.",
    "la convivenza tra le parti è fluida.", "l'architettura complessiva è solida.",
    "la complementarità è perfetta.", "l'integrazione tra le parti è sorprendente.",
    "la proporzione è centrata in pieno.", "il mix è riuscito con una facilità apparente.",
    "la sinfonia tra gli elementi è convincente.", "il concerto è ben orchestrato.",
    "la compatibilità è totale.", "l'intesa è rara e funzionale.",
    "la coesione è tra le migliori che abbia visto.", "il bilanciamento è misurato con attenzione.",
    "il quadro complessivo è armonico.", "la formula è bilanciata e convincente.",
    "la resa d'insieme è sorprendente.", "il connubio è di rara efficacia.",
    "la saldatura tra le componenti è precisa.", "l'amalgama tra gli elementi è riuscita.",
    "la giustapposizione funziona perfettamente.", "la formula è centrata.",
    "l'architettura d'insieme è ben pensata.", "il mix ha una qualità rara.",
    "la composizione è fluida e convincente.", "l'integrazione è naturale.",
    "l'armonia complessiva è rara da trovare.", "il connubio è riuscito con grazia.",
    "la simbiosi è ben costruita.", "il rapporto è di quelli che funzionano davvero.",
    "il bilanciamento ha un livello di finezza raro.", "la fusione è impeccabile.",
    "il dosaggio è preciso come un orologio.", "l'equazione è risolta in modo elegante.",
    "la ricetta qui funziona davvero.", "il connubio è naturale e convincente.",
    "la combinazione è studiata con intelligenza.", "l'equilibrio raggiunto è notevole.",
    "il mix è tra i più calibrati della categoria.", "la resa complessiva è perfettamente accordata.",
    "la proporzione è centrata con una precisione rara.", "il bilanciamento qui è il punto più alto.",
    "la sinergia è il tratto dominante.", "la formula è quella giusta.",
    "l'integrazione tra le varie componenti è esemplare.", "il connubio è uno dei più riusciti che abbia provato.",
    "l'armonia qui è il vero traguardo raggiunto.", "il mix è efficace e ben dosato.",
    "la composizione complessiva è di alto livello.", "la cocktail di elementi è riuscito.",
    "il quadro complessivo raggiunge un equilibrio insolito.", "la combinazione è una di quelle che funzionano davvero.",
    "l'amalgama è di rara qualità.", "la convivenza tra le componenti è esemplare.",
    "il bilanciamento si colloca ai vertici della categoria.", "la resa unitaria raggiunge un livello elevato.",
    "la calibra degli elementi è precisa e convincente.", "il rapporto tra le parti è tra i migliori.",
    "il mix raggiunge un'armonia rara.", "la formula complessiva è centrata perfettamente.",
    "la sinergia tra forme e materiali è ai massimi.", "l'equazione estetica è perfettamente risolta.",
    "la convivenza è riuscita come poche volte.", "la proporzione raggiunta è di quelle che colpiscono.",
    "il risultato complessivo è armonioso e misurato.", "il mix qui raggiunge una sintesi rara.",
],

}
