#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Dizionario PATTERN -> ALTERNATIVE (Parte 14: pattern residui 16x-13x)"""

RESIDUAL_EXTRA2 = {

"Di solito capisco subito se un paio mi accompagnerà davvero.": [
    "Di norma capisco rapidamente se un paio entrerà nella mia vita.",
    "Solitamente capisco in fretta se un paio diventerà parte della mia routine.",
    "Di solito in poco tempo mi è chiaro se un paio farà strada con me.",
    "Di norma capisco presto se un paio resterà con me.",
    "Solitamente sono veloce a capire se un paio avrà un futuro con me.",
    "Di solito bastano pochi giorni per capire se un paio resterà.",
    "Di norma capisco subito se un paio avrà vita lunga con me.",
    "Solitamente capisco velocemente se un paio mi accompagnerà.",
    "Di solito capisco al volo se un paio diventerà abituale.",
    "Di norma capisco rapidamente se un paio avrà un ruolo nella mia vita.",
    "Solitamente è questione di poco per capire se un paio resterà.",
    "Di solito capisco subito se un paio farà parte del mio quotidiano.",
    "Di norma mi basta poco per capire se un paio mi accompagnerà.",
    "Solitamente in pochi utilizzi capisco se un paio avrà un futuro.",
    "Di solito il mio istinto mi dice subito se un paio resterà.",
    "Di norma capisco velocemente se un paio diventerà il mio compagno.",
    "Solitamente non mi serve molto per capire se un paio mi accompagnerà.",
    "Di solito capisco in fretta se un paio entrerà nella rotazione.",
    "Di norma bastano pochissimi utilizzi per capire il futuro di un paio.",
    "Solitamente è chiaro fin da subito se un paio resterà con me.",
],

"Ho un viso che non perdona molto e quindi giudico in fretta.": [
    "Ho lineamenti che non perdonano errori e per questo giudico rapidamente.",
    "Il mio viso è esigente nei confronti degli occhiali, per cui giudico presto.",
    "Ho un volto che non lascia margine e per questo valuto in fretta.",
    "I miei lineamenti sono severi e per questo il giudizio è rapido.",
    "Ho un viso che non concede molto agli occhiali e per questo sono veloce a giudicare.",
    "Il mio volto è impietoso con gli occhiali sbagliati, per cui valuto subito.",
    "Ho lineamenti che richiedono precisione, per questo giudico rapidamente.",
    "Il mio viso non perdona facilmente e per questo il mio giudizio è rapido.",
    "Ho un volto esigente che non concede margine, per cui giudico presto.",
    "I miei lineamenti sono molto selettivi e per questo valuto in fretta.",
    "Ho un viso che richiede precisione e per questo giudico rapidamente.",
    "Il mio volto non è generoso con tutti gli occhiali, per cui sono rapido.",
    "Ho lineamenti impegnativi e per questo il giudizio arriva presto.",
    "Il mio viso è un test severo per qualsiasi occhiale.",
    "Ho un volto che non fa sconti e per questo giudico velocemente.",
    "I miei lineamenti sono un banco di prova rigoroso per gli occhiali.",
    "Ho un viso selettivo che non perdona imprecisioni.",
    "Il mio volto è un giudice severo che non lascia margine.",
    "Ho lineamenti che chiedono precisione e per questo il giudizio è immediato.",
    "Il mio viso non è facile da accontentare, il giudizio è rapido.",
],

"Mi conosco: se un occhiale mi complica la vita, sparisce in tre giorni.": [
    "Mi conosco bene: se un paio mi crea problemi, lo abbandono subito.",
    "So come funziono: se un occhiale mi complica le cose, lo metto via rapidamente.",
    "Mi conosco: se un paio diventa un problema, finisce nel cassetto in fretta.",
    "So come ragiono: se un occhiale non semplifica, sparisce velocemente.",
    "Mi conosco bene: se un paio diventa un fastidio, lo elimino dalla rotazione.",
    "So cosa mi serve: se un occhiale mi crea problemi, lo scarto in fretta.",
    "Mi conosco: se un paio diventa complicato, lo metto da parte subito.",
    "So come funziono: se un occhiale mi dà problemi, lo abbandono rapidamente.",
    "Mi conosco bene: se un paio non è pratico, lo tolgo dalla rotazione.",
    "So cosa voglio: se un occhiale complica le cose, lo elimino in fretta.",
    "Mi conosco: se un paio mi crea difficoltà, lo accantono senza pensarci.",
    "So come sono fatto: se un occhiale non funziona, lo metto da parte subito.",
    "Mi conosco bene: se un paio diventa un problema, finisce in fondo al cassetto.",
    "So cosa mi serve: se un occhiale diventa un problema, lo abbandono velocemente.",
    "Mi conosco: se un paio non è comodo, sparisce dalla mia rotazione.",
    "So come funziono: se un occhiale mi complica il quotidiano, lo metto via.",
    "Mi conosco bene: se un paio è problematico, lo abbandono senza rimpianti.",
    "So come ragiono: se un occhiale diventa un peso, lo elimino in fretta.",
    "Mi conosco: se un paio non funziona praticamente, lo accantono.",
    "So cosa mi serve: se un occhiale complica la routine, finisce nel dimenticatoio.",
],

"Su di me restano più belli da vedere che da portare.": [
    "Addosso a me sono più belli in teoria che in pratica.",
    "Su di me funzionano meglio nell'idea che nell'uso.",
    "Addosso a me restano più belli da guardare che da indossare.",
    "Su di me sono più belli nell'immaginazione che nella realtà.",
    "Addosso a me funzionano meglio allo specchio che nella vita.",
    "Su di me restano più belli da ammirare che da vivere.",
    "Addosso a me sono più belli in foto che addosso.",
    "Su di me funzionano meglio come idea che come realtà.",
    "Addosso a me restano più belli in vetrina che sul viso.",
    "Su di me sono più belli nella teoria che nella pratica.",
    "Addosso a me funzionano meglio da guardare che da portare.",
    "Su di me restano più affascinanti in astratto che nell'uso.",
    "Addosso a me sono più belli come oggetto che come accessorio portato.",
    "Su di me funzionano meglio come idea estetica che come realtà d'uso.",
    "Addosso a me restano più belli da osservare che da vivere.",
    "Su di me sono più attraenti in teoria che addosso.",
    "Addosso a me funzionano meglio come concept che come paio portato.",
    "Su di me restano più belli da contemplare che da usare.",
    "Addosso a me sono più belli sulla carta che sul viso.",
    "Su di me funzionano meglio come oggetto che come accessorio.",
],

"Li guardo e ne capisco il fascino, ma addosso il discorso cambia.": [
    "Li osservo e ne colgo il fascino, ma indosso il discorso è diverso.",
    "Li guardo e ne capisco l'attrattiva, ma addosso la resa cambia.",
    "Li ammiro e ne comprendo il fascino, ma una volta indossati il discorso è un altro.",
    "Li osservo e ne apprezzo il fascino, ma addosso tutto cambia.",
    "Li guardo e ne vedo il fascino, ma portati il discorso si modifica.",
    "Li osservo e ne colgo l'attrattiva, ma indossati la questione è diversa.",
    "Li guardo e li trovo affascinanti, ma addosso la cosa cambia.",
    "Li osservo e ne capisco il fascino, ma indossati il giudizio cambia.",
    "Li guardo e ne apprezzo il design, ma addosso il discorso si complica.",
    "Li osservo e ne colgo il valore, ma indossandoli la questione è un'altra.",
    "Li guardo e ne riconosco il fascino, ma addosso la resa è diversa.",
    "Li osservo e ne apprezzo l'estetica, ma portati la cosa cambia.",
    "Li guardo e ne vedo il potenziale, ma addosso il discorso è un altro.",
    "Li osservo e ne capisco il valore estetico, ma indosso la resa cambia.",
    "Li guardo e ne apprezzo la bellezza, ma addosso il racconto è diverso.",
    "Li osservo e ne colgo il fascino visivo, ma portati il discorso muta.",
    "Li guardo e ne vedo il design, ma addosso tutto si trasforma.",
    "Li osservo e li trovo belli, ma indossandoli il giudizio si sposta.",
    "Li guardo e ne apprezzo l'idea, ma addosso la realtà è diversa.",
    "Li osservo e ne capisco il fascino, ma la resa addosso è un'altra cosa.",
],

"Io parto sempre malissimo con i modelli troppo caratterizzati.": [
    "Io di solito inizio male con i modelli troppo caratterizzati.",
    "Il mio approccio iniziale con i modelli molto caratterizzati è sempre diffidente.",
    "Parto sempre con diffidenza verso i modelli troppo marcati.",
    "Il mio primo impatto con i modelli molto caratterizzati è sempre critico.",
    "Io inizio sempre con scetticismo quando i modelli sono troppo marcati.",
    "Parto sempre in salita con i modelli troppo spiccati.",
    "Il mio approccio iniziale ai modelli troppo caratterizzati è sempre freddo.",
    "Io di solito non parto bene con i modelli molto marcati.",
    "Parto sempre con riserva verso i modelli troppo caratterizzati.",
    "Il mio primo approccio ai modelli molto caratterizzati è sempre cauto.",
    "Io inizio sempre con perplessità verso i modelli troppo marcati.",
    "Parto sempre con diffidenza quando un modello è molto caratterizzato.",
    "Il mio rapporto iniziale con i modelli troppo spiccati è sempre difficile.",
    "Io di solito non mi trovo subito con i modelli troppo marcati.",
    "Parto sempre con scetticismo verso i modelli troppo caratterizzati.",
    "Il mio primo impatto con i modelli troppo marcati è quasi sempre negativo.",
    "Io di solito ho un approccio difficile con i modelli troppo caratterizzati.",
    "Parto sempre con cautela estrema verso i modelli molto marcati.",
    "Il mio rapporto con i modelli troppo caratterizzati inizia sempre male.",
    "Io di solito fatico inizialmente con i modelli troppo spiccati.",
],

"Per quanto mi riguarda, strada interrotta quasi subito.": [
    "Per me, percorso finito quasi subito.",
    "Per quanto mi riguarda, esperienza conclusa in fretta.",
    "Per me, rapporto interrotto molto presto.",
    "Per quanto mi riguarda, il percorso si è fermato quasi subito.",
    "Per me, la strada si è chiusa quasi immediatamente.",
    "Per quanto mi riguarda, esperienza breve e finita.",
    "Per me, il rapporto si è interrotto presto.",
    "Per quanto mi riguarda, la storia è finita quasi subito.",
    "Per me, percorso brevissimo e concluso.",
    "Per quanto mi riguarda, il cammino si è fermato presto.",
    "Per me, esperienza chiusa in tempi rapidi.",
    "Per quanto mi riguarda, il rapporto si è interrotto quasi subito.",
    "Per me, il percorso è stato molto breve.",
    "Per quanto mi riguarda, la strada si è chiusa presto.",
    "Per me, esperienza conclusa quasi immediatamente.",
    "Per quanto mi riguarda, il rapporto si è chiuso presto.",
    "Per me, strada chiusa in fretta.",
    "Per quanto mi riguarda, percorso interrotto molto presto.",
    "Per me, la storia si è conclusa quasi subito.",
    "Per quanto mi riguarda, il cammino si è interrotto in fretta.",
],

"Peccato, perché il potenziale c'era e si vede ancora.": [
    "Un peccato, perché il potenziale è evidente.",
    "Peccato, perché le premesse c'erano e si vedono.",
    "Un vero peccato, perché il potenziale è lì da vedere.",
    "Peccato, perché la potenzialità era ed è visibile.",
    "Un peccato, perché il potenziale è chiaro a tutti.",
    "Peccato, perché le potenzialità ci sono e si notano.",
    "Un vero peccato, perché il potenziale non manca.",
    "Peccato, perché il materiale per fare bene c'era.",
    "Un peccato, perché il potenziale è sotto gli occhi di tutti.",
    "Peccato, perché le qualità di base ci sono e si vedono.",
    "Un vero peccato, perché il potenziale era lì.",
    "Peccato, perché la base per fare meglio c'è.",
    "Un peccato, perché il potenziale è innegabile.",
    "Peccato, perché le premesse per un grande paio c'erano.",
    "Un vero peccato, perché il potenziale si vede chiaramente.",
    "Peccato, perché la materia prima per eccellere c'è.",
    "Un peccato, perché il potenziale è tangibile.",
    "Peccato, perché le basi per qualcosa di grande ci sono.",
    "Un vero peccato, perché la potenzialità è evidente.",
    "Peccato, perché le doti per fare meglio si vedono.",
],

"Mi ha dato subito fiducia anche senza bisogno di abituarmi. Quando un modello continua a convincermi dopo più uscite, per me ha già vinto.": [
    "Mi ha ispirato fiducia fin dal primo momento, senza bisogno di adattamento. Quando un modello convince anche dopo molte uscite, per me è un vincitore.",
    "Mi ha dato sicurezza subito, senza necessità di abituarmi. Se un modello tiene dopo tante uscite, per me è vincente.",
    "Mi ha ispirato fiducia dal primo utilizzo, senza periodo di adattamento. Un modello che convince nel tempo ha già vinto.",
    "Mi ha dato certezza fin da subito, senza bisogno di rodaggio. Quando un modello regge dopo molte uscite, per me il giudizio è chiuso.",
    "Mi ha ispirato fiducia immediata, senza fase di adattamento. Se un modello continua a convincere dopo tanti utilizzi, per me è promosso.",
    "Mi ha dato sicurezza dal primo giorno, senza necessità di abituarmi. Un modello che tiene nel tempo ha già dimostrato tutto.",
    "Mi ha ispirato fiducia subito, senza bisogno di un periodo di prova. Se continua a piacermi dopo molte uscite, il verdetto è positivo.",
    "Mi ha dato certezza immediata, senza adattamento necessario. Quando un paio convince nel tempo, il giudizio è netto.",
    "Mi ha ispirato fiducia dal primo momento, senza bisogno di adattarmi. Se regge dopo molte uscite, per me ha vinto.",
    "Mi ha dato sicurezza fin dalla prima indossata, senza fase di rodaggio. Un modello che resiste nel tempo ha già dimostrato il suo valore.",
    "Mi ha ispirato fiducia immediata, senza necessità di periodo di prova. Se continua a convincermi dopo tante uscite, per me ha vinto.",
    "Mi ha dato certezza fin da subito, senza bisogno di fase di adattamento. Un paio che tiene nel tempo è per me un vincitore.",
    "Mi ha ispirato fiducia dal primo utilizzo, senza tempo di adattamento. Quando un paio continua a piacermi dopo molte uscite, per me è un successo.",
],

"Li tengo, però non sono quelli che mi vengono in mente per primi.": [
    "Li conservo, ma non sono i primi a cui penso.",
    "Li tengo, ma non sono la mia prima scelta.",
    "Li conservo, ma non sono quelli che cerco per primi.",
    "Li tengo, ma non sono i primi che mi vengono in mente.",
    "Li conservo, ma non sono i primi che afferro quando devo uscire.",
    "Li tengo, ma nella mia rotazione non sono in cima.",
    "Li conservo, ma non sono la prima opzione che considero.",
    "Li tengo, ma non sono quelli a cui penso per primi.",
    "Li conservo, ma non sono i primi che scelgo.",
    "Li tengo, ma nella mia mente non sono in prima fila.",
    "Li conservo, ma non sono quelli che mi vengono naturali come prima scelta.",
    "Li tengo, ma non sono i primi della lista mentale.",
    "Li conservo, ma non sono i prediletti nella rotazione.",
    "Li tengo, ma non sono quelli che cerco istintivamente.",
    "Li conservo, ma nell'ordine delle preferenze non sono in cima.",
    "Li tengo, ma non sono il primo paio che scelgo al mattino.",
    "Li conservo, ma non sono quelli che mi vengono spontanei.",
    "Li tengo, ma nella gerarchia dei miei paia non sono ai vertici.",
    "Li conservo, ma non sono la prima scelta naturale.",
    "Li tengo, ma non sono i primi che mi passano per la testa.",
],

"la delicatezza percepita è parte del fascino ma anche del limite.": [
    "la fragilità percepita è parte del fascino ma anche del limite.",
    "la percezione di delicatezza è un punto di fascino e limite insieme.",
    "la fragilità che si percepisce è fascino e limite allo stesso tempo.",
    "la sensazione di delicatezza è sia attrattiva che limitante.",
    "la delicatezza percepita è un punto di forza e di debolezza.",
    "la fragilità apparente è parte del suo fascino e del suo limite.",
    "la percezione di delicatezza è sia il suo pregio che il suo difetto.",
    "la delicatezza che si avverte è fascino e limite in parti uguali.",
    "la sensazione di fragilità è attrattiva e preoccupante insieme.",
    "la delicatezza è il suo fascino e allo stesso tempo il suo tallone d'Achille.",
    "la fragilità percepita è sia un punto di bellezza che un punto debole.",
    "la delicatezza è parte del suo fascino ma anche una nota di cautela.",
    "la sensazione di fragilità è il suo pregio e il suo limite.",
    "la delicatezza percepita è il suo fascino e la sua vulnerabilità.",
    "la percezione di fragilità è attraente e preoccupante insieme.",
    "la delicatezza è un aspetto affascinante che però diventa anche limite.",
    "la fragilità percepita è tanto fascino quanto preoccupazione.",
    "la sensazione di delicatezza è un'arma a doppio taglio: fascino e limite.",
    "la delicatezza è il suo pregio estetico e il suo potenziale punto debole.",
    "la fragilità che si percepisce è sia il suo fascino che la sua debolezza.",
],

}
