#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Dizionario PATTERN -> ALTERNATIVE (Parte 17: ultimi residui significativi)"""

CLEANUP_PATTERNS = {

"Per me è uno di quei rari acquisti che restano nel tempo.": [
    "Per me è uno di quegli acquisti che non si dimenticano.",
    "Per me rientra tra quegli acquisti destinati a durare.",
    "Per me è un acquisto che resiste alla prova del tempo.",
    "Per me è uno di quei rari acquisti che ti accompagnano davvero.",
    "Per me è uno di quegli acquisti che continuano a dare soddisfazione.",
    "Per me è il tipo di acquisto che non invecchia.",
    "Per me è uno di quegli acquisti che diventano un punto fermo.",
    "Per me è uno di quei rari acquisti che restano rilevanti.",
    "Per me fa parte di quegli acquisti che invecchiano bene.",
    "Per me è un acquisto che tiene nel tempo senza perdere valore.",
    "Per me rientra tra quegli acquisti che non smettono di convincere.",
    "Per me è uno di quegli acquisti che migliorano col passare delle settimane.",
    "Per me è uno di quei rari acquisti che non si rimpiangono.",
    "Per me è il tipo di acquisto che conferma la scelta nel tempo.",
    "Per me rientra tra quegli acquisti che continuano a crescere.",
    "Per me è uno di quegli acquisti destinati a restare nella rotazione.",
    "Per me è un acquisto che mantiene le promesse nel tempo.",
    "Per me è uno di quegli acquisti che restano importanti.",
],

"Alla fine li metto poco proprio per questo.": [
    "Alla fine li indosso raramente proprio per questo motivo.",
    "Alla fine li uso poco proprio per questa ragione.",
    "Alla fine finiscono per restare nel cassetto proprio per questo.",
    "Alla fine li porto raramente proprio per questo.",
    "Alla fine li scelgo poco, proprio per questo motivo.",
    "Alla fine li indosso con parsimonia proprio per questo.",
    "Alla fine restano al loro posto più di quanto vorrei.",
    "Alla fine li tiro fuori poco, e il motivo è esattamente questo.",
    "Alla fine li metto meno di quanto pensassi, proprio per questo.",
    "Alla fine restano nella custodia più del previsto per questo motivo.",
    "Alla fine li indosso meno di quanto meriterebbero, proprio per questo.",
    "Alla fine li uso con meno frequenza del previsto.",
    "Alla fine li scelgo raramente, e il motivo è questo.",
    "Alla fine restano poco nella rotazione proprio per questo.",
    "Alla fine li porto meno di quanto avrei voluto.",
    "Alla fine li metto di rado, proprio per questa ragione.",
    "Alla fine finiscono per restare più fermi che addosso.",
    "Alla fine li indosso poco, e la ragione è esattamente questa.",
],

"in un contesto molto più normale di quanto il design farebbe pensare, e": [
    "in un contesto molto più quotidiano di quanto il design suggerisca, e",
    "in una situazione molto più ordinaria di quanto il design lasci intendere, e",
    "in un contesto molto più semplice di quanto il design farebbe immaginare, e",
    "in un ambiente molto più normale di quanto il design suggerisca, e",
    "in un contesto ben più quotidiano di quanto il design prometta, e",
    "in una cornice molto più sobria di quanto il design farebbe credere, e",
    "in un contesto decisamente più normale di quanto il design suggerisca, e",
    "in un ambiente ben più ordinario di quanto il design lasci pensare, e",
    "in un contesto molto più tranquillo di quanto il design suggerisca, e",
    "in una situazione molto più normale di quanto il design farebbe supporre, e",
    "in un contesto più sobrio di quanto il design prometta, e",
    "in un ambiente decisamente più quotidiano di quanto il design suggerisca, e",
    "in un contesto molto più rilassato di quanto il design lasci immaginare, e",
    "in ogni contesto molto più normale di quanto il design faccia intuire, e",
    "in un ambiente molto più ordinario di quanto il design suggerirebbe, e",
    "in un contesto assai più semplice di quanto il design farebbe intendere, e",
    "in una situazione decisamente più sobria di quanto il design suggerisca, e",
    "in un contesto molto più concreto di quanto il design farebbe pensare, e",
],

"mi aveva incuriosito parecchio. Dal vivo però": [
    "mi aveva attirato molto. Nella realtà però",
    "mi aveva intrigato non poco. Di persona però",
    "mi aveva colpito parecchio. Dal vivo però",
    "mi aveva incuriosito molto. Nella pratica però",
    "mi aveva interessato parecchio. Provandolo però",
    "mi aveva attirato parecchio. Di persona però",
    "mi aveva fatto una buona impressione. Dal vivo però",
    "mi aveva stuzzicato parecchio. Nella realtà però",
    "mi aveva convinto sulla carta. Di persona però",
    "mi aveva colpito molto. Provandolo però",
    "mi aveva intrigato parecchio. Nella pratica però",
    "mi aveva ispirato fiducia. Dal vivo però",
    "mi aveva attirato non poco. Provandolo però",
    "mi aveva fatto venire voglia di provarli. Di persona però",
    "mi aveva stuzzicato molto. Nella realtà però",
    "mi aveva colpito in foto. Dal vivo però",
    "mi aveva entusiasmato. Provandolo però",
    "mi aveva conquistato sulla carta. Nella pratica però",
],

"Mi sono piaciuti diversi aspetti — soprattutto": [
    "Ho apprezzato diversi aspetti — in particolare",
    "Mi hanno convinto molti aspetti — soprattutto",
    "Ho trovato interessanti diversi punti — in particolare",
    "Mi hanno colpito diversi aspetti — soprattutto",
    "Ho apprezzato molti elementi — in particolare",
    "Mi sono piaciuti diversi elementi — soprattutto",
    "Ho trovato convincenti diversi aspetti — in particolare",
    "Mi ha colpito più di un aspetto — soprattutto",
    "Ho notato con piacere diversi aspetti — in particolare",
    "Mi hanno conquistato diversi dettagli — soprattutto",
    "Ho apprezzato parecchi aspetti — in particolare",
    "Mi hanno colpito in positivo diversi punti — soprattutto",
    "Ho trovato meritevoli diversi aspetti — in particolare",
    "Mi hanno interessato diversi aspetti — soprattutto",
    "Ho trovato apprezzabili diversi elementi — in particolare",
    "Mi hanno fatto una buona impressione diversi aspetti — soprattutto",
    "Ho trovato validi diversi aspetti — in particolare",
    "Mi hanno convinto diversi dettagli — soprattutto",
],

"Non pensavo mi sarebbero piaciuti così, temevo che": [
    "Non credevo mi avrebbero conquistato, temevo che",
    "Non pensavo mi avrebbero convinto così tanto, avevo paura che",
    "Non immaginavo che mi sarebbero piaciuti, temevo che",
    "Non credevo avrebbero funzionato su di me, temevo che",
    "Non pensavo me ne sarei innamorato, avevo il timore che",
    "Non immaginavo mi avrebbero conquistato, temevo che",
    "Non credevo sarebbero stati così piacevoli, temevo che",
    "Non pensavo mi avrebbero convinto, avevo paura che",
    "Non immaginavo sarebbero diventati così graditi, temevo che",
    "Non credevo mi sarebbero piaciuti tanto, avevo il dubbio che",
    "Non pensavo mi avrebbero colpito così, temevo che",
    "Non immaginavo mi avrebbero entusiasmato, avevo paura che",
    "Non credevo avrebbero avuto questo effetto su di me, temevo che",
    "Non pensavo mi avrebbero sorpreso così, avevo il timore che",
    "Non immaginavo mi sarebbero piaciuti a questo punto, temevo che",
    "Non credevo sarebbero stati così convincenti, temevo che",
    "Non pensavo mi avrebbero lasciato così soddisfatto, temevo che",
    "Non immaginavo avrebbero funzionato così bene, temevo che",
],

"il verde salvia non perdona tutti gli abbinamenti.": [
    "il verde salvia richiede attenzione negli abbinamenti.",
    "il verde salvia limita un po' le combinazioni possibili.",
    "il verde salvia non si abbina a tutto con facilità.",
    "il verde salvia chiede abbinamenti pensati.",
    "il verde salvia non è il colore più versatile negli abbinamenti.",
    "il verde salvia richiede un po' di cura nel coordinamento.",
    "il verde salvia non si adatta a qualsiasi outfit.",
    "il verde salvia limita le possibilità di abbinamento.",
    "il verde salvia richiede un guardaroba compatibile.",
    "il verde salvia non è universale negli abbinamenti.",
    "il verde salvia chiede un minimo di attenzione nel vestirsi.",
    "il verde salvia non è il più facile da abbinare.",
    "il verde salvia restringe un po' il campo degli abbinamenti.",
    "il verde salvia richiede outfit compatibili.",
    "il verde salvia limita la libertà di abbinamento.",
    "il verde salvia non è il colore più adattabile.",
    "il verde salvia chiede una certa cura nel look.",
    "il verde salvia non si sposa con tutto indistintamente.",
],

"se il naso non lo accoglie bene tende a scivolare.": [
    "se il ponte nasale non è compatibile tende a scivolare.",
    "se il naso non lo supporta bene può risultare instabile.",
    "se la forma del naso non è quella giusta tende a scivolare.",
    "se il ponte nasale non è adatto può perdere stabilità.",
    "se il naso non è compatibile rischia di scivolare.",
    "se la struttura nasale non è quella giusta può risultare instabile.",
    "se il naso non lo sostiene bene tende a cedere.",
    "se il ponte non è adatto scivola facilmente.",
    "se il naso non è quello giusto rischia di non stare fermo.",
    "se la forma del naso non è quella ideale perde stabilità.",
    "se il ponte nasale non è compatibile può scivolare.",
    "se il naso non lo accoglie correttamente tende a muoversi.",
    "se la struttura del naso non è ideale può risultare instabile.",
    "se il ponte non è adatto alla forma del naso scivola.",
    "se il naso non ha la forma giusta tende a cedere.",
    "se il ponte nasale non si adatta può perdere aderenza.",
    "se il naso non lo trattiene bene rischia di scivolare.",
    "se la forma nasale non è compatibile non resta stabile.",
],

"i riflessi della lente ogni tanto mi distraggono.": [
    "i riflessi delle lenti ogni tanto risultano fastidiosi.",
    "i riflessi sulla lente a volte disturbano la visione.",
    "i riflessi delle lenti possono distrarre in certi momenti.",
    "i riflessi sulla lente ogni tanto infastidiscono.",
    "i riflessi delle lenti a volte catturano l'attenzione in modo indesiderato.",
    "i riflessi sulla lente a tratti mi disturbano.",
    "i riflessi delle lenti di tanto in tanto mi infastidiscono.",
    "i riflessi sulla lente a volte risultano distraenti.",
    "i riflessi delle lenti ogni tanto mi danno fastidio.",
    "i riflessi sulla lente possono essere distraenti.",
    "i riflessi delle lenti a volte mi disorientano.",
    "i riflessi sulla lente ogni tanto mi disturbano.",
    "i riflessi delle lenti possono risultare fastidiosi in certe condizioni.",
    "i riflessi sulla lente a volte catturano troppo l'occhio.",
    "i riflessi delle lenti ogni tanto mi danno noia.",
    "i riflessi sulla lente possono essere un po' invadenti.",
    "i riflessi delle lenti a volte diventano distraenti.",
    "i riflessi sulla lente di tanto in tanto risultano fastidiosi.",
],

"Il potenziale c'era, la resa personale molto meno.": [
    "Il potenziale era evidente, la resa su di me molto meno.",
    "Le premesse c'erano, la resa personale no.",
    "La promessa era buona, il risultato su di me molto meno.",
    "Il potenziale era lì, la resa personale non all'altezza.",
    "Le premesse erano ottime, la resa su di me deludente.",
    "La base era buona, il risultato personale no.",
    "Il potenziale c'era tutto, la resa su di me molto diversa.",
    "Le premesse promettevano bene, la resa personale meno.",
    "La promessa era alta, il risultato su di me basso.",
    "Il potenziale era innegabile, la resa personale no.",
    "Le basi c'erano, la resa su di me non ha seguito.",
    "La promessa era convincente, il risultato personale deludente.",
    "Il potenziale era chiaro, la resa su di me non all'altezza.",
    "Le premesse erano le migliori, la resa personale no.",
    "La base era promettente, la resa su di me molto meno.",
    "Il potenziale non mancava, la resa personale sì.",
    "Le premesse c'erano tutte, la resa su di me non ha convinto.",
    "La promessa era forte, il risultato personale debole.",
],

"Lo capisco, ma non lo vivo con naturalezza.": [
    "Lo comprendo, ma non mi viene naturale portarlo.",
    "Ne capisco il senso, ma non lo vivo con spontaneità.",
    "Lo capisco come progetto, ma non mi risulta naturale.",
    "Ne colgo il valore, ma non lo porto con disinvoltura.",
    "Lo apprezzo razionalmente, ma non lo vivo con naturalezza.",
    "Ne capisco la logica, ma non lo sento spontaneo.",
    "Lo comprendo, ma non riesco a portarlo con naturalezza.",
    "Ne colgo l'idea, ma non mi risulta naturale usarlo.",
    "Lo capisco intellettualmente, ma non lo vivo con spontaneità.",
    "Ne apprezzo il concept, ma non lo porto con disinvoltura.",
    "Lo comprendo come modello, ma non lo sento mio.",
    "Ne capisco il progetto, ma non mi viene spontaneo portarlo.",
    "Lo apprezzo come idea, ma non lo vivo con facilità.",
    "Ne colgo il messaggio, ma non lo porto con naturalezza.",
    "Lo capisco come proposta, ma non lo sento naturale su di me.",
    "Ne comprendo il fascino, ma non riesco a viverlo con spontaneità.",
    "Lo capisco razionalmente, ma non lo porto con disinvoltura.",
    "Ne apprezzo la visione, ma non lo vivo come mio.",
],

"È uno di quei casi in cui l'idea mi piace più dell'esecuzione su di me.": [
    "È uno di quei casi in cui il concept mi piace più della resa sul mio viso.",
    "È una di quelle situazioni in cui l'idea mi attira più del risultato su di me.",
    "È uno di quei casi in cui la teoria mi piace più della pratica personale.",
    "È una di quelle situazioni in cui il concept vince sulla resa reale.",
    "È uno di quei casi in cui l'ispirazione mi piace più del risultato addosso.",
    "È una di quelle situazioni in cui l'idea supera l'esecuzione nel mio caso.",
    "È uno di quei casi in cui il progetto mi piace più della resa personale.",
    "È una di quelle situazioni in cui il concept mi convince più della resa pratica.",
    "È uno di quei casi in cui la visione mi piace più del risultato su di me.",
    "È una di quelle situazioni in cui l'idea è meglio del risultato addosso.",
    "È uno di quei casi in cui il design mi piace più della resa personale.",
    "È una di quelle situazioni in cui il concept supera la resa sul mio viso.",
    "È uno di quei casi in cui la promessa mi piace più del risultato.",
    "È una di quelle situazioni in cui l'idea è più bella della resa pratica.",
    "È uno di quei casi in cui la teoria vince sulla pratica personale.",
    "È una di quelle situazioni in cui il progetto vale più del risultato addosso.",
    "È uno di quei casi in cui l'ispirazione supera la resa nel mio caso.",
    "È una di quelle situazioni in cui il concept mi piace più della realtà.",
],

"La distanza tra aspettativa e resa è stata troppo grande.": [
    "Il divario tra aspettativa e risultato è stato troppo ampio.",
    "La distanza tra ciò che speravo e ciò che ho avuto è stata troppo grande.",
    "Il gap tra aspettativa e resa reale è stato eccessivo.",
    "La differenza tra aspettativa e risultato è stata troppa.",
    "Il divario tra speranza e realtà è stato troppo ampio.",
    "La distanza tra ciò che immaginavo e ciò che è stato è stata eccessiva.",
    "Il gap tra promessa e resa è stato troppo grande.",
    "La differenza tra aspettativa e realtà è stata considerevole.",
    "Il divario tra ciò che pensavo e ciò che ho trovato è stato troppo.",
    "La distanza tra immaginazione e realtà è stata eccessiva.",
    "Il gap tra attesa e risultato è stato troppo ampio.",
    "La differenza tra ciò che speravo e ciò che ho ottenuto è stata troppa.",
    "Il divario tra aspettativa e realtà è stato troppo marcato.",
    "La distanza tra previsione e resa è stata eccessiva.",
    "Il gap tra aspettativa e risultato concreto è stato troppo ampio.",
    "La differenza tra immaginazione e resa è stata troppo grande.",
    "Il divario tra speranza e risultato è stato eccessivo.",
    "La distanza tra teoria e pratica è stata troppo ampia.",
],

"La bellezza da sola non mi compensa l'attrito quotidiano.": [
    "La bellezza da sola non basta a compensare il disagio nell'uso.",
    "L'estetica da sola non compensa la scomodità quotidiana.",
    "La bellezza non è sufficiente a giustificare l'attrito nell'uso.",
    "L'estetica non basta a compensare i problemi quotidiani.",
    "La bellezza da sola non ripaga il fastidio nell'uso di ogni giorno.",
    "L'estetica non compensa la mancanza di comfort quotidiano.",
    "La bellezza da sola non bilancia l'attrito nell'uso.",
    "L'estetica non basta a giustificare il disagio quotidiano.",
    "La bellezza da sola non compensa i problemi pratici.",
    "L'estetica non ripaga la difficoltà d'uso quotidiano.",
    "La bellezza da sola non bilancia la scomodità nell'uso.",
    "L'estetica non basta quando il comfort manca nel quotidiano.",
    "La bellezza da sola non giustifica l'attrito pratico.",
    "L'estetica non compensa la fatica d'uso di tutti i giorni.",
    "La bellezza da sola non basta se l'uso è problematico.",
    "L'estetica non ripaga i piccoli fastidi quotidiani.",
    "La bellezza da sola non bilancia il disagio pratico.",
    "L'estetica non compensa le frizioni d'uso quotidiano.",
],

"Anche sforzandomi di dargli una seconda occasione, il risultato non cambia.": [
    "Anche provando a dargli un'altra possibilità, il risultato resta lo stesso.",
    "Anche impegnandomi a dargli una seconda chance, le cose non cambiano.",
    "Anche sforzandomi di riprovarlo, il risultato è invariato.",
    "Anche provando a insistere, il risultato non si modifica.",
    "Anche dandogli un'altra opportunità, la conclusione resta la stessa.",
    "Anche sforzandomi di riconsiderarli, il giudizio non cambia.",
    "Anche provando a dargli tempo, il risultato è lo stesso.",
    "Anche impegnandomi a rivalutarli, il verdetto resta invariato.",
    "Anche sforzandomi di vederli con occhi diversi, nulla cambia.",
    "Anche provando a insistere con buona volontà, il risultato è identico.",
    "Anche dandogli ulteriore fiducia, il risultato non si muove.",
    "Anche sforzandomi di apprezzarli, il giudizio resta fermo.",
    "Anche provando a riconsiderarli, la situazione non migliora.",
    "Anche dandogli un'altra occasione, il verdetto resta lo stesso.",
    "Anche impegnandomi a insistere, il risultato non cambia direzione.",
    "Anche sforzandomi di dargli un'altra chance, il risultato è uguale.",
    "Anche provando a rivalutarli, le cose non si spostano.",
    "Anche dandogli tempo extra, il giudizio resta invariato.",
],

}
