#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Parte 4: Pattern residui ad alta frequenza (frasi di chiusura e interne ripetute)
"""
from rewrite_reviews_part3 import PATTERNS

# ═══════════════════════════════════════════════════════════
# FRASI DI APERTURA / INTERNE RIPETUTE
# ═══════════════════════════════════════════════════════════

# "Ci sono diversi elementi riusciti" (78x) — interno, apre elenco pregi
_ci_sono = [
    "Tra i punti di forza trovo",
    "Non mancano aspetti convincenti:",
    "Il modello ha dalla sua diversi pregi:",
    "I tratti positivi sono vari:",
    "Diversi aspetti parlano a favore:",
    "Il modello mostra vari punti di qualità:",
    "I meriti sono più d'uno:",
    "Non si può negare che abbia frequenti punti di forza:",
    "L'elenco dei lati positivi comprende",
    "Tra i pregi individuo",
    "Il bilancio dei pregi include",
    "Di elementi validi ne trovo vari:",
    "La lista dei meriti è lunga:",
    "I punti di luce sono molteplici:",
    "Ho contato diversi aspetti riusciti:",
    "Il catalogo dei pregi comprende",
    "Le cose fatte bene sono più d'una:",
    "Non mancano i dettagli convincenti:",
    "I motivi di apprezzamento sono svariati:",
    "Gli aspetti che funzionano sono vari:",
    "Ho trovato diversi punti che meritano una menzione:",
    "Fra gli aspetti riusciti trovo",
    "Il modello porta con sé diversi pregi:",
    "Ci sono parecchi aspetti meritevoli:",
    "I punti di forza non mancano:",
    "Gli elementi ben riusciti sono vari:",
    "Il terreno dei pregi è ampio:",
    "Le qualità concrete che riconosco sono:",
    "Diversi dettagli giocano a suo favore:",
    "Tra le cose che apprezzo:",
    "I suoi argomenti a favore includono",
    "Sul piano dei pregi trovo",
    "Gli aspetti che mi hanno colpito includono",
    "Il modello ha più di un punto a favore:",
    "Di argomenti validi ne ha:",
    "Fra i dettagli riusciti noto",
    "I lati positivi che emergono sono:",
    "Nell'elenco dei pregi trovo",
    "Il ventaglio dei meriti comprende",
    "I punti che funzionano sono svariati:",
    "Gli elementi che parlano bene del modello sono:",
    "I pregi concreti sono vari:",
    "Fra i tratti riusciti riconosco",
    "Il patrimonio dei pregi include",
    "I lati convincenti sono diversi:",
    "Non posso non riconoscere vari punti di forza:",
    "Tra i meriti più evidenti:",
    "Di qualità ne mostra diverse:",
    "La mappa dei pregi è ricca:",
    "I punti di forza si articolano in modo vario:",
    "Gli aspetti positivi che registro sono:",
    "Fra i dettagli riusciti spicca",
    "Riconosco diversi aspetti pregevoli:",
    "Il modello si distingue per vari elementi:",
    "Tra le note positive:",
    "L'inventario dei pregi comprende",
    "I motivi per cui lo apprezzo sono vari:",
    "Di buoni argomenti ne conta diversi:",
    "Gli aspetti meritevoli sono molti:",
    "Fra i tratti che funzionano:",
    "Il quadro dei pregi include",
    "I dettagli convincenti sono vari:",
    "Non banalizzando, i punti di forza sono:",
    "Le frecce al suo arco includono",
    "I tratti che meritano una menzione:",
    "Il pacchetto di pregi comprende",
    "Gli elementi riusciti sono svariati:",
    "Tra i punti di merito trovo",
    "L'insieme dei pregi include",
    "Di lati convincenti ne riconosco diversi:",
    "Gli aspetti validi che emergono sono:",
    "Il mosaico dei pregi comprende",
    "I dettagli pregevoli sono vari:",
    "Nell'analisi dei punti di forza trovo",
    "Le qualità che emergono sono:",
    "Il registro dei meriti include",
    "Gli aspetti che conquistano sono più d'uno:",
    "Fra i dettagli meritevoli:",
]
PATTERNS["Ci sono diversi elementi riusciti:"] = _ci_sono[:78]
PATTERNS["Ci sono diversi elementi riusciti"] = _ci_sono[:78]

# "Mi piace abbastanza da usarlo davvero." (55x) — voto 4-star valutazione
_mi_piace = [
    "Mi soddisfa a tal punto da portarlo regolarmente.",
    "Lo apprezzo abbastanza da avergli trovato un posto fisso.",
    "Mi convince quanto basta per indossarlo senza esitare.",
    "Lo gradisco abbastanza da non lasciarlo nel cassetto.",
    "Mi piace a sufficienza per includerlo nella mia rotazione.",
    "Lo trovo piacevole al punto da usarlo con frequenza.",
    "Lo apprezzo quanto basta da non trascurarlo.",
    "Mi lascia abbastanza soddisfatto da continuare a metterlo.",
    "Mi convince al punto da sceglierlo spesso.",
    "Lo gradisco a sufficienza per dargli spazio reale.",
    "Mi piace al punto da portarlo fuori senza ripensamenti.",
    "Lo apprezzo abbastanza da dargli fiducia continuativa.",
    "Mi fa un effetto abbastanza positivo da usarlo senza riserve.",
    "Mi piace a tal punto da averlo nella rosa dei preferiti.",
    "Lo apprezzo quanto basta per averlo sempre a portata di mano.",
    "Mi convince abbastanza da portarlo con continuità.",
    "Lo gradisco al punto da utilizzarlo concretamente.",
    "Mi soddisfa al livello giusto per portarlo volentieri.",
    "Lo apprezzo abbastanza da sceglierlo senza forzature.",
    "Mi piace a sufficienza per averlo nella mia selezione attiva.",
    "Lo trovo gradevole abbastanza da dargli un ruolo costante.",
    "Mi piace quanto basta per non lasciarlo a prendere polvere.",
    "Lo apprezzo al livello che mi fa portarlo con regolarità.",
    "Mi convince abbastanza da averlo tra i miei abituali.",
    "Lo gradisco al punto da usarlo senza dovermi convincere.",
    "Mi piace abbastanza da farlo diventare una scelta frequente.",
    "Lo apprezzo a sufficienza da avergli dato un posto stabile.",
    "Mi soddisfa quanto basta da usarlo nella vita di tutti i giorni.",
    "Lo apprezzo abbastanza da portarlo senza pensarci due volte.",
    "Mi piace al punto da non doverlo giustificare.",
    "Lo gradisco abbastanza da averlo nella mia rotazione attiva.",
    "Mi convince quanto basta per averlo tra i miei occhiali di riferimento.",
    "Mi piace al livello giusto per dargli credito con l'uso vero.",
    "Lo apprezzo a sufficienza per averlo in prima fila.",
    "Mi soddisfa abbastanza da portarlo con convinzione.",
    "Lo apprezzo quanto basta perché lo uso davvero.",
    "Mi piace al punto giusto per non relegarlo in fondo al cassetto.",
    "Mi convince abbastanza da indossarlo con piacere.",
    "Lo apprezzo a sufficienza per portarlo con continuità.",
    "Mi piace al punto da essere diventato una scelta reale.",
    "Mi soddisfa quanto basta per indossarlo senza ripensamento.",
    "Lo apprezzo abbastanza da averlo nella rosa delle scelte attive.",
    "Mi convince al livello giusto per dargli spazio vero.",
    "Lo gradisco abbastanza per portarlo regolarmente.",
    "Mi piace quanto basta per averlo come scelta abituale.",
    "Lo apprezzo al punto da portarlo senza bisogno di scuse.",
    "Mi convince a sufficienza per inserirlo nella mia selezione.",
    "Lo gradisco al punto giusto per non abbandonarlo.",
    "Mi piace al livello in cui un occhiale diventa davvero usato.",
    "Lo apprezzo abbastanza da averlo come opzione costante.",
    "Mi soddisfa al punto da indossarlo con naturalezza.",
    "Lo apprezzo quanto basta per portarlo fuori senza esitare.",
    "Mi convince abbastanza da dargli un ruolo effettivo nel quotidiano.",
    "Lo gradisco a sufficienza per usarlo come scelta primaria.",
    "Mi piace al livello giusto per portarlo senza doverci pensare.",
]
PATTERNS["Mi piace abbastanza da usarlo davvero."] = _mi_piace

# "Quello che vedo lo apprezzo" (35x) — interno (spesso prima di "ma")
_quello_che_vedo = [
    "Il valore che riconosco lo rispetto",
    "Le qualità visibili le apprezzo",
    "Ciò che percepisco mi piace",
    "Gli aspetti che noto li stimo",
    "Quello che emerge mi soddisfa",
    "I tratti che osservo mi convincono",
    "La parte che vedo mi convince",
    "Ciò che riesco a cogliere lo apprezzo",
    "I dettagli che noto parlano bene",
    "La resa che percepisco è positiva",
    "Gli elementi visibili li trovo validi",
    "Quello che osservo mi lascia soddisfatto",
    "La parte evidente mi piace",
    "Ciò che emerge alla vista lo trovo buono",
    "I tratti che noto sono apprezzabili",
    "Quello che percepisco mi dà buone sensazioni",
    "Gli aspetti che colgo parlano a favore",
    "La resa visiva mi soddisfa",
    "Ciò che rilevo mi convince",
    "I dettagli che colgo sono positivi",
    "Quello che affiora mi piace",
    "Le qualità percepibili le apprezzo tutte",
    "Ciò che emerge lo trovo convincente",
    "I tratti che riscontro sono buoni",
    "Quello che si vede lo apprezzo sinceramente",
    "La parte tangibile mi convince",
    "Ciò che osservo mi fa buona impressione",
    "Gli aspetti evidenti li trovo riusciti",
    "Quello che noto superficialmente è promettente",
    "Le qualità che percepisco mi piacciono",
    "Ciò che emerge alla prova lo stimo",
    "I dettagli visibili mi convincono",
    "La resa che noto è apprezzabile",
    "Ciò che colgo mi parla positivamente",
    "Gli elementi che osservo li trovo validi",
]
PATTERNS["Quello che vedo lo apprezzo"] = _quello_che_vedo

# ═══════════════════════════════════════════════════════════
# CHIUSURE 5 STELLE
# ═══════════════════════════════════════════════════════════

# "Ogni volta che lo rimetto trovo un dettaglio nuovo da apprezzare." (35x)
_ogni_volta = [
    "Ad ogni utilizzo scopro un aspetto che prima mi era sfuggito.",
    "Più lo indosso, più trovo sfumature che mi piacciono.",
    "Continuo a trovare nuovi motivi per apprezzarlo.",
    "L'apprezzamento cresce un po' a ogni uscita.",
    "Ogni utilizzo aggiunge un tassello al mio giudizio positivo.",
    "A ogni indossata emerge un nuovo dettaglio da segnalare.",
    "Non smette di rivelare qualcosa di nuovo a ogni utilizzo.",
    "L'uso ripetuto continua a premiare con piccole scoperte.",
    "Più lo porto, più trovo ragioni per confermarlo.",
    "La ricchezza dei dettagli si rivela gradualmente a ogni uscita.",
    "Ogni volta che lo prendo in mano noto qualcosa di nuovo.",
    "Il modello continua a offrire sorprese positive nel tempo.",
    "Più lo uso, più scopro lati che prima non avevo colto.",
    "A ogni utilizzo i dettagli continuano a raccontarmi qualcosa.",
    "L'esperienza si arricchisce visita dopo visita.",
    "Non finisce di sorprendermi con piccoli dettagli ben pensati.",
    "Ogni uscita aggiunge una nota positiva in più.",
    "Non mi stanco di trovare nuovi aspetti da apprezzare.",
    "A ogni indossata la stima cresce un po'.",
    "Più lo frequento, più trovo ragioni per confermarne la scelta.",
    "L'uso continuativo rivela una profondità che non immaginavo.",
    "A ogni prova scopro un nuovo lato che mi convince.",
    "Il modello ha una ricchezza che si svela con l'uso.",
    "Più passa il tempo, più lo apprezzo nei dettagli.",
    "L'uso ripetuto non fa che confermare la prima buona impressione.",
    "Ha quel genere di complessità che si rivela solo nel tempo.",
    "Ogni volta aggiungo un motivo alla lista dei pregi.",
    "Il mix di dettagli continua a sorprendere dopo settimane.",
    "Più lo indosso, più cresce la mia considerazione.",
    "Le scoperte continuano anche dopo molte indossate.",
    "A ogni utilizzo trovo un pretesto nuovo per apprezzarlo.",
    "Non si esaurisce in una sola esperienza, anzi cresce.",
    "La stratificazione dei dettagli emerge solo con il tempo.",
    "La sua profondità si rivela indossata dopo indossata.",
    "L'uso continuativo porta sempre nuove conferme.",
]
PATTERNS["Ogni volta che lo rimetto trovo un dettaglio nuovo da apprezzare."] = _ogni_volta

# "Quando un modello continua a convincermi dopo più uscite, per me ha già vinto." (31x)
_quando_modello = [
    "Se dopo diverse uscite resta convincente, per me è un acquisto riuscito.",
    "Un occhiale che regge dopo più prove, nel mio metro, ha già convinto.",
    "La vera conferma arriva con l'uso ripetuto, e qui c'è stata.",
    "Se resiste al giudizio dopo più utilizzi, per me è promosso.",
    "Il fatto che continui a piacermi dopo settimane dice tutto.",
    "Quando il piacere non cala con l'abitudine, vuol dire che funziona.",
    "Se al quinto utilizzo lo scelgo ancora volentieri, è un buon segno definitivo.",
    "La costanza nell'apprezzamento è il mio metro, e qui il test è passato.",
    "Un occhiale che non perde punti con il tempo si è guadagnato il mio rispetto.",
    "Il fatto che non mi stufi è il complimento migliore che posso fargli.",
    "Quando dopo settimane lo scelgo ancora, il verdetto è netto.",
    "La resistenza al tempo è il test definitivo, superato con merito.",
    "Se dopo ripetute indossate lo scelgo ancora, ha vinto la sfida.",
    "Un modello che mantiene il suo fascino con l'uso, per me, è vincente.",
    "Il vero giudizio arriva dopo più uscite, e il suo è positivo.",
    "Un occhiale che supera la prova del tempo nel mio cassetto è già speciale.",
    "Il fatto che lo riprenda sempre volentieri è la prova migliore.",
    "Quando l'apprezzamento cresce anziché calare, il giudizio è scontato.",
    "La conferma arriva quando dopo molteplici utilizzi il piacere resta intatto.",
    "Se non cede alla routine, per me ha centrato l'obiettivo.",
    "Un occhiale che non si consuma col tempo per me è già un successo.",
    "La prova vera è il lungo periodo, e qui il bilancio è netto.",
    "Se dopo tante uscite conserva lo stesso effetto, ha il mio verdetto positivo.",
    "Il fatto che non mi stufi dopo settimane è il segnale più chiaro.",
    "Un modello che supera la prova delle ripetute indossate, nel mio metro, è promosso.",
    "La costanza nella soddisfazione è la conferma che cercavo.",
    "Quando l'abitudine non smorza il piacere, per me il giudizio è chiaro.",
    "Se al decimo utilizzo lo scelgo ancora con convinzione, non serve altro.",
    "La vera misura è il tempo, e qui il verdetto è positivo.",
    "Un occhiale che si conferma uscita dopo uscita merita il massimo credito.",
    "Quando il giudizio migliora nel tempo, il modello ha vinto.",
]
PATTERNS["Quando un modello continua a convincermi dopo pi\u00f9 uscite, per me ha gi\u00e0 vinto."] = _quando_modello

# "Mi viene spontaneo consigliarlo a chi ha il volto giusto." (30x)
_mi_viene = [
    "Lo consiglierei senza esitazione a chi ha i tratti adatti.",
    "Per il viso giusto, è una raccomandazione facile.",
    "Se le proporzioni del viso lo permettono, è un acquisto che suggerisco.",
    "Lo raccomanderei volentieri a chi ha la struttura facciale adatta.",
    "Per chi ha il volto compatibile, lo consiglio senza riserve.",
    "A chi ha i lineamenti giusti, lo suggerirei ad occhi chiusi.",
    "Lo consiglio senza problemi a chi ha il tipo di viso adatto.",
    "Per il volto adatto, è un suggerimento che faccio con convinzione.",
    "Se i lineamenti coincidono, lo raccomanderei senza dubbi.",
    "A chi ha le proporzioni giuste, lo consiglio di cuore.",
    "Lo suggerirei facilmente a chi ha la geometria del viso giusta.",
    "Per il viso compatibile, è un consiglio spontaneo.",
    "Lo raccomando a chi ha la forma del viso adatta senza esitazioni.",
    "A chi ha i tratti giusti, lo consiglio senza pensarci.",
    "Per le proporzioni giuste, lo suggerisco con convinzione.",
    "Lo raccomanderei naturalmente a chi ha i lineamenti compatibili.",
    "Per chi ha il volto adatto, è un consiglio che faccio volentieri.",
    "Lo consiglio con sicurezza a chi ha la struttura adatta.",
    "A chi ha il viso compatibile, lo raccomanderei senza esitazione.",
    "Per il tipo di viso giusto, la raccomandazione viene spontanea.",
    "Lo suggerirei senza forzature a chi ha le proporzioni ideali.",
    "A chi ha i lineamenti adatti, sono il primo a consigliarlo.",
    "Per la struttura del viso giusta, lo raccomando senz'altro.",
    "Lo consiglierei facilmente a chi ha il tipo di faccia compatibile.",
    "Per chi ha la geometria facciale giusta, è un suggerimento facile.",
    "Lo consiglio a cuor leggero a chi ha il viso adatto.",
    "A chi ha i tratti del viso compatibili, lo suggerisco senza remore.",
    "Per il volto giusto, è un consiglio che darei senza esitare.",
    "Lo raccomanderei con naturalezza a chi ha i lineamenti giusti.",
    "A chi ha le proporzioni facciali adatte, lo consiglio volentieri.",
]
PATTERNS["Mi viene spontaneo consigliarlo a chi ha il volto giusto."] = _mi_viene

# "Per me è uno di quei rari acquisti che restano nel tempo." (30x)
_per_me_raro = [
    "Nel mio bilancio è un acquisto destinato a durare.",
    "È il tipo di acquisto che non perde valore col passare dei mesi.",
    "Rientra fra quelle scelte che si confermano nel lungo periodo.",
    "Per me è una di quelle scelte di cui non mi pentirò.",
    "È entrato nella categoria degli acquisti che si rafforzano nel tempo.",
    "Fa parte di quei pochi acquisti che conservano il loro senso.",
    "Nel mio cassetto è destinato a restare a lungo.",
    "È il genere di acquisto che invecchia bene.",
    "Rientra fra le scelte che col tempo si confermano azzeccate.",
    "Per me è un investimento che mantiene le promesse.",
    "Fa parte degli acquisti che continuano a convincermi.",
    "È uno di quei pochi paia destinati a non stufare.",
    "Nel mio percorso di acquisti, questo è di quelli che durano.",
    "Per me è il tipo di acquisto che non passera di moda nel mio cassetto.",
    "Rientra nella categoria degli acquisti solidi e duraturi.",
    "È una scelta che col tempo acquista ancora più senso.",
    "Per me è fra quelli che continueranno a convincermi.",
    "È entrato fra gli acquisti che si consolidano con l'uso.",
    "Nel mio bilancio è una di quelle scelte che reggono.",
    "Per me è il tipo di acquisto che si rafforza col tempo.",
    "Fa parte di quella rara categoria di acquisti che non deludono.",
    "Rientra fra i pochi acquisti che diventano più convincenti nel tempo.",
    "Per me è una scelta destinata a restare confermata.",
    "È il genere di acquisto che dà soddisfazione a lungo termine.",
    "Nel mio panorama di acquisti, è di quelli che restano.",
    "Per me è un acquisto che si consolida settimana dopo settimana.",
    "Fa parte degli acquisti che si migliorano nella memoria.",
    "È fra quelle scelte che nel tempo dimostrano la loro validità.",
    "Per me è un acquisto che continuerà a dare soddisfazione.",
    "Rientra in quella nicchia di scelte che superano il test del tempo.",
]
PATTERNS["Per me \u00e8 uno di quei rari acquisti che restano nel tempo."] = _per_me_raro

# "Mi ha dato subito fiducia anche senza bisogno di abituarmi." (30x)
_fiducia_subito = [
    "Fin dal primo utilizzo mi ha trasmesso sicurezza.",
    "Non ha richiesto alcun rodaggio per convincermi.",
    "La fiducia è nata immediatamente, senza bisogno di adattamento.",
    "Mi ha messo a mio agio dall'inizio senza fasi di assestamento.",
    "Ho provato fiducia immediata, senza periodi di prova mentale.",
    "L'intesa è stata istantanea, senza bisogno di abituarmici.",
    "Da subito mi ha fatto sentire che era la scelta giusta.",
    "Non ho avuto bisogno di tempo per fidarmi di lui.",
    "La confidenza è arrivata al primo utilizzo.",
    "Fin dall'inizio mi ha dato quella sensazione di sicurezza che cerco.",
    "L'adattamento non è stato necessario: funzionava da subito.",
    "La fiducia è scattata senza bisogno di periodi di prova.",
    "Mi ha trasmesso certezza fin dal primo momento.",
    "Non ho avuto quella fase di adattamento che temo sempre.",
    "Il feeling positivo è stato immediato e non ha richiesto abitudine.",
    "Fin da subito ho sentito che potevo fidarmi del modello.",
    "Il periodo di rodaggio, che di solito serve, qui non è stato necessario.",
    "La confidenza è nata istantaneamente, senza fatica.",
    "Non mi ha chiesto tempo per entrare in sintonia.",
    "Dal primo utilizzo la fiducia era già consolidata.",
    "Non ha avuto bisogno di molte prove per convincermi.",
    "La sicurezza che mi ha trasmesso è stata immediata.",
    "L'adattamento è stato nullo: ha funzionato dal primo istante.",
    "La fiducia non ha dovuto costruirsi: era lì fin dall'inizio.",
    "Mi ha dato certezza dal primo contatto, senza progressione.",
    "Non c'è stato bisogno di abituarmi: la fiducia è arrivata subito.",
    "L'intesa immediata ha saltato qualsiasi fase di rodaggio.",
    "Il feeling è stato istantaneo e non ha avuto bisogno di maturare.",
    "Fin dal primo giorno l'ho sentito come una scelta sicura.",
    "La familiarità è stata immediata, come se li avessi già portati.",
]
PATTERNS["Mi ha dato subito fiducia anche senza bisogno di abituarmi."] = _fiducia_subito

# "È uno di quei modelli che stimo più di quanto usi." (35x) — con frase che precede
_stimo_piu = [
    "È il tipo di modello che rispetto intellettualmente ma uso meno del previsto.",
    "Lo apprezzo nella teoria più di quanto lo scelga nella pratica.",
    "Lo stimo per le sue qualità ma non lo prendo abbastanza spesso.",
    "È un modello che ammiro più che indossare.",
    "Lo considero valido ma non quanto basta per usarlo con regolarità.",
    "Ha il mio rispetto, anche se non la mia frequentazione assidua.",
    "Lo ammiro più di quanto lo porti, e questo dice molto.",
    "Ha valore, anche se non riesce a entrare nella mia rotazione abituale.",
    "Lo apprezzo razionalmente senza riuscire a indossarlo con costanza.",
    "Col cuore lo promuovo, col cassetto lo uso meno di quanto meriti.",
    "Lo stimo come prodotto pur non trovando abbastanza occasioni per portarlo.",
    "La stima c'è, l'utilizzo meno di quanto vorrei.",
    "Lo rispetto più di quanto lo scelga quotidianamente.",
    "Ha merito, anche se il mio uso reale non lo riflette del tutto.",
    "Lo giudico bene ma lo tiro fuori meno di quanto dovrei.",
    "La mia opinione è più alta del mio tasso di utilizzo.",
    "Lo valuto positivamente pur non indossandolo quanto vorrei.",
    "Ha la mia stima, non sempre il mio sguardo quando apro il cassetto.",
    "Lo considero meritevole pur non dandogli tutto lo spazio che meriterebbe.",
    "Il giudizio è più alto della frequenza d'uso.",
    "Lo promuovo intellettualmente pur non sceglierlo ogni mattina.",
    "Ha guadagnato il mio rispetto più che il mio uso quotidiano.",
    "Lo porto meno di quanto lo stimi, e questa è la mia perplessità.",
    "Il gap tra stima e utilizzo racconta la storia di questo modello.",
    "Lo apprezzo oggettivamente senza tradurlo in scelta costante.",
    "Ha tutti i requisiti che apprezzo ma non diventa un abitudinario.",
    "Lo stimo per ciò che è, anche se lo uso meno del previsto.",
    "Ha il mio plauso più che il mio utilizzo effettivo.",
    "La mia ammirazione supera il mio tasso reale di indossamento.",
    "Lo riconosco come valido, anche se il cassetto dice diversamente.",
    "Ha le mie lodi ma non tutto il mio tempo.",
    "Lo stimo come progetto più di quanto riesca a usarlo.",
    "Il mio giudizio è più generoso del mio uso pratico.",
    "Lo apprezzo con la mente più che con l'abitudine.",
    "Ha valore per me, anche se non lo traduco in frequenza.",
]
PATTERNS["\u00c8 uno di quei modelli che stimo pi\u00f9 di quanto usi."] = _stimo_piu

# ═══════════════════════════════════════════════════════════
# CHIUSURE CON RISERVE / 4-STAR
# ═══════════════════════════════════════════════════════════

# "Non perfetto, ma abbastanza forte da restare." (33x)
_non_perfetto = [
    "Ha difetti, ma li supera con la sostanza.",
    "Non è impeccabile, però tiene banco con merito.",
    "Ha margini di miglioramento, ma ciò non ne cancella il valore.",
    "Non è esente da limiti, ma resta una scelta solida.",
    "Ha qualche imperfezione, ma la bilancia pende comunque a suo favore.",
    "Non è al cento per cento, eppure si fa scegliere.",
    "Gli riconosco dei limiti, ma non abbastanza da disfarsene.",
    "Qualche difetto c'è, ma il complesso è più che sufficiente.",
    "Non raggiunge la perfezione, ma ha abbastanza merito da conservarlo.",
    "Ha le sue lacune, eppure resta nel mio cassetto.",
    "Non è senza pecche, ma la resa complessiva lo giustifica.",
    "C'è margine, ma nel bilancio finale vince il positivo.",
    "Non è tutto rose, però il saldo resta in attivo.",
    "Ha qualche zona d'ombra, ma la luce prevale.",
    "Non è il modello ideale, ma ha abbastanza per restare.",
    "Le imperfezioni ci sono, ma non oscurano il quadro d'insieme.",
    "Ha qualche mancanza, ma le qualità compensano a sufficienza.",
    "Non è inattaccabile, ma ha un valore che non si discute.",
    "Ha punti deboli, ma il tessuto generale regge.",
    "Non brilla in ogni aspetto, ma tiene la posizione con dignità.",
    "Non è flawless, ma ha sostanza sufficiente per meritare il cassetto.",
    "Qualche pecca la trovo, ma il giudizio complessivo resta positivo.",
    "Ha dei nei, ma l'insieme è abbastanza solido da mantenerlo.",
    "Non è il paio perfetto, ma è il paio che uso.",
    "Ha margini, eppure non lo toglierei dalla mia selezione.",
    "Non è ineccepibile, ma si fa perdonare con i suoi punti di forza.",
    "Ha qualche aspetto migliorabile, ma la somma dei pregi lo salva.",
    "Non tutto è al massimo, ma ne ha abbastanza per restare.",
    "Ha le sue crepe, ma la struttura tiene.",
    "Non è tutto perfetto, ma abbastanza buono da non abbandonarlo.",
    "Le manchevolezze ci sono, ma non abbastanza da detronizzarlo.",
    "Ha qualche punto scoperto, ma il bilancio rimane comunque positivo.",
    "Non è irreprensibile, ma ha la stoffa per restare nel giro.",
]
PATTERNS["Non perfetto, ma abbastanza forte da restare."] = _non_perfetto

# "A volte basta mezzo millimetro nel ponte per spostare tutto." (33x)
_mezzo_mill = [
    "Bastano pochi millimetri di differenza nel ponte per cambiare il giudizio.",
    "La vestibilità del ponte è un dettaglio che pesa più di quanto si creda.",
    "In fatto di ponte, la differenza tra comodo e fastidioso è minima.",
    "Il ponte è sempre quel dettaglio dove si gioca tutto.",
    "Un'inezia nella geometria del ponte cambia la resa complessiva.",
    "Il ponte è il punto dove ogni millimetro conta davvero.",
    "Basta una variazione impercettibile nel ponte per alterare tutto l'equilibrio.",
    "Il ponte è il punto di svolta: un nulla lo rende perfetto o problematico.",
    "Questione di pochi millimetri nel ponte, e il feeling cambia radicalmente.",
    "Il ponte è il dettaglio più sottovalutato e più impattante.",
    "Nel ponte ogni dettaglio millimetrico conta in modo sproporzionato.",
    "È nel ponte che si decide gran parte del comfort.",
    "Una minuzia nel ponte può ribaltare l'intera esperienza.",
    "Il ponte è il fulcro: una differenza impercettibile cambia tutto.",
    "Pochi millimetri nel ponte separano il piacere dal fastidio.",
    "Il ponte è l'elemento più critico in termini di vestibilità.",
    "Una variazione minima nel ponte ha un impatto massimo sulla resa.",
    "Il ponte è quel punto dove l'attenzione al millimetro fa la differenza.",
    "Basta un nulla nel ponte per spostare il giudizio in un verso o nell'altro.",
    "Nel ponte si condensano le sorti della vestibilità.",
    "Un dettaglio apparentemente insignificante nel ponte cambia l'esperienza.",
    "Il ponte è il discrimine: un soffio lo rende adatto o meno.",
    "La geometria del ponte è il fattore silenzioso che decide tutto.",
    "Un ponte leggermente diverso avrebbe cambiato l'intera percezione.",
    "Nel ponte si concentra la differenza tra un sì e un no.",
    "Il ponte è dove il comfort si crea o si distrugge.",
    "Questione di micromillimetri nel ponte, eppure l'effetto è enorme.",
    "Il ponte è il dettaglio che non perdona le approssimazioni.",
    "Un ponte leggermente fuori misura basta a compromettere il bilancio.",
    "Il ponte ha un potere sul comfort che va oltre le apparenze.",
    "Basta una sfumatura nel ponte per fare la differenza totale.",
    "L'appoggio del ponte è il test dove tutto si gioca.",
    "Il ponte è la chiave di volta di ogni calzata.",
]
PATTERNS["A volte basta mezzo millimetro nel ponte per spostare tutto."] = _mezzo_mill

# ═══════════════════════════════════════════════════════════
# CHIUSURE 2-3 STELLE
# ═══════════════════════════════════════════════════════════

# "Questa è una di quelle opinioni che nascono più dalla vestibilità che dal gusto astratto." (32x)
_questa_opinione = [
    "Il mio giudizio è più legato alla vestibilità che al design in sé.",
    "Non è una questione di gusto, ma di come calza.",
    "La mia valutazione nasce dalla prova sul viso, non dall'estetica astratta.",
    "Qui il giudizio dipende dalla calzata più che dall'idea.",
    "Non è il concetto a non funzionare, è la resa sul mio viso.",
    "Il verdetto è figlio della vestibilità, non del design.",
    "La mia opinione è legata a come sta, non a come appare in foto.",
    "È una questione pratica, non estetica: la vestibilità decide.",
    "Non giudico il design ma il modo in cui veste me.",
    "La mia critica non riguarda l'idea, ma la resa concreta.",
    "Il punto non è l'estetica: è come si comporta sul viso.",
    "Il mio parere è dettato dalla vestibilità, non dal concetto.",
    "Non è il modello in sé a non convincermi, è la resa sul mio volto.",
    "La questione è pratica: calza o non calza, il design c'entra poco.",
    "Il giudizio è influenzato dalla prova fisica, non dall'idea astratta.",
    "Non è una recensione sul design, è una recensione sulla vestibilità.",
    "Qui la calzata pesa più di qualsiasi considerazione di stile.",
    "Il mio parere è frutto dell'esperienza sul viso, non della teoria.",
    "La vestibilità ha più peso nel mio giudizio di qualsiasi considerazione estetica.",
    "Non giudico il progetto: giudico il risultato sul mio viso.",
    "Il mio verdetto è figlio della compatibilità col mio volto.",
    "La mia posizione è dettata dalla resa pratica, non dal gusto.",
    "Qui il discrimine non è il bello ma il come-calza.",
    "Il giudizio si basa più sulla vestibilità che sull'idea di design.",
    "Non è una questione estetica: è una questione di appoggio e proporzioni.",
    "Il mio parere nasce dal confronto col viso, non dalle foto.",
    "È un giudizio di vestibilità pura, non di estetica.",
    "Il peso maggiore nel mio verdetto lo ha la calzata.",
    "Non valuto l'idea in sé ma come si traduce sul mio volto.",
    "La mia opinione è costruita sulla vestibilità, non sull'apparenza.",
    "Qui si giudica più la calzata che il design.",
    "Non è una questione di gusto ma di compatibilità col mio viso.",
]
PATTERNS["Questa \u00e8 una di quelle opinioni che nascono pi\u00f9 dalla vestibilit\u00e0 che dal gusto astratto."] = _questa_opinione

# "Mi sembra un modello con pregi chiari e limiti altrettanto leggibili." (31x)
_pregi_chiari = [
    "Ha qualità evidenti e difetti altrettanto trasparenti.",
    "I punti di forza e i limiti sono entrambi facili da individuare.",
    "È un modello che mostra apertamente sia i pregi sia i difetti.",
    "Ha meriti e mancanze entrambi ben visibili.",
    "I suoi pro e contro sono entrambi alla luce del sole.",
    "È un modello trasparente nelle sue virtù e nelle sue debolezze.",
    "I punti a favore e contro sono ugualmente facili da leggere.",
    "Ha qualità e limiti parimenti espliciti.",
    "È un modello che non nasconde né i pregi né i difetti.",
    "Mostra con uguale chiarezza ciò che funziona e ciò che no.",
    "I suoi meriti e le sue lacune sono entrambi in evidenza.",
    "È un modello dal bilancio leggibile in ogni sua voce.",
    "Ha pregi e difetti entrambi facili da catalogare.",
    "I punti di forza e le debolezze sono ugualmente comprensibili.",
    "È un modello in cui le luci e le ombre hanno la stessa nitidezza.",
    "Mostra i suoi meriti e le sue lacune con la stessa trasparenza.",
    "È il tipo di modello che rende semplice elencare pro e contro.",
    "Pro e contro sono entrambi esposti con chiarezza.",
    "Ha un profilo dove le qualità e i limiti si vedono bene.",
    "I punti di forza e quelli deboli sono entrambi espliciti.",
    "È un modello dove il buono e il meno buono sono facili da identificare.",
    "Pregi e difetti sono scritti in modo ugualmente chiaro.",
    "È un modello che non imbroglia: mostra tutto, bello e brutto.",
    "Ha il pregio della trasparenza: pro e contro sono palesi.",
    "Ha un bilancio dove ogni voce è leggibile.",
    "Le qualità e le debolezze sono entrambe alla portata del giudizio.",
    "I suoi lati positivi e negativi hanno la stessa evidenza.",
    "Ha un profilo onesto: non nasconde né i pregi né i limiti.",
    "È leggibile in ogni suo aspetto, nel bene e nel male.",
    "Pregi e limiti sono parimenti evidenti e catalogabili.",
    "I punti di forza e le debolezze sono entrambi alla luce.",
]
PATTERNS["Mi sembra un modello con pregi chiari e limiti altrettanto leggibili."] = _pregi_chiari

# ═══════════════════════════════════════════════════════════
# ALTRE CHIUSURE FREQUENTI (≥20x)
# ═══════════════════════════════════════════════════════════

# "C'è dentro molta più questione di proporzioni che di semplice tendenza." (29x)
PATTERNS["C\u2019\u00e8 dentro molta pi\u00f9 questione di proporzioni che di semplice tendenza."] = [
    "La questione non è di moda, è di geometria del viso.",
    "Qui conta più la proporzione che la tendenza.",
    "Non è un problema di stile, è un problema di misure.",
    "La compatibilità qui è più una questione di volumi che di gusto.",
    "Il nodo non è estetico, è strutturale: servono le proporzioni giuste.",
    "La moda c'entra poco: è tutto una questione di proporzioni facciali.",
    "Qui il vero discrimine è la compatible con la geometria del viso.",
    "Non è una questione di trend, è una questione di come cade.",
    "La chiave non è il gusto ma l'armonia con i tratti del viso.",
    "Quello che conta è il rapporto con la struttura facciale, non la moda.",
    "La tendenza importa poco: la resa dipende dalla proporzione.",
    "È un discorso di armonia geometrica, non di mode passeggere.",
    "I volumi del viso decidono più del gusto personale.",
    "Qui la proporzione è regina e la moda viene dopo.",
    "La resa finale dipende dalla geometria facciale, non dal trend.",
    "Non è il design a decidere, sono le proporzioni del viso.",
    "La questione è tutta nella compatibilità strutturale, non nello stile.",
    "Il vero test non è estetico ma proporzionale.",
    "Il rapporto con il viso conta infinitamente più della moda.",
    "La partita si gioca sulle proporzioni, non sulle tendenze.",
    "Non si tratta di moda: si tratta di geometria e compatibilità.",
    "Il punto è la proporzione col viso, non il trend del momento.",
    "La resa dipende più dalla struttura facciale che dalla tendenza.",
    "Non è una questione di stile ma di matematica del viso.",
    "Il discrimine è tutto nelle proporzioni, non nell'estetica.",
    "Il design è secondario rispetto alla compatibilità col viso.",
    "La moda qui non c'entra: è questione di volumi e misure.",
    "Il vero nodo è la proporzione, non la tendenza del momento.",
    "Il giudizio è più legato alla struttura del viso che allo stile.",
]
PATTERNS["C'\u00e8 dentro molta pi\u00f9 questione di proporzioni che di semplice tendenza."] = PATTERNS["C\u2019\u00e8 dentro molta pi\u00f9 questione di proporzioni che di semplice tendenza."]

# "Ha una presenza che non dipende dal logo, ma dalla forma e da come cade sul viso." (29x)
PATTERNS["Ha una presenza che non dipende dal logo, ma dalla forma e da come cade sul viso."] = [
    "L'identità non viene dal marchio ma dalla forma e dalla calzata.",
    "Il suo carattere nasce dalla linea e dalla resa sul viso, non dal logo.",
    "Non è il brand che colpisce: è la sagoma e come sta addosso.",
    "La personalità qui è tutta nella struttura e nella vestibilità.",
    "Il fascino non è legato al nome ma alla forma e al modo in cui si pone sul viso.",
    "Non è una questione di griffe: è la forma a fare tutto.",
    "L'impatto non viene dal marchio, viene dal design e dalla resa.",
    "Il logo è secondario: conta la forma e come veste.",
    "Non deve nulla al nome: tutto il suo appeal sta nella forma.",
    "Il suo valore si esprime attraverso la linea e la vestibilità, non il brand.",
    "Non è il brand a dare forza: è la sagoma e la calzata.",
    "Il merito è tutto della forma e della resa, non del logo sulla stanghetta.",
    "L'autorevolezza non viene dal marchio ma dal modo in cui cade sul viso.",
    "Non conta chi lo fa: conta come si presenta sul volto.",
    "Il suo punto di forza è la forma, non l'etichetta.",
    "L'identità nasce dalla struttura e dalla resa, non dal nome.",
    "Non è la griffe che parla: è la linea e come si appoggia.",
    "Il carattere è nella sagoma e nel modo in cui interagisce col viso.",
    "Il logo è l'ultimo dei suoi meriti: la forma dice tutto.",
    "Non deve niente al brand: la sua forza è nella proporzione e nella calzata.",
    "La sua presenza è tutta nel design e nella vestibilità sul volto.",
    "Non è questione di marchio: è tutto nella linea e nella resa.",
    "L'appeal sta nel modo in cui cade, non nel nome stampato.",
    "Il suo fascino prescinde dal brand: è la forma che parla.",
    "L'identità è costruita sulla struttura, non sull'etichetta.",
    "Non dipende dal nome per farsi notare: basta la forma.",
    "Il merito è della sagoma e della resa sul viso, non del marchio.",
    "Il valore non sta nel logo: sta nella proporzione e nella calzata.",
    "La sua forza è nella linea e in come veste, non nel brand.",
]

# "Con il contesto giusto rende molto più che bene." (29x)
PATTERNS["Con il contesto giusto rende molto pi\u00f9 che bene."] = [
    "Nell'ambiente adatto esprime il suo massimo potenziale.",
    "Con lo sfondo giusto il risultato è oltre le aspettative.",
    "Se lo si associa al contesto giusto, la resa è notevole.",
    "Nel contesto appropriato brilla in modo sorprendente.",
    "Con l'occasione giusta diventa un pezzo da novanta.",
    "Non è universale, ma nel setting giusto vola alto.",
    "Nella situazione adeguata esprime una qualità superiore.",
    "Se lo si inquadra nel giusto contesto, il risultato è eccellente.",
    "Nell'occasione giusta la resa è più che soddisfacente.",
    "Con lo scenario adatto la resa cambia radicalmente in meglio.",
    "Non ovunque, ma dove funziona, funziona benissimo.",
    "Nel terreno adatto dà frutti che sorprendono.",
    "Se abbinato bene, il risultato è davvero sopra la media.",
    "Nell'ambiente giusto il suo potenziale si moltiplica.",
    "Con le giuste condizioni la resa è di altissimo livello.",
    "Nella nicchia giusta esprime il meglio di sé.",
    "Se collocato bene, la qualità emerge con forza.",
    "Con il giusto abbinamento il risultato è di grande impatto.",
    "Nel contesto ideale il suo valore si manifesta appieno.",
    "Con la giusta cornice diventa un acquisto davvero luminoso.",
    "Nell'ambito giusto la resa è decisamente sopra la media.",
    "Quando l'occasione è quella giusta, il livello si alza notevolmente.",
    "Con il contesto adatto esprime una resa che sorprende.",
    "Se gli si concede il terreno giusto, la qualità emerge con forza.",
    "Nell'ambiente corretto il bilancio diventa molto positivo.",
    "Con le circostanze adatte dà risultati che non ti aspetti.",
    "Nel contesto giusto il modello esprime tutto il suo valore.",
    "Se l'occasione è adeguata, la resa è davvero notevole.",
    "Con lo sfondo adatto il risultato finale è di spessore.",
]

# "Forse su un altro volto il bilancio cambierebbe anche parecchio." (28x)
PATTERNS["Forse su un altro volto il bilancio cambierebbe anche parecchio."] = [
    "Su un viso diverso dal mio il giudizio potrebbe essere molto diverso.",
    "Con un'altra struttura facciale i risultati sarebbero probabilmente altri.",
    "Il bilancio è personale: su un altro viso il verdetto cambierebbe.",
    "Per un volto diverso la storia potrebbe essere completamente un'altra.",
    "Il mio giudizio è legato al mio viso: su altri potrebbe calzare benissimo.",
    "Un altro volto potrebbe ribaltare completamente il verdetto.",
    "Con proporzioni facciali diverse il risultato sarebbe un altro.",
    "Il giudizio è soggettivo e legato alle mie proporzioni: su altri visi potrebbe essere opposto.",
    "Su un viso con proporzioni diverse il bilancio cambierebbe molto.",
    "Il mio volto è solo uno dei tanti: su altri potrebbe funzionare alla grande.",
    "Con un altro tipo di viso l'esperienza potrebbe essere radicalmente diversa.",
    "La resa dipende dal viso, e il mio non è l'unico metro.",
    "Su geometrie facciali diverse il giudizio potrebbe essere opposto.",
    "Per un viso diverso il discorso potrebbe cambiare completamente.",
    "Il bilancio è legato al mio volto: non è un giudizio universale.",
    "Su altri lineamenti il modello potrebbe esprimersi molto meglio.",
    "La mia esperienza è personale: un viso diverso potrebbe stravolgere il giudizio.",
    "Con altri tratti facciali le conclusioni sarebbero probabilmente diverse.",
    "Il verdetto riflette il mio viso: su un altro potrebbe essere l'opposto.",
    "Cambiando viso il bilancio si riscriverebbe probabilmente.",
    "Su un altro volto le carte in tavola sarebbero diverse.",
    "La resa è strettamente personale: su altri visi la storia cambierebbe.",
    "Un altro tipo di viso renderebbe probabilmente un giudizio diverso.",
    "Il mio bilancio è mio: un altro volto porterebbe altri risultati.",
    "Su una struttura facciale diversa dalla mia le cose andrebbero diversamente.",
    "Con un viso diverso i rapporti di forza cambierebbero.",
    "Non generalizzo: su un altro volto il verdetto sarebbe certamente diverso.",
    "La mia è un'esperienza personale: su un'altra faccia il discorso cambierebbe.",
]

# "Con i suoi limiti, resta un acquisto che rifarei." (27x)
PATTERNS["Con i suoi limiti, resta un acquisto che rifarei."] = [
    "Nonostante i limiti, lo comprerei di nuovo.",
    "Anche con i difetti che ha, lo riconfermerei.",
    "Malgrado le imperfezioni, lo sceglierei ancora.",
    "Con tutti i suoi limiti, non me ne pento.",
    "Pur con le sue mancanze, lo rifarei senza troppe esitazioni.",
    "Difetti compresi, resta un acquisto che confermerei.",
    "Non è senza limiti, ma lo riacquisterei.",
    "I difetti ci sono, ma non bastano a farmi rimpiangere la scelta.",
    "Nonostante qualche pecca, lo rifarei con la stessa convinzione.",
    "Anche con le sue debolezze, lo ricomprerei.",
    "Se dovessi rifare la scelta, la rifarei nonostante i limiti.",
    "I difetti non cancellano il fatto che lo rifarei.",
    "Pur non essendo perfetto, è un acquisto che riconfermerei.",
    "Con le sue imperfezioni, resta una scelta che ripeterei.",
    "I limiti ci sono, ma il giudizio finale resta un sì.",
    "Se tornassi indietro, lo sceglierei di nuovo nonostante i difetti.",
    "Ha i suoi limiti, ma il bilancio resta positivo abbastanza da ricomprarlo.",
    "Limiti inclusi, lo riprenderei senza esitazioni eccessive.",
    "I suoi punti deboli non mi farebbero cambiare la decisione.",
    "Nonostante le zone d'ombra, lo racquisterei volentieri.",
    "Anche riconoscendo le imperfezioni, resta una scelta che rifarei.",
    "Le lacune ci sono, ma non abbastanza da pentirmi dell'acquisto.",
    "Se dovessi scegliere di nuovo, lo prenderei ancora, limiti e tutto.",
    "I difetti non bastano a farmi cambiare idea: lo rifarei.",
    "Con i suoi limiti riconosciuti, resta un sì.",
    "Nonostante qualche nota in meno, lo ricomprerei.",
    "Anche con le sue debolezze note, è un acquisto che confermerei.",
]

# "Non è una condanna universale né un'ovazione cieca: è proprio una reazione d'uso." (27x)
PATTERNS["Non \u00e8 una condanna universale n\u00e9 un\u2019ovazione cieca: \u00e8 proprio una reazione d\u2019uso."] = [
    "Non è né bocciatura totale né elogio smisurato: è un giudizio pratico.",
    "Non lo condanno e non lo esalto: lo giudico per come lo uso.",
    "Il mio parere non è estremo: nasce dall'esperienza di utilizzo.",
    "Non è bianco o nero: è il grigio dell'uso quotidiano.",
    "Non lo demolisco né lo celebro: lo valuto per quello che mi dà.",
    "È un giudizio che nasce dalla pratica, non dalla teoria.",
    "Non è una stroncatura né un inno: è un parere di uso reale.",
    "Il mio verdetto è figlio dell'uso, non dell'entusiasmo o della rabbia.",
    "Non idealizzo e non condanno: valuto sulla base di ciò che ho vissuto.",
    "È un parere nato dall'uso, non dalla pancia.",
    "Non è un giudizio per eccesso: è semplicemente la mia esperienza.",
    "Né apoteosi né catastrofe: è la cronaca del mio uso.",
    "Non mi faccio trascinare dagli estremi: è un giudizio equilibrato.",
    "Non è né il dieci né lo zero: è il voto dell'esperienza.",
    "Evito i giudizi assoluti: il mio è un parere d'uso.",
    "Non lo esalto e non lo affondo: lo racconto per come è stato.",
    "Il mio giudizio è pratico, non emotivo.",
    "Non è un verdetto drastico: è la sintesi dell'uso reale.",
    "Non cerco di convertire nessuno: parlo per esperienza diretta.",
    "Non è un'opinione estrema: è il resoconto di come si porta.",
    "Il mio parere è calibrato: nasce dalla pratica, non da un impulso.",
    "Non mi esprimo per slogan: giudico sulla base dell'uso effettivo.",
    "Non è un giudizio di pancia: è il bilancio di un uso concreto.",
    "Né entusiasmo cieco né delusione: è un parere misurato sull'uso.",
    "Non è un giudizio ideologico: è la traduzione della mia esperienza.",
    "Il mio verdetto non è radicale: riflette l'uso che ne ho fatto.",
    "Non sto né da una parte né dall'altra: racconto ciò che ho provato.",
]
PATTERNS["Non \u00e8 una condanna universale n\u00e9 un'ovazione cieca: \u00e8 proprio una reazione d'uso."] = PATTERNS["Non \u00e8 una condanna universale n\u00e9 un\u2019ovazione cieca: \u00e8 proprio una reazione d\u2019uso."]

# "Il punto non è che sia sbagliato, è che non mi scatta l'istinto." (27x)
PATTERNS["Il punto non \u00e8 che sia sbagliato, \u00e8 che non mi scatta l\u2019istinto."] = [
    "Non è questione di difetti, è che non mi scatta la connessione.",
    "Non ha niente di sbagliato: semplicemente non mi parla.",
    "Il problema non è un errore, è un'assenza di feeling.",
    "Non è che non funzioni: è che non mi convince a livello viscerale.",
    "Non è difettoso, è che manca quel qualcosa che mi farebbe sceglierlo.",
    "Il nodo non è un difetto, è una mancanza di scintilla.",
    "Non è carente, è che non mi scatta il riflesso di prenderlo.",
    "Il limite non è tecnico: è una questione di istinto personale.",
    "Non è che sia mal fatto: è che non mi viene naturale indossarlo.",
    "Il problema non è un difetto: è l'assenza dell'impulso di portarlo.",
    "Non è sbagliato in sé: semplicemente non mi innesca quella voglia.",
    "Non è un errore di design, è una mancanza di connessione spontanea.",
    "Il punto critico non è un limite: è l'assenza dell'istintività.",
    "Non trovo difetti concreti: è il richiamo istintivo che manca.",
    "Il nodo non è la qualità, è la mancanza di quella spinta naturale.",
    "Non è una questione razionale: è l'istinto che non si accende.",
    "Non è fallato: gli manca solo quel magnetismo che mi farebbe sceglierlo.",
    "Il limite è nell'alchimia personale, non nel prodotto.",
    "Non è difettoso, è che non mi viene la voglia spontanea di portarlo.",
    "Il problema non è nel modello: è nell'assenza del mio istinto.",
    "Non è sbagliato, è semplicemente fuori dalla mia frequenza.",
    "Non posso criticare la qualità: è il richiamo istintivo che manca.",
    "Il difetto non è tecnico: è la mancanza di un feeling spontaneo.",
    "Non trovo errori, eppure non mi scatta l'impulso.",
    "Il punto debole non è nel modello: è nella connessione con me.",
    "Non è una questione di qualità: è che l'istinto non risponde.",
    "Non è carente: gli manca solo l'alchimia con il mio modo di essere.",
]
PATTERNS["Il punto non \u00e8 che sia sbagliato, \u00e8 che non mi scatta l'istinto."] = PATTERNS["Il punto non \u00e8 che sia sbagliato, \u00e8 che non mi scatta l\u2019istinto."]

# "Quindi lo tengo in una terra di mezzo." (27x)
PATTERNS["Quindi lo tengo in una terra di mezzo."] = [
    "Per questo lo colloco in una zona intermedia.",
    "Lo posiziono quindi in un limbo valutativo.",
    "Di conseguenza resta in un'area di giudizio sospesa.",
    "Per questo il mio giudizio non si sbilancia.",
    "Lo catalogo quindi fra i giudizi irrisolti.",
    "Resta così in una posizione di stallo nel mio parere.",
    "Per questo motivo il mio verdetto rimane in sospeso.",
    "Il risultato è che lo lascio in una zona d'ombra valutativa.",
    "Così finisce in quella fascia dove non promuovo e non boccia.",
    "Il mio giudizio si ferma a metà strada.",
    "Per questo lo colloco fra le valutazioni incompiute.",
    "Rimane quindi in un'area grigia del mio bilancio.",
    "Per questo il parere non si chiude in modo netto.",
    "Di conseguenza il giudizio resta in bilico.",
    "Lo lascio quindi in una zona neutra del mio cassetto.",
    "Per questo motivo non prendo una posizione decisa.",
    "Lo colloco così in un limbo fra positivo e negativo.",
    "Per questo il mio verdetto non trova un approdo chiaro.",
    "Il giudizio rimane in un territorio incerto.",
    "Lo posiziono di conseguenza in una zona dove il parere non è netto.",
    "Per questo resta in un equilibrio precario nel mio giudizio.",
    "Di conseguenza non lo catalogo né fra i migliori né fra i peggiori.",
    "Lo lascio in un'area intermedia del mio bilancio.",
    "Per questo lo tengo in un punto dove il giudizio oscilla.",
    "Il mio parere resta sospeso, senza approdi certi.",
    "Per questo motivo lo lascio in una fascia di mezzo.",
    "Di conseguenza il mio giudizio non lo colloca da nessuna parte in modo netto.",
]

# "Lo promuovo, pur senza idealizzarlo." (27x)
PATTERNS["Lo promuovo, pur senza idealizzarlo."] = [
    "Lo approvo, senza però farne un mito.",
    "Il mio giudizio è positivo, senza essere entusiastico.",
    "Lo promuovo con la lucidità di chi vede anche i limiti.",
    "Lo consiglio, mantenendo una visione realistica.",
    "Il verdetto è positivo, ma con le dovute proporzioni.",
    "Lo promuovo senza farmi trascinare dall'entusiasmo.",
    "Lo approvo con una nota di pragmatismo.",
    "Lo promuovo sapendo che non è il modello perfetto.",
    "Il mio sì è lucido, non cieco.",
    "Lo promuovo con una dose ragionevole di realismo.",
    "Lo consiglio senza dimenticare i suoi limiti.",
    "Lo approvo mantenendo i piedi per terra.",
    "Il mio giudizio è positivo ma calibrato.",
    "Lo promuovo senza metterlo su un piedistallo.",
    "Lo consiglio con onestà, non con fanatismo.",
    "Lo promuovo riconoscendo anche ciò che non è perfetto.",
    "Il mio verdetto positivo è ragionato, non emotivo.",
    "Lo approvo mantenendo il senso delle proporzioni.",
    "Lo promuovo con un entusiasmo controllato.",
    "Lo consiglio, ma con la chiarezza di chi non ha le fette di salame sugli occhi.",
    "Lo promuovo senza nascondere i suoi limiti.",
    "Il mio sì è consapevole, non incondizionato.",
    "Lo approvo con le dovute sfumature.",
    "Lo promuovo senza esagerare con i toni.",
    "Lo consiglio con la misura che merita.",
    "Lo promuovo, senza per questo metterlo sul piedistallo.",
    "Lo consigo con una promozione lucida e consapevole.",
]

# "Non ho avuto quella fase di dubbio che mi capita con i modelli più costruiti." (27x)
PATTERNS["Non ho avuto quella fase di dubbio che mi capita con i modelli pi\u00f9 costruiti."] = [
    "Non c'è stata la solita incertezza che provo con i modelli più elaborati.",
    "Ho saltato quella fase di indecisione che di solito accompagna i modelli complessi.",
    "Non ho attraversato il consueto periodo di dubbio dei modelli più strutturati.",
    "La fase di incertezza che temo con i modelli più articolati qui non è arrivata.",
    "Non ho vissuto quel tentennamento che di solito provo con i modelli più carichi.",
    "L'incertezza che accompagna i modelli più ricercati qui non si è presentata.",
    "Non ho avuto quel periodo di ripensamento tipico dei modelli più costruiti.",
    "Il dubbio che di solito mi assale con i modelli più elaborati qui non è emerso.",
    "Non c'è stato quel passaggio di indecisione che temo sempre con i modelli complessi.",
    "Ho evitato quella zona grigia che mi capita con i modelli più sfaccettati.",
    "La fase di perplessità che solitamente accompagna i modelli articolati qui non c'è stata.",
    "Non ho dovuto attraversare quel tunnel di incertezza dei modelli più costruiti.",
    "La solita esitazione con i modelli più elaborati qui non si è manifestata.",
    "Non c'è stata quella fase di ripensamento che di norma sperimento con modelli simili.",
    "Il percorso di dubbio che spesso accompagna i modelli strutturati qui è saltato.",
    "Non ho avuto i soliti tentennamenti che mi prendono con i modelli più lavorati.",
    "La fase di incertezza iniziale che associo ai modelli più complessi non si è verificata.",
    "Ho saltato quel periodo di perplessità che di solito mi frena con i modelli articolati.",
    "L'indecisione che mi coglie con i modelli più ricercati qui non si è vista.",
    "Non ho attraversato quella palude di dubbi tipica dei modelli più impegnativi.",
    "Il percorso di incertezza che pavento con i modelli complessi non si è materializzato.",
    "Non c'è stata la tipica esitazione che provo con i modelli più costruiti.",
    "Non ho avuto il solito periodo di ambiguità che mi prende con i modelli elaborati.",
    "Il dubbio prolungato che temo con i modelli più complessi qui non è comparso.",
    "Non c'è passata quella fase di instabilità nel giudizio che mi capita con i modelli impegnativi.",
    "L'oscillazione che di solito mi accompagna con i modelli strutturati qui è mancata.",
    "Non ho sofferto la tipica incertezza dei modelli più complessi.",
]

print(f"Parte 4 caricata: totale {len(PATTERNS)} pattern definiti")
