#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Parte 3: Pattern restanti di incipit/chiusura meno frequenti
"""

from rewrite_reviews_part2 import PATTERNS

# ---------------------------------------------------------------------------
# "La cosa più onesta che posso dire è" (32x)
# ---------------------------------------------------------------------------
PATTERNS["La cosa pi\u00f9 onesta che posso dire \u00e8"] = [
    "La valutazione più sincera che mi sento di dare è",
    "Se devo essere del tutto onesto, il mio parere è",
    "Il giudizio più trasparente che posso offrire è",
    "La risposta più diretta che ho è",
    "La descrizione più fedele che riesco a dare è",
    "Se tolgo ogni filtro, il mio giudizio è",
    "Parlando con la massima franchezza,",
    "Il resoconto più onesto che posso fare è",
    "Se devo andare dritto al punto,",
    "La mia opinione più nuda è",
    "Senza giri di parole, il mio verdetto è",
    "Il giudizio più schietto che ho è",
    "Se devo pesare ogni parola, la verità è",
    "In tutta sincerità, la mia impressione è",
    "Se devo mettere nero su bianco,",
    "Con la massima onestà intellettuale,",
    "Il resoconto più leale che posso dare è",
    "Detto nel modo più diretto possibile,",
    "La fotografia più fedele che posso fare è",
    "Se tolgo qualsiasi abbellimento,",
    "Il racconto più autentico che posso offrire è",
    "Con la sincerità che merita una recensione seria,",
    "Se devo essere completamente trasparente,",
    "La lettura più aderente alla realtà è",
    "Se mi chiedete un'opinione senza filtri,",
    "Il mio giudizio più netto è",
    "Depurato da ogni entusiasmo o delusione,",
    "Se devo condensare tutto in un parere,",
    "La mia valutazione più equilibrata è",
    "Il parere più genuino che posso offrire è",
    "La mia presa di posizione più onesta è",
    "Se devo dire pane al pane,",
]
# "Li ho comprati per un motivo e li" (32x)
PATTERNS["Li ho comprati per un motivo e li"] = [
    "Li ho scelti per una ragione precisa e li",
    "L'acquisto aveva una motivazione chiara e li",
    "Li ho presi con un'idea in testa e li",
    "Avevo uno scopo preciso quando li ho comprati e li",
    "Il motivo dell'acquisto era specifico e li",
    "Li ho cercati con un obiettivo e li",
    "Li ho ordinati per un'esigenza precisa e li",
    "C'era un motivo concreto dietro l'acquisto e li",
    "Li ho voluti per una ragione specifica e li",
    "L'ho fatto per un'esigenza pratica e li",
    "La motivazione iniziale era chiara e li",
    "Avevo un'idea precisa quando li ho comprati e li",
    "Li ho acquistati sapendo cosa cercavo e li",
    "Lo scopo iniziale era definito e li",
    "Li ho selezionati con un criterio e li",
    "Il movente dell'acquisto era preciso e li",
    "Li ho presi con un progetto in mente e li",
    "La ragione d'acquisto era netta e li",
    "Il proposito era chiaro quando li ho scelti e li",
    "Li ho comprati sapendo perché e li",
    "C'era un piano dietro l'acquisto e li",
    "L'intenzione d'acquisto era mirata e li",
    "Li ho voluti per colmare un vuoto e li",
    "Li ho scelti con cognizione di causa e li",
    "Il bisogno era identificato e li",
    "Li ho presi per un fine pratico e li",
    "Avevo le idee chiare sul perché comprarli e li",
    "La decisione aveva una base concreta e li",
    "Li ho acquistati con una ragione precisa e li",
    "C'era un'esigenza reale dietro e li",
    "Li ho scelti seguendo un ragionamento e li",
    "Il perché dell'acquisto era limpido e li",
]
# "Il primo impatto non dice tutta la verità su questo paio." (42x)
PATTERNS["Il primo impatto non dice tutta la verit\u00e0 su questo paio."] = [
    "Questo modello va oltre la prima impressione.",
    "Il primo sguardo non basta per capire questo paio.",
    "C'è molto di più di quello che si nota subito.",
    "Servono più minuti di quanto si pensi per inquadrarli.",
    "La superficie racconta solo metà della storia.",
    "L'apparenza iniziale non esaurisce il discorso.",
    "Il primo contatto è solo un antipasto.",
    "Dietro la prima impressione c'è un mondo da esplorare.",
    "Non è un paio che si decodifica al volo.",
    "Serve pazienza per apprezzarli davvero.",
    "L'impressione d'istinto è incompleta.",
    "Ci vuole tempo per cogliere tutto quello che offrono.",
    "Il giudizio rapido non rende giustizia a questo modello.",
    "Il primo impatto non è indicativo del quadro completo.",
    "C'è una profondità che sfugge al primo sguardo.",
    "Questo paio ha più strati di quanto sembri.",
    "La prima occhiata non coglie l'essenziale.",
    "Il primo approccio è fuorviante, la verità sta nell'uso.",
    "Non è il tipo di occhiale che si giudica in un lampo.",
    "La lettura rapida non funziona con questo modello.",
    "Serve un po' di frequentazione per capirli.",
    "Il giudizio immediato è solo una bozza.",
    "C'è più sostanza di quella che emerge al primo contatto.",
    "La valutazione al volo non è quella giusta.",
    "Il primo tentativo non dice tutto.",
    "La verità si rivela con l'uso, non con lo sguardo.",
    "Non è un amore o un rifiuto a prima vista.",
    "Questo modello richiede una seconda lettura.",
    "La prima impressione non è il giudizio definitivo.",
    "La fretta non è amica di questo paio.",
    "Bisogna dargli tempo per capire cosa sanno fare.",
    "Il primo capitolo non racconta la storia intera.",
    "Non si lasciano inquadrare immediatamente.",
    "C'è un divario tra primo impatto e giudizio ponderato.",
    "La reazione istintiva va corretta dall'esperienza.",
    "Il primo incontro è solo un'introduzione.",
    "Non si svelano subito, e forse è il loro pregio.",
    "La conoscenza richiede più di un tentativo.",
    "La fotografia iniziale è parziale.",
    "Il primo giro non basta a capirli.",
    "La loro verità emerge con l'uso continuativo.",
    "Il primo giudizio è quasi sempre da rivedere.",
]
# "In foto mi piacevano, ma dal vivo la lettura cambia parecchio." (42x)
PATTERNS["In foto mi piacevano, ma dal vivo la lettura cambia parecchio."] = [
    "Sullo schermo promettevano bene, ma di persona la percezione è diversa.",
    "Le immagini non raccontano tutto: dal vivo cambiano molte cose.",
    "Dalle foto all'esperienza reale c'è un salto notevole.",
    "L'immagine online e la resa reale non coincidono del tutto.",
    "Il divario fra foto e realtà qui si sente parecchio.",
    "Sulle foto erano convincenti, sul viso il discorso è un altro.",
    "Lo scarto tra immagine e realtà è stato significativo.",
    "Online erano una cosa, di persona un'altra.",
    "Le foto mi avevano illuso un po': dal vivo la musica cambia.",
    "La distanza fra lo schermo e il naso è più grande del previsto.",
    "L'aspettativa creata dalle immagini non corrisponde alla realtà.",
    "Fotograficamente funzionavano, nella realtà il discorso si complica.",
    "Fra la foto e il viso c'è un oceano di differenza.",
    "L'impressione digitale e quella dal vero non coincidono.",
    "Le immagini promettevano, il riscontro reale ha ridimensionato.",
    "Dallo schermo al naso il percorso è stato sorprendente.",
    "Quello che vedevo online non è quello che ho trovato addosso.",
    "L'entusiasmo delle foto si è ridimensionato dal vivo.",
    "La resa fotografica ingannava: sul viso è tutto diverso.",
    "L'impressione a schermo e quella a specchio non vanno d'accordo.",
    "Le foto li presentavano al meglio, la realtà è più sfumata.",
    "Dal catalogo al viso il passaggio non è stato indolore.",
    "Le foto raccontavano una storia, il viso un'altra.",
    "L'attrattiva delle immagini non si è tradotta uguale dal vivo.",
    "Il gap fra rendering e realtà ha pesato nel mio giudizio.",
    "Le foto li valorizzavano, il confronto col viso meno.",
    "La differenza fra l'immagine e l'esperienza reale è rilevante.",
    "Online sembravano perfetti, dal vivo la perfezione sfuma.",
    "Il passaggio dallo schermo alla realtà non è stato liscio.",
    "L'impressione digitale e il test fisico raccontano storie diverse.",
    "Sulle foto brillavano, nel quotidiano la resa è più contenuta.",
    "L'immagine online non preparava alla realtà.",
    "Dal monitor al naso il viaggio è stato accidentato.",
    "Tra il look fotografico e quello reale c'è un margine ampio.",
    "Le foto catturavano, l'esperienza reale poneva nuove domande.",
    "La promessa delle immagini non è stata del tutto mantenuta.",
    "Quello che funzionava in foto non funziona uguale dal vivo.",
    "Il modello fotografa meglio di come si vive.",
    "Le immagini avevano creato aspettative che il viso ha ridimensionato.",
    "L'appeal delle foto non ha retto il confronto col reale.",
    "Sulle immagini ero convinto, dal vivo ho rivisto il giudizio.",
    "Il fascino delle foto è stato solo parzialmente confermato dal vivo.",
]
# "La prima impressione è stata migliore del previsto." (45x)
PATTERNS["La prima impressione \u00e8 stata migliore del previsto."] = [
    "Il primo contatto ha superato le mie aspettative.",
    "Mi ha sorpreso positivamente alla prima prova.",
    "L'impatto iniziale è stato superiore a quanto immaginassi.",
    "La resa immediata è stata più convincente del previsto.",
    "Il primo approccio è stato più promettente di quanto sperassi.",
    "Alla prima prova la sorpresa è stata positiva.",
    "L'effetto al primo utilizzo mi ha colpito favorevolmente.",
    "Il primo incontro ha dato più di quanto mi aspettassi.",
    "Dal primo istante hanno superato le premesse.",
    "Già al primo sguardo hanno dimostrato più del previsto.",
    "L'apertura della custodia è stata più piacevole del previsto.",
    "Il primo test è andato oltre le mie previsioni.",
    "Il debutto è stato sorprendentente positivo.",
    "Alla prima uscita hanno impressionato più del dovuto.",
    "Il primo impatto ha battuto le aspettative.",
    "Il feeling iniziale è stato più forte di quanto immaginassi.",
    "Il primo contatto è stato una piacevole sorpresa.",
    "L'esordio è stato migliore di quanto speravo.",
    "La prima prova è stata incoraggiante oltre misura.",
    "Il primo sguardo ha dato risultati superiori alle premesse.",
    "Il primo tentativo ha raccolto più consensi di quanto prevedessi.",
    "L'avvio è stato promettente, anche più del necessario.",
    "Il primo utilizzo è stato più confortante del previsto.",
    "Il primo giro è andato meglio delle mie previsioni.",
    "Dal primo momento hanno dato segnali migliori delle attese.",
    "La prima prova è stata più convincente di quanto immaginassi.",
    "L'impatto al primo tentativo ha superato le mie stime.",
    "Il primo contatto ha risposto oltre le aspettative.",
    "L'approccio iniziale è stato più gratificante del previsto.",
    "Al primo tentativo hanno dimostrato qualcosa in più.",
    "Il debutto è stato insaspettatamente buono.",
    "L'inizio è stato più luminoso delle premesse.",
    "Il primo assaggio è stato più gustoso del previsto.",
    "Il primo round è andato a loro favore, nettamente.",
    "L'esordio è stato più forte di quanto avrei scommesso.",
    "Dal primo utilizzo è emerso qualcosa di più del previsto.",
    "Le prime sensazioni sono state migliori delle aspettative.",
    "Il primo test ha dato un risultato sopra la media delle attese.",
    "Il primo approccio ha consegnato più di quanto richiesto.",
    "Alla prima prova il risultato ha superato le premesse.",
    "Il primo tentativo è stato più eloquente del previsto.",
    "Il feeling iniziale ha ecceduto le mie aspettative.",
    "Il debutto ha avuto un impatto migliore di quanto prevedessi.",
    "Alla prima uscita sono rimasto colpito più del dovuto.",
    "Il primo incontro è stato più incisivo delle mie previsioni.",
]
# "Pensavo di aver capito tutto dalle immagini, invece no." (43x)
PATTERNS["Pensavo di aver capito tutto dalle immagini, invece no."] = [
    "Credevo che le foto dicessero tutto, mi sbagliavo.",
    "Le immagini mi avevano dato un'idea incompleta.",
    "Online pensavo di conoscerli, dal vivo ho scoperto altro.",
    "Le foto non raccontavano la storia completa.",
    "Mi ero fatto un'idea dalle immagini che poi si è rivelata parziale.",
    "Quello che vedevo online era solo una parte della verità.",
    "Dalle foto credevo di sapere cosa aspettarmi, e invece.",
    "L'impressione dal web non corrispondeva alla realtà a tutto tondo.",
    "Guardandoli sullo schermo credevo di averli inquadrati. Non era così.",
    "Le foto mi avevano raccontato una mezza verità.",
    "Credevo di conoscere già il modello, ma dal vivo è cambiato tutto.",
    "L'idea che mi ero costruito dalle foto era incompleta.",
    "Pensavo che le foto bastassero per giudicare: avevo torto.",
    "Le immagini sono state fuorvianti rispetto al risultato reale.",
    "Dal catalogo pensavo di averli già capiti. Mi illudevo.",
    "Online mi sembravano una cosa, dal vivo sono un'altra.",
    "Le foto mi aveano raccontato una storia diversa da quella reale.",
    "Credevo di aver decodificato tutto dallo schermo. Errore mio.",
    "L'impressione digitale mi aveva ingannato in parte.",
    "Dal web al viso c'è un mondo che le foto non mostrano.",
    "Le immagini erano un trailer, il film dal vivo è un altro.",
    "Online mi sembrava di conoscerli, la realtà ha corretto il tiro.",
    "Quello che credevo di sapere dalle foto era parziale.",
    "Le immagini non dicevano tutto, non si avvicinevano nemmeno.",
    "Dall'immagine al prodotto reale la differenza è stata notevole.",
    "Pensavo di averli già giudicati sul web: sbagliavo di grosso.",
    "Le foto raccontavano solo metà della storia.",
    "L'idea preconcepita dalle immagini non ha retto.",
    "Le immagini mi avevano dato una certezza che è crollata dal vivo.",
    "Il giudizio che mi ero costruito dallo schermo era fuori fuoco.",
    "Non basta guardare le foto per capire un paio di occhiali.",
    "Le foto mi avevano preparato male alla realtà.",
    "Credevo di conoscerli per immagini; la realtà ha fatto il suo corso.",
    "Il giudizio dal web era incompleto, come spesso accade.",
    "Le foto avevano dato solo una versione parziale.",
    "Dalle immagini non avevo capito il quadro intero.",
    "Pensavo di sapere cosa mi aspettava: le foto non bastano mai.",
    "Il modello che avevo in mente dalle foto era diverso da quello reale.",
    "Le foto mi avevano dato certezze che la realtà ha smontato.",
    "C'era più da scoprire di quanto le immagini suggerissero.",
    "Il gap fra foto e realtà mi ha costretto a rivedere il giudizio.",
    "Dalle immagini il modello è una cosa, in mano un'altra.",
    "Le foto erano un punto di partenza, non il punto di arrivo.",
]
# "Ho aspettato qualche uscita prima di farmi un'idea" (29x)
PATTERNS["Ho aspettato qualche uscita prima di farmi un\u2019idea"] = [
    "Mi sono preso del tempo prima di esprimermi",
    "Ho preferito aspettare qualche utilizzo prima di giudicare",
    "Non ho voluto correre nel giudizio, mi sono dato tempo",
    "Ho lasciato passare più di un'occasione prima di decidere",
    "Mi sono dato un margine di tempo prima di tirare le somme",
    "Ho voluto testarli in più situazioni prima di parlare",
    "Non mi sono pronunciato subito, ho aspettato di capire meglio",
    "Ho atteso più di un'uscita per elaborare un parere",
    "Mi sono preso qualche giorno di rodaggio prima di giudicare",
    "Ho preferito non affrettare il giudizio e aspettare",
    "Ho lasciato decantare l'esperienza prima di esprimermi",
    "Mi sono concesso diverse prove prima di trarre conclusioni",
    "Non mi sono fidato del primo utilizzo, ho aspettato il terzo",
    "Ho voluto farmi un'opinione con calma e con più test",
    "Ho temporeggiato volutamente prima di prendere posizione",
    "Mi sono imposto di aspettare prima di formulare un giudizio",
    "Ho tenuto il parere in sospeso fino a quando non ho avuto certezze",
    "Ho aspettato di avere più dati di esperienza prima di decidere",
    "Mi sono dato un periodo di prova prolungato prima di parlare",
    "Ho atteso che il giudizio si stabilizzasse con l'uso ripetuto",
    "Non ho voluto giudicare in fretta, ho aspettato il momento giusto",
    "Ho preferito accumulare più esperienze prima di esprimere un parere",
    "Ho preso tempo prima di farmi un'idea definitiva",
    "Ci ho messo più uscite del solito prima di pronunciarmi",
    "Ho scelto di non esprimermi al volo e di darmi tempo",
    "Ho preferito lasciare maturare l'opinione con più utilizzi",
    "Ho aspettato di testarli in contesti diversi prima di giudicare",
    "Mi sono preso il lusso di un giudizio lento e ponderato",
    "Ho voluto essere sicuro della mia opinione e ho aspettato",
]
PATTERNS["Ho aspettato qualche uscita prima di farmi un'idea"] = PATTERNS["Ho aspettato qualche uscita prima di farmi un\u2019idea"]

# "Appena aperta la custodia ho capito che non era un paio banale." (37x)
PATTERNS["Appena aperta la custodia ho capito che non era un paio banale."] = [
    "Fin dall'apertura della confezione ho colto qualcosa di diverso.",
    "Al primo contatto si è capito che non era un modello qualsiasi.",
    "Dalla custodia in poi si respirava un certo livello.",
    "Il primo contatto fisico ha subito trasmesso qualità.",
    "Già estraendoli dalla custodia ho percepito un taglio diverso.",
    "L'apertura della scatola ha confermato: è un modello con identità.",
    "Fin dal primo istante la sensazione di qualità era palpabile.",
    "Togliendoli dalla custodia ho capito che avevano qualcosa in più.",
    "Il primo contatto ha comunicato subito una cura non comune.",
    "Dalla custodia alla mano, la sensazione era già diversa dal solito.",
    "Il primo tocco ha detto molto: non è un occhiale banale.",
    "Aprendoli ho avuto subito l'impressione di un prodotto curato.",
    "Il momento dell'unboxing ha dato subito un segnale forte.",
    "Alla prima presa in mano la differenza si è sentita.",
    "Il contatto iniziale ha suggerito che il livello era alto.",
    "Già dalla custodia si intuiva una cura sopra la media.",
    "Il primo approccio ha trasmesso una sensazione di ricercatezza.",
    "Togliendoli dall'astuccio ho avvertito subito una certa presenza.",
    "Il primo tocco ha rivelato un'attenzione fuori dall'ordinario.",
    "Aperta la scatola, il primo sguardo ha confermato che non è roba comune.",
    "Il contatto iniziale è stato eloquente: il livello c'è.",
    "La prima sensazione tattile ha parlato in modo chiaro.",
    "Dalla custodia al naso la qualità non ha mai vacillato.",
    "Il primo istante con loro in mano ha dissipato ogni dubbio.",
    "Sin dalla prima manciata di secondi ho capito che c'era sostanza.",
    "Il primo contatto con il materiale ha dato un'impressione forte.",
    "L'apertura della custodia è stata più eloquente di qualsiasi foto.",
    "Già dal primo sguardo fuori dall'astuccio la qualità si avvertiva.",
    "Prendendoli in mano per la prima volta ho capito che erano speciali.",
    "L'unboxing ha comunicato subito un salto di qualità.",
    "La prima impressione alla mano è stata: questo è un prodotto serio.",
    "Il primo contatto ha stabilito un livello di partenza alto.",
    "Aprendoli ho avvertito subito una personalità marcata.",
    "La custodia aperta ha rivelato subito un prodotto non convenzionale.",
    "Il primo momento è bastato per capire che c'era una marcia in più.",
    "Appena in mano, la qualità si è manifestata con chiarezza.",
    "Sin dall'apertura, il livello era evidente.",
]

# "Non mi interessa mai il colpo di fulmine" (27x)
PATTERNS["Non mi interessa mai il colpo di fulmine"] = [
    "Non cerco mai l'entusiasmo immediato",
    "Non do peso all'impressione istantanea",
    "Non mi fido delle reazioni impulsive",
    "Non bado mai alla prima emozione",
    "L'innamoramento a prima vista non è il mio metro",
    "Non mi lascio guidare dall'impulso del momento",
    "Il giudizio lampo non è il mio stile",
    "Non do valore all'attrazione immediata",
    "Non cerco l'effetto wow del primo secondo",
    "Non sono mai stato uno da primi slanci",
    "Non è la scintilla iniziale che mi interessa",
    "Non mi affido all'istinto del primo contatto",
    "L'impatto istantaneo non mi condiziona",
    "Non cerco emozioni immediate in un acquisto",
    "Non mi convince mai la prima reazione",
    "Non baso il giudizio sulla prima sensazione",
    "L'entusiasmo del momento non è il mio criterio",
    "Non mi interessa il wow: preferisco il ragionamento",
    "Non cerco mai la folgorazione immediata",
    "Non mi fido delle impressioni a caldo",
    "Il fascino istantaneo non mi basta",
    "Non è la reazione veloce che cerco",
    "Non mi lascio abbagliare dall'effetto iniziale",
    "Non valuto mai un occhiale sulla base del primo minuto",
    "L'ammaliamento del primo sguardo non mi tocca",
    "L'attrazione immediata non è mai stata il mio criterio",
    "Non mi seduce la prima impressione: preferisco la seconda",
]

# "Non sono uno che cambia occhiali ogni mese." (27x)
PATTERNS["Non sono uno che cambia occhiali ogni mese."] = [
    "Non faccio parte di chi rinnova gli occhiali in continuazione.",
    "Sono piuttosto fedele ai miei occhiali e ne cambio pochi.",
    "Non ho l'abitudine di ruotare i modelli spesso.",
    "Tengo i miei occhiali a lungo, non sono un collezionista.",
    "Non faccio acquisti impulsivi in fatto di occhiali.",
    "Quando trovo un paio che funziona, lo tengo.",
    "Non appartengo alla categoria di chi cambia modello ogni stagione.",
    "Compro occhiali con la parsimonia di chi sa cosa vuole.",
    "Non sono un consumatore seriale di montature.",
    "La mia rotazione di occhiali è molto lenta.",
    "Non spendo in occhiali leggero: ogni acquisto è pesato.",
    "Scelgo pochi modelli e li uso davvero.",
    "Non inseguo la novità in fatto di occhiali.",
    "I miei acquisti di montature si contano sulle dita.",
    "Non vivo il cambio di occhiali come un evento frequente.",
    "Compro poco e uso tanto, in fatto di occhiali.",
    "Non appartengo al mondo di chi accumula montature.",
    "I miei occhiali durano anni, non settimane.",
    "Non sono uno che compra per il gusto di comprare.",
    "In fatto di occhiali vado sul sicuro e sul duraturo.",
    "La mia relazione con gli occhiali è monogama e lenta.",
    "Non mi butto sulle novità: aspetto e poi scelgo con cura.",
    "La mia frequenza di acquisto è bassa e ragionata.",
    "Non seguo le tendenze a ogni stagione.",
    "Preferisco pochi paia e usarli bene.",
    "Non faccio shopping di occhiali a cuor leggero.",
    "Sono selettivo e compro con il contagocce.",
]

# "Sono entrato nella prova con un pregiudizio e" (27x)
PATTERNS["Sono entrato nella prova con un pregiudizio e"] = [
    "Avevo un'idea preconcepita e",
    "Partivo con un giudizio già formato e",
    "Il mio pregiudizio era forte prima della prova e",
    "Avevo un'opinione preconfezionata e",
    "Mi sono avvicinato con un'idea fissa in testa e",
    "Il mio parere era già scritto prima di provarli e",
    "Entravo nel test con un bias evidente e",
    "Il pregiudizio che avevo era robusto e",
    "Mi ero già fatto un'idea, probabilmente sbagliata, e",
    "Partivo con un preconcetto solido e",
    "La mia posizione era già orientata prima del test e",
    "Avevo un filtro mentale prima di provarli e",
    "Non ero neutro all'inizio, avevo già un parere, e",
    "Il mio punto di partenza era viziato e",
    "Arrivavo alla prova con un giudizio predefinito e",
    "Il mio sguardo non era imparziale all'inizio e",
    "Portavo con me aspettative condizionate e",
    "Il mio approccio iniziale era condizionato e",
    "Non partivo da zero, avevo un'inclinazione e",
    "La mia visione era già parziale prima del test e",
    "Avevo un quadro mentale che non era obiettivo e",
    "Il mio giudizio era già influenzato prima della prova e",
    "Avevo un'opinione prima ancora di indossarli e",
    "Partivo con un angolo precostituito e",
    "C'era un pregiudizio che mi accompagnava e",
    "Non nascondo un bias iniziale e",
    "Avevo preso posizione prima della prova e",
]

# "All'inizio li guardavo con curiosità più che con" (26x)
PATTERNS["All\u2019inizio li guardavo con curiosit\u00e0 pi\u00f9 che con"] = [
    "All'inizio il mio interesse era più da osservatore che da",
    "All'inizio provavo più curiosità che reale",
    "All'inizio il mio approccio era più esplorativo che legato a",
    "All'inizio c'era più indagine che vera",
    "All'inizio mi muoveva più la curiosità che la",
    "All'inizio la mia attitudine era più di studio che di",
    "All'inizio l'atteggiamento era più analitico che di",
    "All'inizio mi affascinavano più per indagine che per",
    "All'inizio li osservavo con più distacco che",
    "All'inizio era più un esperimento che una vera",
    "All'inizio il rapporto era più di esplorazione che di",
    "All'inizio il mio sguardo era più curioso che",
    "All'inizio li studiavo più che viverli con",
    "All'inizio c'era più ricerca intellettuale che",
    "Al principio mi spingeva la curiosità più che la",
    "All'avvio l'approccio era più investigativo che di",
    "In principio mi guidava l'interesse più che la",
    "Inizialmente li osservavo con più spirito di scoperta che",
    "Da principio la mia motivazione era più la curiosità che la",
    "In origine il mio rapporto con loro era più di studio che di",
    "All'inizio provavo più fascinazione intellettuale che vera",
    "All'inizio mi incuriosivano più che convincermi con",
    "All'inizio il mio interesse era più cerebrale che",
    "All'inizio li approcciavo con più domande che",
    "All'inizio c'era più voglia di capire che reale",
    "All'inizio il mio atteggiamento era più di ricognizione che di",
]
PATTERNS["All'inizio li guardavo con curiosit\u00e0 pi\u00f9 che con"] = PATTERNS["All\u2019inizio li guardavo con curiosit\u00e0 pi\u00f9 che con"]

# "Sono di quei modelli che vanno raccontati dopo" (26x)
PATTERNS["Sono di quei modelli che vanno raccontati dopo"] = [
    "Appartengono a quella categoria di occhiali che si apprezzano dopo",
    "Rientrano fra quei paia che si capiscono solo dopo",
    "Fanno parte dei modelli che richiedono tempo per essere",
    "Sono nel gruppo di occhiali che vanno vissuti prima di essere",
    "Appartengono alla famiglia dei modelli da capire dopo",
    "Rientrano in quella fascia di prodotti che parlano solo dopo",
    "Sono il tipo di occhiale che si giudica dopo",
    "Vanno catalogati fra i modelli che si comprendono dopo",
    "Fanno parte di quella schiera di modelli che maturano dopo",
    "Sono fra quelli che necessitano tempo per",
    "Appartengono a quei modelli che chiedono pazienza prima di",
    "Rientrano nella casistica dei modelli che vanno digeriti dopo",
    "Vanno messi fra quelli che si rivelano solo dopo",
    "Sono nel novero di quei modelli che emergono dopo",
    "Rientrano fra quelli che hanno bisogno di",
    "Appartengono ai modelli che non si lasciano giudicare prima di",
    "Fanno parte degli occhiali che si aprono solo dopo",
    "Sono il genere di modello che si svela dopo",
    "Vanno inseriti fra quelli che richiedono più di",
    "Appartengono a quei paio che maturano solo dopo",
    "Rientrano in quella categoria che ha bisogno di",
    "Sono fra i modelli che non parlano subito ma dopo",
    "Vanno annoverati fra quelli che necessitano di",
    "Sono del tipo che va raccontato con calma, dopo",
    "Appartengono ai modelli che si svelano gradualmente dopo",
    "Rientrano fra i modelli il cui valore emerge solo dopo",
]

# Restanti incipit meno frequenti
PATTERNS["Non cerco mai l\u2019effetto influencer, cerco il paio"] = [
    "Non inseguo il trend social, voglio il paio",
    "Non mi interessa l'effetto vetrina, cerco il paio",
    "Non rincorro il look da post, cerco il paio",
    "Non punto all'occhiale da Instagram, cerco il paio",
    "Non inseguo la visibilità dello stile, cerco il paio",
    "Non sto dietro alle mode virali, cerco il paio",
    "Non mi serve l'effetto social, cerco il paio",
    "Non cerco l'appeal da contenuto, cerco il paio",
    "Non rincorro tendenze digitali, cerco il paio",
    "Non voglio il modello da like, cerco il paio",
    "Non mi entusiasma il modello del momento, cerco il paio",
    "Non compro per fare scena, cerco il paio",
    "Non seguo le mode passeggere, cerco il paio",
    "Non inseguo cosa va di moda online, cerco il paio",
    "Non cerco il modello più fotogenico, cerco il paio",
    "Non mi muovo per le tendenze, cerco il paio",
    "Non voglio l'occhiale del momento, cerco il paio",
    "Non seguo il gusto della massa, cerco il paio",
]
PATTERNS["Non cerco mai l'effetto influencer, cerco il paio"] = PATTERNS["Non cerco mai l\u2019effetto influencer, cerco il paio"]

PATTERNS["Non compro per collezione, compro per uso reale."] = [
    "Non accumulo modelli, acquisto per usarli.",
    "Non colleziono occhiali, li compro per portarli.",
    "Non faccio incetta di montature, compro per necessità d'uso.",
    "Il mio non è collezionismo, è acquisto mirato.",
    "Non compro per avere, compro per indossare.",
    "Non mi interessa accumulare, mi interessa usare.",
    "Non sono un collezionista ma un utilizzatore.",
    "Non aggiungo per il gusto di aggiungere, scelgo per usare.",
    "Ogni mio acquisto è pensato per l'uso quotidiano.",
    "Non acquisto per riempire un cassetto, acquisto per vivere.",
    "Il mio criterio è pratico, non da collezionista.",
    "Non mi attira il possesso fine a sé stesso.",
    "Ognuno dei miei occhiali deve guadagnarsi il proprio spazio.",
    "Non sono tipo da vetrina, sono tipo da uso vero.",
]

PATTERNS["Ho un viso che non perdona molto e"] = [
    "I miei lineamenti sono esigenti in fatto di montature e",
    "La geometria del mio viso è selettiva e",
    "Non tutti i modelli funzionano sul mio viso e",
    "Ho tratti del viso che filtrano duramente i modelli e",
    "Il mio volto è piuttosto critico con gli occhiali e",
    "Le proporzioni del mio viso sono impietose con certi modelli e",
    "Il mio viso fa una scrematura brutale sui modelli e",
    "Ho lineamenti che mettono a dura prova le montature e",
    "Il mio viso è poco indulgente con la maggior parte degli occhiali e",
    "I miei tratti sono piuttosto severi con le montature e",
    "La struttura del mio viso è un banco di prova impegnativo e",
    "Ho un tipo di viso che mette in difficoltà molti modelli e",
    "Le mie proporzioni facciali sono esigenti e",
    "Ho lineamenti che chiedono molto alle montature e",
]

PATTERNS["Di solito capisco subito se un paio mi"] = [
    "In genere il mio giudizio su un occhiale si forma in fretta e mi",
    "Normalmente non ho bisogno di molto per sapere se mi",
    "Di solito mi basta poco per capire se un modello mi",
    "Solitamente il feeling con un paio di occhiali è immediato e mi",
    "In genere riconosco subito se un modello mi",
    "Di norma la mia reazione iniziale è già indicativa e mi",
    "La mia capacità di giudizio rapido sugli occhiali in genere mi",
    "Generalmente il mio istinto su un paio di occhiali mi",
    "Quasi sempre so subito se un occhiale mi",
    "Il mio primo istinto con gli occhiali di solito mi",
    "In genere il primo impatto mi dice già se mi",
    "Normalmente il mio giudizio è rapido e mi",
    "Di solito non ho bisogno di riflettere a lungo per sapere se mi",
]

PATTERNS["A forza di provarne, ho capito che il"] = [
    "Dopo tante prove, ho imparato che il",
    "L'esperienza accumulata mi ha insegnato che il",
    "Provandone molti, ho realizzato che il",
    "Con il tempo ho capito che il",
    "Anni di prove mi hanno insegnato che il",
    "La pratica mi ha mostrato che il",
    "L'esperienza diretta mi ha fatto capire che il",
    "Dopo molte montature, so ormai che il",
    "A forza di tentativi, ho compreso che il",
    "Tanti acquisti mi hanno insegnato che il",
    "La lunga esperienza mi ha fatto vedere che il",
]

PATTERNS["Io parto sempre malissimo con i modelli troppo"] = [
    "Il mio rapporto con i modelli troppo",
    "Con i modelli troppo",
    "I modelli troppo",
    "Non vado mai d'accordo con i modelli troppo",
    "Fatico sempre all'inizio con i modelli troppo",
    "Do per persi in partenza i modelli troppo",
    "Ho un problema ricorrente con i modelli troppo",
    "I modelli troppo",
    "Non ho mai un buon feeling iniziale con i modelli troppo",
    "La mia diffidenza è massima verso i modelli troppo",
    "Parto sempre male quando un modello è troppo",
]

PATTERNS["Ho quarantadue anni e di solito diffido dei"] = [
    "Alla mia età ho imparato a diffidare dei",
    "Con gli anni ho sviluppato una certa diffidenza verso i",
    "L'esperienza mi ha reso scettico verso i",
    "Da uomo maturo, tendo a diffidare dei",
    "Con il tempo ho imparato a essere cauto con i",
    "Negli anni ho sviluppato una prudenza particolare verso i",
    "La mia età mi rende naturalmente diffidente verso i",
    "Con il passare degli anni sono diventato guardingo verso i",
    "L'età mi ha insegnato a non fidarmi dei",
    "Da quarantenne navigato, ho imparato a guardare con sospetto i",
    "A quest'età ho sviluppato un filtro particolare verso i",
]

PATTERNS["Ho gusti abbastanza selettivi e faccio pochi acquisti"] = [
    "Sono piuttosto esigente e compro con parsimonia",
    "I miei standard sono alti e gli acquisti rari",
    "Seleziono con cura e compro poco",
    "Sono molto selettivo nelle scelte e acquisto di rado",
    "Ho criteri stringenti e la mia frequenza d'acquisto è bassa",
    "Scelgo con grande attenzione e compro pochissimo",
    "I miei gusti sono raffinati e gli acquisti contati",
    "Compro raramente, ma quando lo faccio sono molto esigente",
    "Il mio metro è severo e i miei acquisti pochi",
    "Sono di gusti precisi e acquisto con il contagocce",
]

PATTERNS["Mi conosco: se un occhiale mi complica la"] = [
    "So per esperienza che se un occhiale rende difficile la",
    "Ormai lo so: se un modello mi complica la",
    "Mi conosco abbastanza da sapere che se un occhiale interferisce con la",
    "Ho imparato che se un paio di occhiali mi rende complicata la",
    "So come funziono: se un occhiale mi appesantisce la",
    "So per certo che se un modello mi ostacola la",
    "Mi conosco bene: se un occhiale mi disturba la",
    "L'esperienza mi dice che se un modello compromette la",
    "So cosa funziona per me: se un occhiale intralcia la",
    "Ho chiaro in testa che se un modello mi rallenta la",
]

print("Parte 3 caricata: totale " + str(len(PATTERNS)) + " pattern definiti")
for k, v in PATTERNS.items():
    print(f"  {len(v):3d} alt. per: {k[:50]}")
