#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Parte 5: Pattern residui a media frequenza (20–28x)
"""
from rewrite_reviews_part4 import PATTERNS

# ═══════════════════════════════════════════════════════════
# CHIUSURE 5 STELLE (≥20x)
# ═══════════════════════════════════════════════════════════

# "Quando succede così, non c'è molto da discutere: promosso pienamente." (26x)
PATTERNS["Quando succede cos\u00ec, non c\u2019\u00e8 molto da discutere: promosso pienamente."] = [
    "A quel punto il verdetto è scontato: promosso con merito.",
    "Di fronte a risultati così, il giudizio si scrive da solo.",
    "I fatti parlano da soli: merita la promozione piena.",
    "Se le cose stanno così, non servono molte parole: promosso.",
    "Dato il quadro, la promozione è automatica.",
    "Con questi presupposti il verdetto non ammette dubbi.",
    "A queste condizioni, il giudizio positivo è inevitabile.",
    "Quando tutto quadra così, il voto positivo è scontato.",
    "Con una resa simile la promozione viene naturale.",
    "Se la resa è questa, il verdetto è uno solo: piena promozione.",
    "Di fronte a una tale costanza, il giudizio è inequivocabile.",
    "Con un risultato così il verdetto è evidente.",
    "A questi livelli di soddisfazione, la promozione è dovuta.",
    "Se l'esperienza conferma così, il giudizio non necessita di esitazioni.",
    "Il quadro che emerge porta a un'unica conclusione: promosso.",
    "Quando la coerenza è questa, la promozione è l'unica risposta logica.",
    "La resa parla chiaro: il giudizio è nettamente positivo.",
    "Con un bilancio che torna così bene, il verdetto è ovvio.",
    "Di fronte a un'esperienza come questa, il giudizio è una formalità.",
    "Se tutto converge in positivo, la promozione è la sola conclusione.",
    "Quando i fatti sono così netti, il verdetto si scrive da sé.",
    "Se i risultati sono questi, la promozione è una conseguenza naturale.",
    "Il bilancio è così chiaro che il verdetto si impone.",
    "Quando la resa è a questo livello, il giudizio è una mera formalità.",
    "Di fronte a questi risultati, non c'è margine di dubbio.",
    "A queste condizioni, il sì è pieno e convinto.",
]
PATTERNS["Quando succede cos\u00ec, non c'\u00e8 molto da discutere: promosso pienamente."] = PATTERNS["Quando succede cos\u00ec, non c\u2019\u00e8 molto da discutere: promosso pienamente."]

# "Alla fine il bilancio per me è positivo, anche con qualche riserva concreta." (26x)
PATTERNS["Alla fine il bilancio per me \u00e8 positivo, anche con qualche riserva concreta."] = [
    "Nel complesso il giudizio è favorevole, pur con alcune riserve.",
    "Il bilancio finale pende dalla parte giusta, nonostante qualche appunto.",
    "Tutto considerato, il mio giudizio resta positivo malgrado qualche distinzione.",
    "Tirando le somme, il saldo è positivo anche se non privo di osservazioni.",
    "In definitiva il giudizio propende per il positivo, con qualche ma.",
    "Il verdetto complessivo è favorevole, pur con alcune note di riserva.",
    "A consuntivo il bilancio è positivo, anche se non senza annotazioni.",
    "Nel bilancio la mia valutazione complessiva resta positiva, con dei se.",
    "Il quadro generale è positivo, anche se non senza distinguo.",
    "La somma dei pro e dei contro dà un risultato positivo con riserve.",
    "In sintesi il mio verdetto è favorevole, ma non incondizionato.",
    "Il bilancio totale è positivo, pur conservando qualche appunto.",
    "In conclusione il giudizio propende per il bene, con qualche caveat.",
    "Il mio giudizio definitivo è positivo, seppur con delle sfumature.",
    "La valutazione complessiva è positiva, anche se non priva di riserve.",
    "Tutto sommato il bilancio è in attivo, anche se con qualche nota.",
    "Il saldo finale è positivo, seppure non assoluto.",
    "Il quadro di insieme pende verso il positivo, con qualche precisazione.",
    "In definitiva il mio giudizio è favorevole, ma con le dovute riserve.",
    "A conti fatti il bilancio è positivo, senza però essere privo di osservazioni.",
    "Il giudizio finale è positivo, con la precisazione di qualche limite.",
    "Il bilancio definitivo è favorevole, anche se annoterei qualche riserva.",
    "Tutto pesato, il saldo resta favorevole con qualche asterisco.",
    "Il conteggio finale è positivo, anche se con qualche nota in calce.",
    "Il mio verdetto conclusivo è positivo, accompagnato da qualche osservazione.",
    "Il bilancio è per me positivo, con qualche avvertenza.",
]

# "Lo promuovo senza esitazioni, con la sola avvertenza che va capito prima di essere davvero amato." (25x)
PATTERNS["Lo promuovo senza esitazioni, con la sola avvertenza che va capito prima di essere davvero amato."] = [
    "Lo consiglio pienamente, con la nota che richiede tempo per apprezzarlo fino in fondo.",
    "Lo approvo senza riserve, sapendo che chiede un minimo di comprensione iniziale.",
    "Lo promuovo con convinzione, avvertendo che non è un amore a prima vista.",
    "Lo raccomando senza dubbi, ma va dato tempo di svelare le sue qualità.",
    "Lo promuovo convintamente; unica nota: richiede un po' di pazienza per amarlo.",
    "Promosso senza riserve, con il consiglio di dargli tempo di esprimersi.",
    "Lo promuovo totalmente, con la nota che il suo valore emerge con la conoscenza.",
    "Lo consiglio senza esitare, suggerendo di dargli il tempo di farlo crescere.",
    "Lo promuovo pienamente, ma chi se lo avvicina sappia che chiede pazienza.",
    "Promozione piena, ma va compreso prima di innamorarsene.",
    "Lo consiglio con convinzione, con l'avvertenza che matura nel tempo.",
    "Lo promuovo senza dubbi, precisando che l'amore arriva con l'uso.",
    "Lo approvo totalmente, ma va saputo che rivela il suo meglio nel tempo.",
    "Lo consiglio vivamente, ma con la nota che non è immediato.",
    "Promuovo senza esitazioni, con il consiglio di non valutarlo solo al primo impatto.",
    "Lo promuovo pienamente, ricordando che va vissuto per essere apprezzato davvero.",
    "Lo consiglio senza riserve, specificando che premia chi gli dà tempo.",
    "Lo approvo con decisione, segnalando che la bellezza si rivela con l'uso.",
    "Lo promuovo a pieni voti, ma il suo fascino chiede un po' di pazienza.",
    "Lo consiglio senza alcun dubbio, con il monito di non giudicarlo subito.",
    "Promozione totale, con l'annotazione che va conosciuto prima di innamorarsi.",
    "Lo consiglio caldamente, avvertendo che il meglio lo dà col tempo.",
    "Lo promuovo pienamente, con la sola nota che non va giudicato dalla prima prova.",
    "Lo consiglio con la sola avvertenza di dargli più di un'occasione.",
    "Promosso senza riserve, ma la piena soddisfazione arriva comprendendolo.",
]

# "Gli manca poco per convincermi del tutto." (24x)
PATTERNS["Gli manca poco per convincermi del tutto."] = [
    "È a un passo dal convincermi completamente.",
    "Manca davvero poco per un giudizio pieno.",
    "Siamo vicini alla promozione totale, ma non ci siamo ancora.",
    "Il traguardo della piena convinzione è quasi raggiunto.",
    "Manca un ultimo tassello per il mio sì pieno.",
    "È quasi del tutto convincente, gli serve un ultimo passo.",
    "Il margine che lo separa dal giudizio pieno è ridotto.",
    "Ci siamo quasi: manca poco per la mia approvazione totale.",
    "Un ultimo dettaglio e sarebbe stato un sì senza riserve.",
    "Lo spazio che lo separa dalla promozione piena è minimo.",
    "Ci vuole poco per passare dal quasi al sì totale.",
    "Siamo a un soffio dalla piena convinzione.",
    "Il gap verso la piena soddisfazione è davvero modesto.",
    "Manca un niente per il mio giudizio incondizionato.",
    "È molto vicino a convincermi del tutto.",
    "La distanza dalla piena promozione è minima.",
    "Un passo ancora e sarebbe stato il sì pieno.",
    "Manca pochissimo per arrivare alla piena approvazione.",
    "Lo scarto dalla piena convinzione è ridotto all'osso.",
    "È a un soffio dal voto pieno.",
    "Poca cosa lo separa dal giudizio totalmente positivo.",
    "Quasi ci siamo: il gap con la promozione piena è sottile.",
    "Il dettaglio che manca per il sì pieno è piccolo.",
    "Manca una sfumatura per il mio giudizio completo.",
]

# "Resto in quella zona grigia in cui apprezzo più di quanto desideri." (24x)
PATTERNS["Resto in quella zona grigia in cui apprezzo pi\u00f9 di quanto desideri."] = [
    "Mi trovo in quel limbo in cui l'apprezzamento supera la voglia di portarlo.",
    "Sono in quella fascia dove il rispetto è più alto del desiderio.",
    "Mi colloco in un territorio dove lo stimo più di quanto lo scelga.",
    "Sono in quell'area in cui il giudizio è positivo ma l'impulso di usarlo è tiepido.",
    "Resto in un punto dove la stima supera l'entusiasmo di indossarlo.",
    "Mi trovo dove l'apprezzamento razionale eccede la voglia pratica.",
    "Sono in quella fascia dove il rispetto c'è ma la voglia di indossarlo è moderata.",
    "Resto in un'area dove lo stimo senza sentirne il richiamo forte.",
    "Mi colloco dove il mio giudizio è migliore della mia frequenza d'uso.",
    "Sono in quel punto dove lo apprezzo più che desiderarlo.",
    "Mi trovo in quella zona dove la stima è più alta della voglia.",
    "Resto dove il riconoscimento supera l'attrazione pratica.",
    "Mi posiziono in un limbo quanto lo apprezzo più di quanto lo senta mio.",
    "Sono in quell'area dove il giudizio positivo non si traduce in desiderio.",
    "Resto in un punto dove la valutazione è più alta dell'impulso di portarlo.",
    "Mi trovo dove lo stimo intellettualmente più di quanto lo scelga istintivamente.",
    "Sono in quella fascia dove il rispetto supera la frequentazione.",
    "Mi colloco dove lo apprezzo senza che diventi una priorità nel cassetto.",
    "Resto in un territorio dove la stima è concreta ma il desiderio meno.",
    "Mi trovo dove il mio apprezzamento non si traduce in uso assiduo.",
    "Sono in quella zona dove il giudizio è generoso ma la scelta quotidiana meno.",
    "Resto dove la mia opinione è alta ma il mio uso non la rispecchia.",
    "Mi muovo in un limbo dove stimo più che indosso.",
    "Mi trovo in un'area di apprezzamento senza urgenza di portarlo.",
]

# "Mi piace e lo porto, anche se non è il paio che affiderei a chiunque." (24x)
PATTERNS["Mi piace e lo porto, anche se non \u00e8 il paio che affiderei a chiunque."] = [
    "Lo apprezzo e lo uso, anche se non lo consiglierei indiscriminatamente.",
    "Mi piace e lo indosso, pur sapendo che non è per tutti.",
    "Lo gradisco e lo scelgo, anche se non è universale.",
    "Lo porto con piacere, pur consapevole che non è adatto a chiunque.",
    "Lo uso volentieri, anche se non lo raccomanderei a tutti.",
    "Mi piace e lo indosso regolarmente, ma non è un modello per ogni viso.",
    "Lo apprezzo per me, pur sapendo che non è un consiglio universale.",
    "Lo porto e lo scelgo, anche se non è una scelta per tutti.",
    "Mi soddisfa e lo uso, anche se non lo consiglierei a chiunque.",
    "Lo indosso con soddisfazione, pur consapevole che è una scelta personale.",
    "Lo porto e mi piace, anche se il consiglio non sarebbe per tutti.",
    "Lo scelgo volentieri per me, anche se non per tutti.",
    "Mi ci trovo bene e lo uso, pur sapendo che non è per chiunque.",
    "Lo apprezzo e lo porto, ma non è il tipo di modello che consiglio a tutti.",
    "Lo uso e ne sono contento, anche se non è per ogni tipo di viso.",
    "Mi piace indossarlo, pur non considerandolo un consiglio per chiunque.",
    "Lo porto con piacere, anche se la raccomandazione non è generalizzabile.",
    "Lo uso con soddisfazione, ma non lo suggerirei a tutti.",
    "Mi piace e fa parte della mia rotazione, anche se non per tutti i visi.",
    "Lo scelgo regolarmente, pur non considerandolo universale.",
    "Lo porto e mi piace, anche se non è un consiglio da dare a chiunque.",
    "Lo apprezzo e lo scelgo spesso, pur sapendo che non è per ogni persona.",
    "Lo indosso con piacere, anche se non per tutti sarebbe lo stesso.",
    "Mi piace e continuo a portarlo, ma evito di consigliarlo indistintamente.",
]

# "Non lo sento come un semplice accessorio, ma come una parte del look che ordina tutto il resto." (24x)
PATTERNS["Non lo sento come un semplice accessorio, ma come una parte del look che ordina tutto il resto."] = [
    "Non è un accessorio ma il perno che dà coerenza a tutto il look.",
    "Lo percepisco come il fulcro attorno a cui costruisco il resto dell'outfit.",
    "Non è un complemento: è l'elemento che detta la direzione di tutto il look.",
    "Lo sento come un pezzo chiave, non come un dettaglio secondario.",
    "Per me non è un accessorio qualsiasi: è ciò che organizza il mio stile.",
    "Non è un contorno: è il pezzo che tiene insieme tutto il resto.",
    "Lo considero il baricentro del look, non un semplice complemento.",
    "Non è un dettaglio: è l'elemento che dà senso al resto.",
    "Lo percepisco come il cardine del mio look, non come un ornamento.",
    "Non è un accessorio passivo: è ciò che struttura il mio stile.",
    "Lo sento come la colonna che regge tutto il look.",
    "Non lo vivo come un semplice ornamento ma come il punto fermo del mio outfit.",
    "Per me funziona come un regista silenzioso che ordina il tutto.",
    "Non è un dettaglio perso nel look: è ciò che lo definisce.",
    "Lo uso come elemento portante, non come aggiunta.",
    "Non è un complemento qualsiasi: dà il tono a tutto il resto.",
    "Lo vedo come il pezzo attorno a cui orbita il resto del look.",
    "Non è un accessorio: è l'elemento che porta coesione.",
    "Lo sento come il filo conduttore del mio stile quotidiano.",
    "Per me è il pezzo che organizza visivamente tutto il resto.",
    "Non è un semplice ornamento: è il pilastro del mio look.",
    "Lo percepisco come l'asse attorno a cui ruota il mio outfit.",
    "Non è un dettaglio marginale: è ciò che governa l'intero look.",
    "Lo vivo come l'elemento che dà struttura a tutto il resto.",
]

# "Resta un ottimo acquisto, semplicemente non totalmente universale." (23x)
PATTERNS["Resta un ottimo acquisto, semplicemente non totalmente universale."] = [
    "Rimane un grande acquisto, solo non per tutti.",
    "È un acquisto eccellente, non universale.",
    "Resta una scelta di qualità, non per ogni viso.",
    "Un ottimo acquisto, che richiede però la giusta compatibilità.",
    "Acquisto validissimo, non generalizzabile però.",
    "È un acquisto di alto livello, che non è per chiunque.",
    "Resta un'ottima scelta, con la premessa della giusta vestibilità.",
    "Acquisto eccellente per chi ci sta bene; non universale.",
    "Un acquisto di qualità, parzialmente soggettivo nella vestibilità.",
    "Rimane un gran bell'acquisto, a patto di avere il viso giusto.",
    "Acquisto riuscito, anche se non per tutti i volti.",
    "Resta una scelta di altissimo livello, semplicemente non per ogni persona.",
    "Un ottimo acquisto, con la premessa che va provato sul proprio viso.",
    "È un acquisto valido, anche se non consigliabile indiscriminatamente.",
    "Un gran bel prodotto, non per ogni profilo facciale.",
    "Resta un acquisto molto positivo, anche se non per chiunque.",
    "Un acquisto eccellente, che non pretende di essere per tutti.",
    "Resta un ottimo prodotto, che va valutato in base alla propria morfologia.",
    "Un acquisto di spessore, non trasversale a qualsiasi viso.",
    "Rimane una scelta di grande qualità, non adatta in modo universale.",
    "Un acquisto brillante, ma non per ogni tipologia di volto.",
    "Rimane un gran prodotto, con il limite della vestibilità personale.",
    "Acquisto di prim'ordine, anche se non per tutti.",
]

# "È il genere di acquisto che mi fa venire voglia di uscire solo per indossarlo." (23x)
PATTERNS["\u00c8 il genere di acquisto che mi fa venire voglia di uscire solo per indossarlo."] = [
    "Mi fa venire voglia di uscire solo per poterlo portare.",
    "È il tipo di acquisto che crea l'occasione per essere indossato.",
    "Mi spinge a uscire solo per il piacere di portarlo.",
    "Crea la voglia di uscire, non il bisogno: è l'acquisto che motiva.",
    "È il tipo di acquisto che mi fa cercare scuse per metterlo.",
    "Mi inventa motivi per uscire solo per portarlo.",
    "È un acquisto che genera occasioni: esco per il gusto di indossarlo.",
    "Mi fa inventare impegni per avere una ragione di portarlo fuori.",
    "Il piacere di indossarlo genera la voglia di uscire.",
    "È l'acquisto che trasforma una giornata qualsiasi in un'occasione.",
    "Mi fa organizzare uscite che prima non avrei fatto solo per portarlo.",
    "È il tipo di paio che mi fa trovare pretesti per andare fuori.",
    "Ogni uscita diventa una scusa per indossarlo.",
    "Mi dà un motivo in più per uscire la mattina.",
    "È quell'acquisto che rende le uscite più motivanti.",
    "Mi invoglia a uscire per il solo piacere di averlo addosso.",
    "La voglia di portarlo genera uscite che altrimenti eviterei.",
    "È il tipo di acquisto che aggiunge motivazione alle mie giornate.",
    "Mi fa venire voglia di cercare ogni pretesto per portarlo fuori.",
    "È un acquisto che crea occasioni d'uso per sé stesso.",
    "Esce con me più spesso di quanto servisse, perché me ne dà voglia.",
    "Mi fa desiderare di uscire ogni giorno solo per indossarlo.",
    "È il tipo di paio che rende ogni uscita un pretesto piacevole.",
]

# "Mi lascia quella soddisfazione rara di aver scelto qualcosa con un'identità precisa." (23x)
PATTERNS["Mi lascia quella soddisfazione rara di aver scelto qualcosa con un\u2019identit\u00e0 precisa."] = [
    "Mi dà la soddisfazione di aver scelto qualcosa con un carattere distinto.",
    "Ha quell'identità chiara che rende la scelta particolarmente soddisfacente.",
    "La soddisfazione sta nel riconoscere un'identità precisa nella mia scelta.",
    "Mi gratifica sapere di aver scelto un modello con una personalità definita.",
    "L'appagamento viene dal sapere di aver puntato su un carattere specifico.",
    "Mi regala quella rara soddisfazione di aver scelto con criterio.",
    "La gioia più grande è aver trovato un modello dalla personalità netta.",
    "Mi piace sapere che ho scelto qualcosa con un'anima propria.",
    "Dà la soddisfazione di avere tra le mani un prodotto con una direzione chiara.",
    "Mi lascia contento di aver scelto un modello con un'identità inconfondibile.",
    "La soddisfazione viene dalla coerenza e dall'identità precisa di questa scelta.",
    "Mi gratifica il fatto di aver scelto qualcosa che sa chi è.",
    "Ha una personalità definita che rende l'acquisto particolarmente gratificante.",
    "Mi appaga sapere che il mio acquisto ha un carattere netto.",
    "L'identità chiara del modello rende questa scelta speciale.",
    "Mi regala la soddisfazione di aver scelto qualcosa di unico e definito.",
    "Poche scelte danno la stessa gratificazione di un modello con personalità.",
    "Il senso di soddisfazione nasce dalla precisa identità della mia scelta.",
    "È raro trovare un modello con un'identità così chiara: e dà soddisfazione.",
    "Mi compiaccio di aver scelto un modello che ha qualcosa da dire.",
    "La soddisfazione più grande è aver puntato su un modello con carattere.",
    "Il piacere della scelta sta nell'identità forte e chiara del modello.",
    "Mi lascia appagato sapere di aver scelto qualcosa con una voce propria.",
]
PATTERNS["Mi lascia quella soddisfazione rara di aver scelto qualcosa con un'identit\u00e0 precisa."] = PATTERNS["Mi lascia quella soddisfazione rara di aver scelto qualcosa con un\u2019identit\u00e0 precisa."]

# ═══════════════════════════════════════════════════════════
# CHIUSURE 2-3 STELLE (≥20x)
# ═══════════════════════════════════════════════════════════

# "Non è amore cieco, ma è un sì convinto." (22x)
PATTERNS["Non \u00e8 amore cieco, ma \u00e8 un s\u00ec convinto."] = [
    "Non è fanatismo, ma è un giudizio decisamente positivo.",
    "Non lo idealizzo, ma lo approvo con decisione.",
    "Non è venerazione, ma è una promozione convinta.",
    "Non è infatuazione, ma è un parere solidamente positivo.",
    "Non è un amore totalizzante, ma il sì è fermo.",
    "Non è passione cieca, ma è riconoscimento sincero.",
    "Non è idolatria, ma è un giudizio convintamente favorevole.",
    "Non è un colpo di fulmine, ma è un sì ben ragionato.",
    "Non è fascino acritico, ma è un'approvazione completa.",
    "Non è devozione, ma è un appoggio pieno.",
    "Non è il mio amore, ma è un prodotto che promuovo con forza.",
    "Non è un'infatuazione a ogni costo, ma è un parere decisamente positivo.",
    "Non è adorazione, ma è un giudizio che non ammette incertezze.",
    "Non è un amore irrazionale, ma è un sì solido.",
    "Non è un entusiasmo cieco, ma è un consenso dato con lucidità.",
    "Non è una venerazione, ma il giudizio è ampiamente positivo.",
    "Non è amore assoluto, ma è un sì genuino e convinto.",
    "Non è fanatismo da fan, ma la promozione è piena.",
    "Non è un'adorazione, ma è un'approvazione data con convinzione.",
    "Non è una passione cieca, ma è un verdetto molto favorevole.",
    "Non è un amore totale, ma il sì è forte e deciso.",
    "Non è dedizione assoluta, ma la stima è alta.",
]

# "Non è un disastro concettuale, è un disastro di compatibilità." (21x)
PATTERNS["Non \u00e8 un disastro concettuale, \u00e8 un disastro di compatibilit\u00e0."] = [
    "Il progetto non è sbagliato: è la compatibilità con me a non funzionare.",
    "Come idea va bene: il problema è che non sta bene a me.",
    "Il design non ha colpe: la resa sul mio viso sì.",
    "Non è il concetto che fallisce: è come calza su di me.",
    "L'errore non è nel progetto ma nella compatibilità col mio viso.",
    "L'idea è buona: ciò che non funziona è il modo in cui mi veste.",
    "Non condanno il design: condanno la resa sul mio volto.",
    "Il modello in sé non ha problemi: il problema è il mio viso.",
    "Non è un fallimento di design: è un'incompatibilità anatomica.",
    "Il progetto non è da buttare: la vestibilità su di me sì.",
    "L'idea non è sbagliata: la resa pratica sul mio viso lo è.",
    "Il concetto merita: la compatibilità col mio volto no.",
    "Non è il modello ad essere sbagliato: è la mia faccia a non essere giusta per lui.",
    "Il design ha i suoi meriti: la vestibilità sul mio viso no.",
    "Non è un errore di progettazione: è un errore di compatibilità.",
    "L'idea è solida: il problema è tutto nella resa sul mio volto.",
    "Non è la filosofia del modello che boccia: è come sta su di me.",
    "Sul piano concettuale funziona: è sul piano pratico che crolla.",
    "Il progetto è interessante: la traduzione sul mio viso no.",
    "Non è la qualità del design a mancare: è la compatibilità col mio viso.",
    "Il modello non ha difetti concettuali: ha un difetto di compatibilità con me.",
]

# "Peccato, perché qualche qualità ce l'ha." (21x)
PATTERNS["Peccato, perch\u00e9 qualche qualit\u00e0 ce l\u2019ha."] = [
    "Purtroppo, perché le qualità non mancano.",
    "Un vero peccato, visto che ha aspetti validi.",
    "È un peccato perché le premesse di qualità c'erano.",
    "Dispiace, perché i punti di forza non gli mancano.",
    "Peccato davvero, perché ha dei meriti innegabili.",
    "È frustrante perché le qualità di base ci sono.",
    "Il rammarico c'è, perché il materiale di base è buono.",
    "Spiace, perché ha delle carte da giocare.",
    "Un peccato, perché non è un modello privo di merito.",
    "Rammarico, perché le potenzialità le vedo.",
    "Dispiace, perché non è che gli manchino le qualità.",
    "Peccato, perché ha più di un aspetto meritevole.",
    "È un peccato perché l'intenzione e la qualità ci sono.",
    "Spiace, perché a livello di qualità non è carente.",
    "Purtroppo, perché ci sarebbero gli ingredienti per qualcosa di meglio.",
    "Un vero rammarico, visto che i pregi non gli mancano.",
    "Dispiace dirlo, perché le qualità sono visibili.",
    "Peccato, perché su un'altra base avrebbe funzionato.",
    "Rammarico sincero, perché ha delle frecce al suo arco.",
    "Spiace sinceramente, perché le premesse erano buone.",
    "È un peccato, perché non si può dire che non abbia meriti.",
]
PATTERNS["Peccato, perch\u00e9 qualche qualit\u00e0 ce l'ha."] = PATTERNS["Peccato, perch\u00e9 qualche qualit\u00e0 ce l\u2019ha."]

# "Nella mia rotazione è entrato davvero, non simbolicamente." (21x)
PATTERNS["Nella mia rotazione \u00e8 entrato davvero, non simbolicamente."] = [
    "È entrato nella mia selezione attiva, non per far numero.",
    "Fa parte dei miei occhiali di uso reale, non solo di nome.",
    "È nella mia rotazione effettiva, non come presenza passiva.",
    "Ha conquistato un posto reale fra i miei occhiali, non uno nominale.",
    "Nella mia rotazione quotidiana occupa un posto vero.",
    "Lo uso davvero: non è un pezzo da collezione dimenticato.",
    "È entrato nella rosa dei miei abituali, non come figurante.",
    "Non è lì per fare collegare: lo uso attivamente.",
    "Ha un ruolo concreto nella mia selezione di ogni giorno.",
    "Non è un inquilino passivo: è parte attiva della mia rotazione.",
    "Lo scelgo regolarmente: il suo posto nella rotazione è reale.",
    "Non è lì per bellezza: lo uso regolarmente.",
    "Ha un posto vero nel mio cassetto, non solo simbolico.",
    "Lo porto davvero, non lo tengo solo per dire di averlo.",
    "Nella mia selezione gioca un ruolo attivo.",
    "Non è un pezzo da mostra: è un pezzo da uso.",
    "Fa parte della rotazione vera, non della selezione ornamentale.",
    "Lo prendo davvero dal cassetto: non è un inquilino fantasma.",
    "È un membro attivo della mia rotazione, non un comprimario.",
    "Ha guadagnato un posto effettivo, non teorico, nella mia selezione.",
    "Lo uso con frequenza reale: il suo posto è sostanziale.",
]

# "Tra quelli che possiedo, questo è entrato molto in fretta tra i preferiti." (20x)
PATTERNS["Tra quelli che possiedo, questo \u00e8 entrato molto in fretta tra i preferiti."] = [
    "Fra i miei occhiali, si è fatto strada tra i preferiti in tempo record.",
    "Nel mio cassetto ha scalato la classifica dei preferiti molto rapidamente.",
    "È diventato uno dei preferiti nel giro di poco.",
    "Se ne è andato dritto nella mia top selection, senza passaggi intermedi.",
    "Ha bruciato le tappe ed è diventato subito uno dei miei preferiti.",
    "Fra tutti i miei occhiali, è entrato nella lista dei preferiti come un razzo.",
    "Non ha impiegato molto a diventare uno dei miei pezzi preferiti.",
    "Ha conquistato un posto stabile fra i miei preferiti in tempi brevissimi.",
    "Nel panorama dei miei occhiali, si è posizionato fra i top quasi subito.",
    "La scalata ai primi posti fra i miei occhiali è stata fulminea.",
    "È passato da nuovo arrivo a preferito in un lampo.",
    "Nel mio set di occhiali, ha raggiunto il podio dei preferiti rapidissimo.",
    "La corsa verso la mia top list è stata velocissima.",
    "Fra tutti i miei acquisti, si è fatto spazio tra i preferiti in fretta.",
    "Ha conquistato la mia top selection in tempo record.",
    "È entrato nel ristretto gruppo dei miei preferiti senza indugiare.",
    "Fra i miei occhiali, pochi hanno scalato la classifica così in fretta.",
    "Ha preso posto tra i preferiti prima ancora che me ne rendessi conto.",
    "Nel mio cassetto ha ottenuto lo status di preferito in poco tempo.",
    "La sua ascesa fra i miei occhiali preferiti è stata rapida.",
]

# "Mi aspettavo un modello interessante, non uno che mi venisse voglia di rimettere subito." (20x)
PATTERNS["Mi aspettavo un modello interessante, non uno che mi venisse voglia di rimettere subito."] = [
    "Pensavo a un modello piacevole, non a una tentazione perenne.",
    "Mi aspettavo qualcosa di buono, non qualcosa che volessi rimettere ogni volta.",
    "Prevedevo un prodotto valido, non uno da affetto immediato.",
    "Non mi aspettavo che superasse il livello dell'interesse per diventare un must.",
    "Pensavo a un buon acquisto, non a un paio da cui non riesco a separarmi.",
    "Mi aspettavo qualcosa di apprezzabile, non una dipendenza immediata.",
    "Credevo di comprare qualcosa di valido, non il mio prossimo preferito.",
    "Non prevedevo che avrei avuto già voglia di rimetterlo ogni volta.",
    "Immaginavo un'aggiunta piacevole, non una priorità nel cassetto.",
    "Mi aspettavo un buon modello, non uno che sceglierei per primo ogni mattina.",
    "Pensavo a un prodotto valido, non al paio che raggiunge sempre i miei primi pensieri.",
    "Prevedevo di apprezzarlo, non di provare una cosí forte voglia di portarlo sempre.",
    "Mi aspettavo un buon acquisto: ha superato quella soglia in un attimo.",
    "Credevo in un modello di qualità, non in una rivelazione immediata.",
    "Immaginavo un prodotto solido, non uno che mi farebbe uscire solo per portarlo.",
    "Non credevo sarebbe diventato così rapidamente il mio primo istinto.",
    "Pensavo a un modello all'altezza, non a un colpo di fulmine.",
    "Mi aspettavo di apprezzarlo con calma, non di volerlo rimettere ogni giorno.",
    "Prevedevo un buon prodotto, ma non questa urgenza di indossarlo.",
    "Immaginavo un acquisto ragionato, non un nuovo favorito istantaneo.",
]

# "Lo rimetto volentieri e questo per me vale più di mille schede tecniche." (20x)
PATTERNS["Lo rimetto volentieri e questo per me vale pi\u00f9 di mille schede tecniche."] = [
    "Il fatto che lo scelga ogni volta per me vale più di qualsiasi specifica.",
    "Lo riporto con piacere, e questo conta più di ogni dettaglio tecnico.",
    "La voglia di rimetterlo è la miglior recensione possibile.",
    "Il piacere di portarlo di nuovo supera qualsiasi dato tecnico.",
    "Se lo rimetto volentieri, il resto delle specifiche passa in secondo piano.",
    "La prima prova del suo valore è che mi viene voglia di rimetterlo.",
    "Lo indosso sempre con piacere: questa è l'unica specifica che conta.",
    "Il test definitivo è la voglia di rimetterlo, e quello lo supera ogni volta.",
    "Se lo riporto volentieri, per me è più importante di qualsiasi scheda.",
    "Il piacere di rimetterlo è la conferma più forte.",
    "Il desiderio di rindossarlo è il voto più alto che posso assegnare.",
    "Se ogni volta ho voglia di rimetterlo, il giudizio è già scritto.",
    "Lo riprendo sempre con piacere e quello per me è il metro definitivo.",
    "La gioia di rimetterlo è più eloquente di qualsiasi specifica.",
    "Il fatto che lo scelga ripetutamente è la sua vera qualifica.",
    "Lo riporto con entusiasmo e questo dice più di mille parole.",
    "Il piacere di rindossarlo è il migliore dei test.",
    "Se continuo a sceglierlo, le specifiche diventano una nota a piè di pagina.",
    "Lo rimetto con convinzione, e quello è l'unico metro che mi importa.",
    "La voglia costante di rimetterlo è il mio verdetto più sincero.",
]

print(f"Parte 5 caricata: totale {len(PATTERNS)} pattern definiti")
