#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Parte 2: Pattern restanti (interni e di chiusura)
"""

# Importa PATTERNS dalla parte 1
from rewrite_reviews_part1 import PATTERNS

# ---------------------------------------------------------------------------
# PATTERN 11: "Si vede che il disegno è curato, anche se non tutto è perfetto." (38x)
# ---------------------------------------------------------------------------
_p11 = [
    "La cura progettuale si percepisce, nonostante qualche imperfezione.",
    "Il design è pensato bene, anche se non è impeccabile.",
    "C'è attenzione nel disegno, pur con qualche limite.",
    "La ricerca estetica è evidente, seppure con margini di miglioramento.",
    "Il progetto dietro è serio, anche se non tutto è risolto.",
    "Si nota un lavoro di design accurato, pur non esente da difetti.",
    "La qualità del disegno è buona, non perfetta ma onesta.",
    "L'intenzione progettuale è chiara, anche se qualcosa sfugge.",
    "Il lavoro di design c'è e si vede, malgrado qualche sbavatura.",
    "La mano del designer si sente, anche dove non arriva del tutto.",
    "Il disegno denota cura, senza per questo essere infallibile.",
    "La progettazione è di livello, pur con qualche angolo non levigato.",
    "Si percepisce un pensiero dietro, anche se l'esecuzione non è totale.",
    "La linea è studiata, benché non tutto risulti impeccabile.",
    "Il concept è valido, anche dove la resa non è assoluta.",
    "L'idea di design è forte, nonostante qualche dettaglio meno rifinito.",
    "La costruzione formale è solida, pur con qualche concessione.",
    "Il tratto progettuale è curato, al netto di piccole imperfezioni.",
    "La maturità del disegno si avverte, anche se non è totale.",
    "L'architettura del modello è ragionata, pur non essendo perfetta.",
    "La fattura del design è onesta, senza sconfinare nell'eccellenza.",
    "Il pensiero creativo c'è, anche se non tutto è stato portato a termine.",
    "Il disegno ha sostanza, nonostante qualche aspetto migliorabile.",
    "La regia estetica è buona, anche quando non è impeccabile.",
    "L'impianto progettuale convince, con qualche riserva sui dettagli.",
    "Il design è di buon livello, senza essere irreprensibile.",
    "Il progetto ha intelligenza, pur con qualche passaggio non perfetto.",
    "La cura formale è reale, anche se non copre ogni angolo.",
    "Il disegno ha un suo rigore, pur con qualche esitazione.",
    "L'elaborazione estetica è di qualità, anche se con margini residui.",
    "Il design è onesto, non perfetto ma dignitoso.",
    "La coerenza progettuale c'è, anche se con qualche concessione.",
    "Il profilo estetico è ragionato, pur senza raggiungere la perfezione.",
    "La linea è stata pensata con cura, anche dove non arriva al top.",
    "Il disegno rivela attenzione, lasciando qualche piccola zona d'ombra.",
    "L'impronta progettuale è positiva, senza essere immacolata.",
    "Il design merita rispetto, anche nei punti dove tentenna.",
    "Il lavoro creativo è visibile, nonostante qualche dettaglio migliorabile.",
]
PATTERNS["Si vede che il disegno \u00e8 curato, anche se non tutto \u00e8 perfetto."] = _p11

# ---------------------------------------------------------------------------
# PATTERN 12: "Ha delle qualità evidenti, sarebbe disonesto negarlo." (36x)
# ---------------------------------------------------------------------------
_p12 = [
    "I pregi ci sono, sarebbe ingiusto non riconoscerli.",
    "Le qualità sono innegabili, va detto con onestà.",
    "Non manca di punti di forza, questo è chiaro.",
    "Ha dei meriti che sarebbe scorretto ignorare.",
    "I lati positivi saltano all'occhio, non posso negarlo.",
    "Ha elementi validi che meritano di essere riconosciuti.",
    "Non si può dire che manchi di sostanza.",
    "Le sue virtù sono concrete e visibili.",
    "Ha dei punti forti che parlano da soli.",
    "Oggettivamente ha delle carte da giocare.",
    "I suoi meriti sono sotto gli occhi di tutti.",
    "Ci sono aspetti indiscutibilmente riusciti.",
    "Non è privo di qualità, questo lo ammetto senza fatica.",
    "Ha argomenti validi a suo favore.",
    "Le cose buone ci sono e non vanno sottaciute.",
    "Non manca di frecce al suo arco.",
    "Ha dei requisiti che meritano una menzione.",
    "È un modello con delle frecce da tirare.",
    "I punti di forza esistono e sono reali.",
    "Ha dalla sua alcuni elementi davvero riusciti.",
    "Non si può dire che non abbia nulla da offrire.",
    "I suoi tratti positivi sono evidenti a chiunque.",
    "Ha una base solida, questo va riconosciuto.",
    "Non mancano gli aspetti meritevoli.",
    "Le qualità ci sono e si vedono chiaramente.",
    "Ha delle basi su cui è giusto dare credito.",
    "Non è un modello privo di argomenti.",
    "I meriti concreti ci sono e vanno ammessi.",
    "Ha dei momenti di lucidità estetica innegabili.",
    "Non è un prodotto senza valore, questo è certo.",
    "Ha dei tratti che parlano a suo favore con chiarezza.",
    "Ci sono aspetti che meritano un riconoscimento esplicito.",
    "Ha una sua dignità estetica che non si può contestare.",
    "I punti di pregio sono tangibili.",
    "Ha dei fondamenti che vanno rispettati.",
    "Le sue carte migliori sono sul tavolo e si vedono.",
]
PATTERNS["Ha delle qualit\u00e0 evidenti, sarebbe disonesto negarlo."] = _p12

# ---------------------------------------------------------------------------
# PATTERN 13: "ha tirato fuori una personalità più matura di quanto" (37x)
# ---------------------------------------------------------------------------
_p13 = [
    "ha rivelato un carattere più solido di quanto",
    "ha mostrato una profondità maggiore di quanto",
    "ha svelato una complessità superiore a quella che",
    "ha espresso una maturità che non mi aspettavo da quanto",
    "ha fatto emergere un temperamento più definito di quanto",
    "ha sfoggiato una presenza più sofisticata di quanto",
    "ha dimostrato una caratura più alta di quanto",
    "ha sorpreso con una profondità che superava quanto",
    "ha portato alla luce un carattere più pieno di quanto",
    "ha dispiegato un'identità più ricca di quanto",
    "ha sciorinato una maturità insospettabile rispetto a quanto",
    "ha manifestato una consistenza superiore a quanto",
    "ha rivelato un peso estetico maggiore di quanto",
    "ha tirato fuori un temperamento più complesso di quanto",
    "ha esibito una solidità identitaria che superava quanto",
    "ha svelato una profondità progettuale oltre quanto",
    "ha messo in campo un carattere più strutturato di quanto",
    "ha espresso una cifra stilistica più ampia di quanto",
    "ha lasciato affiorare una personalità più netta di quanto",
    "ha scoperto una dimensione più adulta di quanto",
    "ha fatto venire a galla un carattere oltre quanto",
    "ha delineato un'identità più matura di quanto",
    "ha palesato una solidità che eccedeva quanto",
    "ha liberato un carattere più deciso di quanto",
    "ha fatto trasparire una profondità che andava oltre quanto",
    "ha messo in mostra una stoffa superiore a quanto",
    "ha dischiuso un profilo più ricco di quanto",
    "ha svelato una consistenza stilistica oltre quanto",
    "ha rivelato una caratura più densa di quanto",
    "ha mostrato una levatura superiore a quanto",
    "ha estratto un'identità più definita di quanto",
    "ha saputo esprimere un carattere più pieno di quanto",
    "ha scoperto carte più importanti di quanto",
    "ha portato in superficie una maturità eccedente quanto",
    "ha esibito un'anima più strutturata di quanto",
    "ha prodotto un'impressione più profonda di quanto",
    "ha lasciato emergere una statura più alta di quanto",
]
PATTERNS["ha tirato fuori una personalit\u00e0 pi\u00f9 matura di quanto"] = _p13

# ---------------------------------------------------------------------------
# PATTERN 14: "Lo capisco, semplicemente non lo sento mio fino in fondo." (35x)
# ---------------------------------------------------------------------------
_p14 = [
    "Ne riconosco il valore, ma non sento quel legame.",
    "Lo apprezzo razionalmente, senza mai entrarci davvero in sintonia.",
    "Capisco perché piaccia, ma su di me non scatta.",
    "Intellettualmente lo promuovo, emotivamente no.",
    "Il pregio c'è, ma manca la connessione personale.",
    "Lo rispetto senza riuscire a farlo mio.",
    "Razionalmente lo capisco, ma non lo vivo sulla mia pelle.",
    "Riconosco il suo valore, eppure non è il mio linguaggio.",
    "Mi è chiaro il perché funzioni, ma non per me.",
    "L'idea mi piace, l'esperienza sul mio viso meno.",
    "Lo comprendo, senza però sentirlo addosso.",
    "Il merito lo vedo, l'affinità la cerco invano.",
    "Ne percepisco la qualità, ma non la sento mia.",
    "Lo ammiro a distanza, senza mai volerlo davvero.",
    "È un buon prodotto che non parla il mio dialetto.",
    "Lo giudico bene, ma non mi ci ritrovo.",
    "Lo promuovo col pensiero, non col cuore.",
    "Lo stimo, ma non lo scelgo.",
    "Capisco chi lo ama, io resto in panchina.",
    "Lo difenderei in una discussione, ma non lo indosserei di slancio.",
    "Vedo il progetto, non vedo il mio riflesso dentro.",
    "Ha le sue ragioni, che non coincidono con le mie.",
    "Lo posiziono tra i buoni, ma non tra i miei.",
    "Lo riconosco come valido, senza mai sentirlo vicino.",
    "Ne ammetto la qualità senza provare trasporto.",
    "È un occhiale fatto bene che non mi appartiene.",
    "Lo osservo con rispetto e con distacco.",
    "Lo lodo, ma non lo indosso con naturalezza.",
    "Il giudizio è positivo, la chimica personale è assente.",
    "Lo capisco, ma la vibrazione personale non c'è.",
    "Lo trovo interessante per altri, non per me.",
    "Lo accetto nella teoria, nella pratica mi sfugge.",
    "Il suo linguaggio è chiaro, ma non è il mio.",
    "Lo valuto bene, senza che diventi parte di me.",
    "Lo considero riuscito, per qualcun altro.",
]
PATTERNS["Lo capisco, semplicemente non lo sento mio fino in fondo."] = _p14

# ---------------------------------------------------------------------------
# PATTERN 15: "mi aveva incuriosito parecchio. Dal vivo però" (46x)
# ---------------------------------------------------------------------------
_p15 = [
    "mi aveva attirato molto. Nella realtà però",
    "aveva suscitato il mio interesse. All'atto pratico però",
    "mi aveva colpito sulla carta. Sul viso però",
    "mi incuriosiva non poco. Una volta provato però",
    "aveva catturato la mia attenzione. Nella pratica però",
    "mi aveva fatto pensare. Dal vero però",
    "mi sembrava promettente. Nella quotidianità però",
    "mi aveva intrigato su immagine. Provandolo però",
    "aveva solleticato la mia curiosità. Al dunque però",
    "aveva destato il mio interesse. Portandolo però",
    "mi aveva fatto fermare a guardare. Sulla pelle però",
    "mi aveva dato l'idea giusta. Nella realtà dei fatti però",
    "aveva stimolato il mio interesse. Nel concreto però",
    "mi aveva ispirato fiducia. Al test reale però",
    "mi aveva tenuto incollato alle foto. Il test dal vivo però",
    "aveva acceso la mia curiosità. Indossandolo però",
    "aveva suscitato aspettative. Nella pratica quotidiana però",
    "mi aveva dato segnali positivi. In situazione reale però",
    "mi parlava a distanza. Avvicinandomi però",
    "mi aveva fatto fare un pensiero serio. Mettendolo però",
    "mi aveva dato una buona prima impressione. All'uso però",
    "aveva risvegliato la mia attenzione. Provato sul campo però",
    "mi affascinava online. Nella vita vera però",
    "mi aveva generato aspettative. All'atto pratico però",
    "mi aveva convinto in partenza. Una volta su però",
    "mi stuzzicava parecchio. Dalla teoria alla pratica però",
    "mi dava un segnale forte. Confrontandomi con la realtà però",
    "mi aveva fatto sognare un po'. Poi però",
    "mi aveva dato molte speranze. Alla verifica però",
    "mi piaceva già prima di provarlo. Di persona però",
    "aveva catturato la mia immaginazione. Alla prova dei fatti però",
    "mi aveva sedotto sulla carta. Nella concretezza però",
    "mi aveva dato una carica iniziale. Al dunque però",
    "mi aveva mandato segnali incoraggianti. Provandolo davvero però",
    "mi aveva fatto decidere in fretta. Usandolo però",
    "aveva acceso qualcosa. Misurandomi con il quotidiano però",
    "mi aveva dato buone vibrazioni. Portandolo fuori però",
    "mi entusiasmava nell'idea. Nella pratica però",
    "mi aveva conquistato a distanza. Di persona però",
    "mi aveva dato motivo di fiducia. Testandolo però",
    "mi aveva comunicato energia. Al riscontro reale però",
    "aveva fatto breccia subito. Nella routine però",
    "mi aveva parlato forte e chiaro. All'esperienza però",
    "mi aveva dato ottimi segnali. Dal primo utilizzo però",
    "mi aveva caricato di aspettative. Nella pratica concreta però",
    "aveva generato in me curiosità forte. Al primo test però",
]
PATTERNS["mi aveva incuriosito parecchio. Dal vivo per\u00f2"] = _p15

# ---------------------------------------------------------------------------
# PATTERN 16: "ma non basta per salvarlo nel mio uso." (46x)
# ---------------------------------------------------------------------------
_p16 = [
    "ma non è sufficiente a farlo entrare nella mia rotazione.",
    "ma questo non basta per rendermelo indispensabile.",
    "ma alla fine non è abbastanza per il mio quotidiano.",
    "eppure non risolve il problema della compatibilità con me.",
    "ma non compensa il resto per il mio tipo di utilizzo.",
    "ma ciò non è abbastanza da farlo restare nel mio cassetto.",
    "ma non cambia il bilancio finale nel mio caso.",
    "ma non sposta abbastanza l'ago della bilancia per me.",
    "eppure non colma la distanza fra l'idea e il mio uso reale.",
    "ma questo non riesce a convincermi nel lungo periodo.",
    "ma non è il tipo di argomento che mi fa tornare a prenderlo.",
    "ma non risolve la questione di fondo per come lo uso.",
    "eppure non salva il rapporto fra me e questo modello.",
    "ma non è il dettaglio che ribalta il verdetto nel mio caso.",
    "ma non riesce a trattenerlo fra i miei occhiali abituali.",
    "ma ciò non basta a conquistarmi nell'uso quotidiano.",
    "eppure non è sufficiente a fargli guadagnare un posto fisso.",
    "ma non raggiunge la soglia che mi farebbe sceglierlo spesso.",
    "ma alla resa dei conti non cambia il mio verdetto finale.",
    "ma questo da solo non basta a tenerlo in gioco.",
    "eppure il bilancio per il mio uso resta insufficiente.",
    "ma non supera la soglia della praticità nel mio caso.",
    "ma per come lo uso io non è abbastanza.",
    "eppure non lo riscatta nel bilancio complessivo.",
    "ma non è il fattore determinante per il mio utilizzo.",
    "ma resta un argomento debole per il mio cassetto.",
    "eppure non riesce a salvarli nella mia routine.",
    "ma nel mio uso reale questo conta poco.",
    "ma non è il tipo di merito che cambia le sorti del mio giudizio.",
    "eppure il conto finale nel mio caso non torna.",
    "ma non ha il peso sufficiente per trattenermi.",
    "ma questo non gli vale la permanenza nella mia selezione.",
    "eppure non basta per farlo diventare un abitudinario.",
    "ma il deficit di praticità per me resta.",
    "ma non è il genere di qualità che mi fa tornare a cercarlo.",
    "eppure per il mio profilo d'uso non è sufficiente.",
    "ma non sposta i pesi abbastanza nel mio bilancio.",
    "ma non è il tipo di surplus che mi fa perdonare il resto.",
    "eppure non compensa le perplessità che ho nel mio contesto.",
    "ma ciò non basta a chiudere in positivo il mio giudizio.",
    "ma per la mia vita concreta non è abbastanza.",
    "eppure questo non cambia il fatto che nel mio uso restano marginali.",
    "ma non raggiunge il peso necessario per restare nel mio giro.",
    "ma nel concreto non è sufficiente a salvarli.",
    "eppure non è il genere di pregio che mi fa cambiare idea.",
    "ma per il mio stile di vita non basta a riscattarli.",
]
PATTERNS["ma non basta per salvarlo nel mio uso."] = _p16

# ---------------------------------------------------------------------------
# PATTERN 17: "Alla fine resto in equilibrio instabile." (36x)
# ---------------------------------------------------------------------------
_p17 = [
    "Alla fine rimango in una zona grigia.",
    "Il mio giudizio resta sospeso fra due poli.",
    "Non riesco a pendere in modo netto da un lato.",
    "Resto diviso, senza una direzione chiara.",
    "Il verdetto rimane in bilico.",
    "Mi trovo in una terra di mezzo dal punto di vista del giudizio.",
    "Il mio parere oscilla senza mai stabilizzarsi.",
    "Resto in un limbo valutativo.",
    "Il giudizio finale non trova un approdo netto.",
    "Mi ritrovo in una posizione intermedia che non si risolve.",
    "Il bilancio resta in pareggio incerto.",
    "Non arrivo a una conclusione netta in nessuna delle due direzioni.",
    "Rimango a metà strada fra promozione e bocciatura.",
    "Non prendo posizione, perché la realtà è ambigua.",
    "Il mio parere galleggia senza toccare terra.",
    "Resto in un punto morto valutativo.",
    "Il mio verdetto rimane irrisolto.",
    "Non mi sbilancio, perché le ragioni sono bilanciate.",
    "Il giudizio resta in uno stato di sospensione.",
    "Mi trovo esattamente nel mezzo, senza spinte decisive.",
    "La mia opinione resta in uno stato interlocutorio.",
    "Il mio parere rimane agganciato a un punto intermedio.",
    "Non riesco a chiudere il cerchio del giudizio.",
    "Il mio verdetto resta incompleto.",
    "Mi fermo a un giudizio che non è né su né giù.",
    "Rimango in un equilibrio che non si consolida.",
    "Il mio parere resta ancorato al centro.",
    "Non arrivo a una sentenza definitiva.",
    "Il bilancio si chiude in pareggio, senza vincitori.",
    "La mia posizione resta in mezzo al guado.",
    "Non trovo il modo di pendere da una parte o dall'altra.",
    "Resto aggrappato a un giudizio che non si definisce.",
    "Il mio verdetto è un punto interrogativo che non si risolve.",
    "Rimango in quella zona dove il positivo e il negativo si equivalgono.",
    "Il giudizio finale continua a oscillare.",
    "Il mio parere non trova un punto fermo.",
]
PATTERNS["Alla fine resto in equilibrio instabile."] = _p17

# ---------------------------------------------------------------------------
# PATTERN 18: "Mi sono piaciuti diversi aspetti" (41x)
# ---------------------------------------------------------------------------
_p18 = [
    "Ho apprezzato vari elementi",
    "Diversi dettagli mi hanno convinto",
    "Ci sono più cose che mi piacciono",
    "Trovo parecchi punti di forza",
    "Molti aspetti mi soddisfano",
    "Riconosco più di un pregio",
    "Ho notato diversi punti a favore",
    "Non mancano gli elementi riusciti",
    "Più di un dettaglio mi ha colpito",
    "Ho trovato vari aspetti convincenti",
    "C'è del buono in diversi punti",
    "Apprezzo più di un singolo elemento",
    "Registro vari tratti positivi",
    "I punti di forza sono più d'uno",
    "Diversi aspetti meritano una menzione positiva",
    "Noto parecchi pregi concreti",
    "Ci sono molteplici elementi che funzionano",
    "Ho individuato vari dettagli riusciti",
    "Non posso negare diversi meriti",
    "Diversi fattori giocano a loro favore",
    "Trovo più di una ragione per apprezzarli",
    "Parecchi dettagli mi hanno fatto buona impressione",
    "Hanno dalla loro diversi elementi validi",
    "Ci sono vari aspetti che meritano credito",
    "Più di un tratto mi ha fatto piacere",
    "Ho riscontrato diversi punti positivi",
    "I meriti sono plurimi",
    "Non mancano i dettagli convincenti",
    "Diversi particolari mi hanno interessato",
    "Registro più d'un aspetto degno di nota",
    "Hanno vari argomenti a loro favore",
    "Ci sono parecchi elementi che funzionano bene",
    "Trovo diversi spunti pregevoli",
    "Ho colto vari pregi nel complesso",
    "Non pochi aspetti mi hanno colpito positivamente",
    "Diversi tratti esprimono qualità",
    "Ci sono svariati motivi per apprezzarli",
    "Ho contato più di un punto a favore",
    "Numerosi dettagli meritano una nota positiva",
    "Parecchi aspetti si dimostrano validi",
    "Le cose che funzionano sono più d'una",
]
PATTERNS["Mi sono piaciuti diversi aspetti"] = _p18

# ---------------------------------------------------------------------------
# PATTERN 19: "ha trovato il suo senso in modo molto" (36x)
# ---------------------------------------------------------------------------
_p19 = [
    "ha mostrato la sua ragion d'essere in modo",
    "ha rivelato la propria identità in maniera molto",
    "ha espresso il suo significato in modo",
    "ha fatto capire il suo valore in maniera",
    "ha chiarito il suo scopo in modo",
    "ha comunicato il suo punto di forza in modo",
    "ha svelato la propria logica in maniera",
    "ha dimostrato la sua coerenza in modo",
    "ha reso evidente la propria funzione in modo",
    "ha dato prova del suo senso in maniera",
    "ha messo in luce il proprio carattere in modo",
    "ha delineato la propria ragione in modo",
    "ha fatto emergere il suo scopo in maniera",
    "ha manifestato la propria coerenza in modo",
    "ha dispiegato il suo significato in modo",
    "ha reso chiara la propria identità in maniera",
    "ha pronunciato la propria voce in modo",
    "ha dichiarato il suo senso in modo",
    "ha portato alla luce il proprio valore in maniera",
    "ha espresso la propria ragion d'essere in modo",
    "ha precisato la propria natura in modo",
    "ha articolato il proprio carattere in modo",
    "ha rivelato il proprio scopo in maniera",
    "ha tradotto la propria idea in pratica in modo",
    "ha concretizzato il proprio senso in modo",
    "ha esplicitato la sua identità in maniera",
    "ha condensato la propria essenza in modo",
    "ha fatto parlare il proprio design in modo",
    "ha esposto il proprio punto in maniera",
    "ha reso tangibile il proprio valore in modo",
    "ha raccontato la propria storia in modo",
    "ha saputo esprimere il suo perché in maniera",
    "ha dato voce al proprio carattere in modo",
    "ha palesato la sua utilità in modo",
    "ha cristallizzato il proprio senso in modo",
    "ha dato forma alla sua identità in modo",
]
PATTERNS["ha trovato il suo senso in modo molto"] = _p19

# ---------------------------------------------------------------------------
# PATTERN 20: "ha confermato il suo carattere senza diventare" (36x)
# ---------------------------------------------------------------------------
_p20 = [
    "ha mantenuto la sua personalità senza scadere in",
    "ha conservato il suo tratto senza deragliare verso",
    "ha difeso la propria identità senza sfociare in",
    "ha ribadito il proprio carattere senza risultare",
    "ha preservato la propria cifra senza rischiare di apparire",
    "ha custodito la sua essenza senza avvicinarsi a un effetto",
    "ha sostenuto il proprio registro senza trasformarsi in qualcosa di",
    "ha protetto la propria voce senza mai diventare",
    "ha confermato la propria identità senza virare verso",
    "ha mantenuto il suo timbro senza cadere nel",
    "ha tenuto fede alla sua linea senza eccedere nel",
    "ha conservato la propria direzione senza scivolare nel",
    "ha continuato a esprimere il suo carattere senza diventare",
    "ha riaffermato la propria cifra senza sfiorare il",
    "ha salvaguardato il proprio tratto senza rischiare di diventare",
    "ha tenuto il punto senza mai risultare",
    "ha consolidato la propria identità senza cedere alla tentazione di",
    "ha espresso la propria personalità senza degenerare in",
    "ha difeso la sua linea senza mai sfiorare l'effetto",
    "ha resistito alla tentazione di esagerare senza perdere",
    "ha mantenuto la rotta senza sconfinare nel",
    "ha portato avanti la sua idea senza diventare",
    "ha retto la propria posizione senza trasformarsi in",
    "ha fatto il suo senza mai sconfinare nel",
    "ha comunicato il suo senso senza mai eccedere nel",
    "ha dato la sua impronta senza rischiare di essere",
    "ha dimostrato personalità senza sfociare nel",
    "ha giocato le sue carte senza mai sembrare",
    "ha svolto il suo ruolo senza mai risultare",
    "ha parlato senza alzare la voce fino a diventare",
    "ha preso posizione senza mai eccedere nel",
    "ha marcato il territorio senza mai cadere nel",
    "ha occupato la scena senza mai sfiorare il",
    "ha detto la sua senza mai trasformarsi in",
    "ha lasciato il segno senza rischiare di diventare",
    "ha dichiarato il suo registro senza scivolare nel",
]
PATTERNS["ha confermato il suo carattere senza diventare"] = _p20

# ---------------------------------------------------------------------------
# PATTERN 21-30: Incipit meno frequenti
# ---------------------------------------------------------------------------

# "Li ho giudicati in dieci secondi e poi li ho rivalutati con calma." (48x)
_p21 = [
    "Il primo giudizio è stato immediato, il secondo molto più ragionato.",
    "La prima impressione e il parere definitivo non coincidono affatto.",
    "All'inizio li ho archiviati in fretta, poi mi sono ricreduto.",
    "Il verdetto lampo si è ribaltato con l'uso quotidiano.",
    "Servono più di dieci secondi per capire cosa hanno da dire.",
    "L'impressione veloce è stata smentita dall'uso prolungato.",
    "Dopo il primo sguardo frettoloso, ho rivalutato tutto.",
    "Il giudizio istantaneo non raccontava la storia completa.",
    "Ci ho messo poco a giudicarli e tanto a capirli davvero.",
    "La prima occhiata ingannava, la seconda ha aperto un mondo.",
    "La reazione d'impulso non rendeva giustizia al modello.",
    "Il mio giudizio si è evoluto parecchio dalla prima prova.",
    "Giudicandoli troppo in fretta avevo perso il pezzo migliore.",
    "La fretta iniziale ha ceduto il passo a una valutazione più attenta.",
    "Il mio parere ha fatto un percorso notevole dalla prima volta.",
    "L'impressione lampo è tramontata dopo qualche utilizzo reale.",
    "Al primo tentativo li avevo già archiviati, e invece.",
    "Il pregiudizio iniziale si è sgretolato con il tempo.",
    "Con l'uso mi sono accorto che il primo impatto era fuorviante.",
    "Il giudizio a caldo era uno, quello a freddo un altro.",
    "L'opinione rapida e quella meditata non hanno nulla in comune.",
    "Ho imparato che questo modello richiede pazienza per essere capito.",
    "La prima reazione era lontanissima dal parere finale.",
    "Un giudizio troppo rapido mi avrebbe portato fuori strada.",
    "Ho dovuto rivedere completamente il mio primo parere.",
    "L'impressione d'istinto era ingenerosa, quella ponderata molto diversa.",
    "Il tragitto fra prima impressione e giudizio finale è stato lungo.",
    "La reazione immediata e la valutazione ragionata dicono cose opposte.",
    "Con il senno di poi, il primo giudizio era affrettato.",
    "L'ho sottovalutato all'inizio, poi l'ho rivalutato completamente.",
    "La mia opinione ha fatto un bel viaggio rispetto al punto di partenza.",
    "La prima reazione va ignorata per capire questo modello.",
    "Ho cambiato molto idea dal primo contatto a oggi.",
    "Il giudizio immediato non aveva colto il punto.",
    "All'inizio non ci credevo, poi l'ho dovuto ammettere.",
    "La mia prima impressione era ingiusta, lo riconosco.",
    "Il percorso dalla diffidenza all'apprezzamento è stato graduale.",
    "La rivalutazione è arrivata dopo, ma è stata significativa.",
    "Ho cambiato verso lungo la strada, e non me l'aspettavo.",
    "Ho vissuto una delle mie più grandi inversioni a U.",
    "Il primo impatto negativo si è trasformato piano piano.",
    "Ho iniziato scettico e sono finito sorpreso.",
    "La mia opinione si è ribaltata con l'uso.",
    "Dalla diffidenza iniziale al rispetto il passo è stato lungo.",
    "Il primo contatto non prometteva, ma poi il quadro è cambiato.",
    "Il mio giudizio ha subito un'inversione che non prevedevo.",
    "Ho dovuto ricredermi abbastanza in fretta.",
    "La rivalutazione è stata inevitabile dopo qualche uscita.",
]
PATTERNS["Li ho giudicati in dieci secondi e poi li ho rivalutati con calma."] = _p21

# "Li ho infilati per la prima volta senza aspettarmi troppo e invece" (41x)
_p22 = [
    "Li ho provati senza grandi aspettative e sono rimasto colpito:",
    "Non mi aspettavo molto al primo tentativo, e invece",
    "Li ho indossati quasi per caso e mi sono trovato bene:",
    "Alla prima prova le attese erano zero, ma poi",
    "Senza particolari aspettative li ho messi su, e",
    "Il primo utilizzo è stato una piacevole sorpresa:",
    "Li ho infilati con nonchalance e sono rimasto stupito:",
    "Non ci puntavo nulla e invece alla prima prova",
    "Li ho provati con distacco, ma il risultato mi ha sorpreso:",
    "Il primo contatto è stato più interessante del previsto:",
    "Senza crederci troppo li ho indossati, e",
    "Li ho messi su senza aspettative e la sorpresa è arrivata:",
    "Al primo tentativo non ci speravo, e invece",
    "Il debutto è stato insospettabilmente positivo:",
    "Li ho presi in mano senza convinzione, poi",
    "La prima prova non doveva impressionarmi, e invece",
    "Mi sono avvicinato senza entusiasmo ma il risultato",
    "Il primo test, che avrebbe dovuto essere neutro,",
    "Li ho calzati senza cerimonie e",
    "Pensavo di provarli e basta, invece",
    "La prima volta che li ho messi non mi aspettavo granché, e",
    "Li ho indossati quasi per obbligo e poi",
    "Il primo approccio doveva essere solo un test, ma",
    "Li ho infilati distrattamente e risultato è stato sorprendente:",
    "Li ho messi senza farci troppo caso e mi sono ritrovato a pensare:",
    "La prima uscita con loro non prometteva molto, ma",
    "Li ho indossati per pura curiosità e sono rimasto colpito:",
    "Senza pretese li ho provati, e devo ammettere che",
    "Non immaginavo nulla di speciale al primo utilizzo, e invece",
    "Il primo contatto doveva essere esplorativo, è diventato una scoperta:",
    "Li ho calzati di fretta, senza aspettarmi niente, e poi",
    "Alla prima prova ero già pronto a toglierli, ma",
    "Li ho messi solo per curiosità, e",
    "Non c'era nessun entusiasmo alla prima prova, eppure",
    "Li ho aperti senza cerimonia e mi sono trovato di fronte a",
    "Li ho provati con l'idea di togliermeli subito, e invece",
    "Li ho indossati tanto per provare e il risultato",
    "Il primo test non sembrava speciale, ma poi",
    "Senza attendermi nulla di straordinario li ho provati, e",
    "La prima volta che li ho calzati non ci credevo, eppure",
    "Li ho messi su con scetticismo e mi sono dovuto ricredere:",
]
PATTERNS["Li ho infilati per la prima volta senza aspettarmi troppo e invece"] = _p22

# "La prova vera non l'ho fatta davanti allo specchio, ma fuori, e lì" (37x)
_p23 = [
    "Il banco di prova reale non è stato lo specchio ma la strada, e lì",
    "Il test che conta l'ho fatto all'aperto, non in casa, e lì",
    "Non è in bagno che li ho capiti, ma fuori, e lì",
    "La conferma è arrivata fuori di casa, non davanti al riflesso, e lì",
    "Il giudizio serio l'ho dato all'esterno, non allo specchio, e lì",
    "Li ho davvero capiti solo uscendo di casa, e lì",
    "Il verdetto è cambiato quando li ho portati fuori, e lì",
    "Per testarli sul serio sono dovuto uscire, e lì",
    "Il test vero è stato il mondo esterno, non il riflesso, e lì",
    "La verifica che conta è quella alla luce del sole, e lì",
    "Solo fuori casa si capisce se un occhiale funziona, e lì",
    "Il giudizio che vale l'ho espresso per strada, e lì",
    "L'ho capito davvero solo portandoli fuori, e lì",
    "Il responso che conta è arrivato on the road, e lì",
    "La sentenza vera l'ha data il mondo esterno, e lì",
    "Il vero esame è stato indossarli nella vita reale, e lì",
    "Il test da specchio non basta: è fuori che si gioca tutto, e lì",
    "La prova del fuoco è stata all'esterno, e lì",
    "Non è il riflesso a dire la verità, ma la strada, e lì",
    "Il mio parere si è formato fuori, non davanti al vetro, e lì",
    "Il momento della verità è arrivato uscendo, e lì",
    "Per giudicarli ho dovuto portarli nel mondo vero, e lì",
    "La validazione reale è venuta dalla vita quotidiana, non dallo specchio, e lì",
    "Il test più onesto l'ho fatto in giro, e lì",
    "Solo al di fuori delle quattro mura ho avuto il quadro completo, e lì",
    "Il giudizio che mi fido di dare è quello maturato per strada, e lì",
    "La risposta vera l'ho trovata fuori dalla porta di casa, e lì",
    "Non mi sono fidato dello specchio, ho aspettato la prova sul campo, e lì",
    "Il riscontro autentico è arrivato dall'esperienza esterna, e lì",
    "Il vero test è la vita fuori, non il riflesso in bagno, e lì",
    "La prova che conta non è quella del riflesso, ma quella della realtà, e lì",
    "Il test definitivo l'ho fatto per strada, non in casa, e lì",
    "La valutazione concreta è arrivata portandoli fuori, e lì",
    "Il mio metro di giudizio è la strada, non lo specchio, e lì",
    "Il riscontro reale l'ho avuto solo all'aperto, e lì",
    "Li ho valutati nella vita vera, non in quella riflessa, e lì",
    "La prova attendibile è stata quella fatta fuori, e lì",
]
PATTERNS["La prova vera non l\u2019ho fatta davanti allo specchio, ma fuori, e l\u00ec"] = _p23
PATTERNS["La prova vera non l'ho fatta davanti allo specchio, ma fuori, e l\u00ec"] = _p23

# "Il test decisivo per me è sempre la seconda uscita, quella senza entusiasmo iniziale, e lì" (41x)
_p24 = [
    "Il giudizio vero arriva alla seconda uscita, quando la novità è passata, e lì",
    "Per me il test che conta è quello del giorno dopo, a mente fredda, e lì",
    "La prova decisiva è stata la seconda volta, senza l'adrenalina del nuovo, e lì",
    "Giudico sempre alla seconda uscita, quando le emozioni si calmano, e lì",
    "Il mio metro è il secondo utilizzo, quello senza l'effetto novità, e lì",
    "Il vero banco di prova è la volta dopo, senza euforia, e lì",
    "Aspetto sempre la seconda prova per giudicare, quella a sangue freddo, e lì",
    "Per me il giudizio si forma al secondo giro, senza più sorprese, e lì",
    "La verifica che conta è la ripetizione, quando l'entusiasmo è rientrato, e lì",
    "Il test che mi fido di seguire è quello del secondo giorno, e lì",
    "Per me il momento della verità è quando li rimetto senza più attese, e lì",
    "Il giudizio che conta arriva quando l'effetto wow è passato, e lì",
    "La mia valutazione matura solo al secondo utilizzo, quello lucido, e lì",
    "È al secondo tentativo, quello ragionato, che li giudico davvero, e lì",
    "Per me la prova che vale è quella a mente sgombra, la seconda, e lì",
    "Il vero test per me è la seconda volta, quando non devo più stupirmi, e lì",
    "Aspetto sempre che passi il primo giorno per giudicare, e lì",
    "Il mio sistema di giudizio si attiva al secondo round, e lì",
    "Per me la conferma sta nel secondo utilizzo, quello senza aspettative, e lì",
    "La validazione per me arriva quando li riprendo in mano senza entusiasmo, e lì",
    "È la seconda prova che pesa, quella disincantata, e lì",
    "Il mio criterio è la seconda uscita, quando manca l'effetto sorpresa, e lì",
    "Per me l'esame reale è la seconda volta, quella razionale, e lì",
    "La seconda uscita è il filtro più onesto che conosco, e lì",
    "Aspetto il secondo tentativo per esprimermi, quello senza emozione, e lì",
    "Il mio giudizio prende forma al secondo giro, quello sobrio, e lì",
    "Per me la verifica seria inizia dalla seconda volta, e lì",
    "È solo alla seconda prova, smaltito il primo impatto, che mi fido del parere, e lì",
    "La seconda uscita senza entusiasmo è il mio barometro, e lì",
    "Per me il verdetto nasce nel secondo utilizzo, il più onesto, e lì",
    "Mi fido solo del giudizio del giorno dopo, quando la sensazione iniziale è sbiadita, e lì",
    "La mia valutazione seria parte solo dalla seconda prova, e lì",
    "Per me il giudizio che vale è quando li riprendo senza più quell'ansia del nuovo, e lì",
    "Il verdetto affidabile è quello della seconda uscita, a freddo, e lì",
    "Per me l'analisi inizia quando l'aspettativa iniziale è esaurita, e lì",
    "Il test che non mente è il secondo, quello pragmatico, e lì",
    "Per me la verità si rivela alla seconda prova, e lì",
    "La conferma la cerco alla seconda uscita, a mente lucida, e lì",
    "Per me conta il secondo incontro, quello disilluso, e lì",
    "Il giudizio che formulo al secondo utilizzo è quello che vale, e lì",
    "La prova del nove, per me, è la seconda uscita senza enfasi, e lì",
]
PATTERNS["Il test decisivo per me \u00e8 sempre la seconda uscita, quella senza entusiasmo iniziale, e l\u00ec"] = _p24

print("Parte 2 caricata: totale " + str(len(PATTERNS)) + " pattern")
