#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Riscrittura recensioni: sostituisce pattern ripetitivi con alternative uniche.
Ogni pattern ha un pool di alternative combinatoriche.
Nessuna alternativa viene usata due volte per lo stesso pattern.
"""

import json
import random
import hashlib

random.seed(42)  # Riproducibilità

# ============================================================
# POOL DI ALTERNATIVE PER OGNI PATTERN
# Ogni entry: (pattern_esatto, [lista_alternative])
# Le alternative devono essere drop-in replacements
# ============================================================

PATTERNS = {}

# ---------------------------------------------------------------------------
# PATTERN 1: "qui hanno trovato un equilibrio raro" (114x)
# Appare come: "[materiale] e [lenti] qui hanno trovato un equilibrio raro."
# ---------------------------------------------------------------------------
_p1_verbs = [
    "qui si combinano con una coerenza insolita",
    "qui dialogano in modo armonioso",
    "qui trovano una sintonia naturale",
    "qui creano un insieme che funziona",
    "qui si fondono con un risultato convincente",
    "qui generano un abbinamento riuscito",
    "qui si integrano con una fluidità rara",
    "qui producono un effetto sorprendentemente organico",
    "qui lavorano bene insieme, senza forzature",
    "qui raggiungono un punto di equilibrio notevole",
    "qui si sposano con naturalezza",
    "qui si completano a vicenda",
    "qui costruiscono un insieme che ha senso",
    "qui si amalgamano con precisione",
    "qui danno vita a una combinazione solida",
    "qui restituiscono un effetto compatto",
    "qui si intrecciano in modo felice",
    "qui si bilanciano senza sforzo apparente",
    "qui convergono verso un risultato unitario",
    "qui offrono una resa cromatica centrata",
    "qui si accordano con una naturalezza disarmante",
    "qui formano un abbinamento sorprendentemente coeso",
    "qui si mescolano con gusto",
    "qui lavorano all'unisono per un risultato pulito",
    "qui si armonizzano con misura",
    "qui si calibrano in modo originale",
    "qui sviluppano un dialogo materico interessante",
    "qui si temperano l'un l'altro con efficacia",
    "qui collaborano in un esito che convince",
    "qui si equilibrano con una grazia inaspettata",
    "qui creano un contrasto morbido e piacevole",
    "qui tessono un racconto visivo credibile",
    "qui traducono bene l'intenzione del design",
    "qui propongono un accoppiamento misurato",
    "qui si legano con un ritmo armonico",
    "qui si incastrano con una logica loro",
    "qui riescono a parlarsi senza sovrapporsi",
    "qui reggono insieme senza cali di tono",
    "qui producono una sinergia che si nota",
    "qui assemblano un quadro d'insieme convincente",
    "qui compongono un mosaico cromatico ordinato",
    "qui portano a un bilanciamento quasi perfetto",
    "qui generano un contrappunto elegante",
    "qui costruiscono una palette coerente",
    "qui si modulano con intelligenza",
    "qui trovano il loro posto l'uno accanto all'altro",
    "qui concorrono a un risultato maturo",
    "qui si dispongono con un senso preciso",
    "qui riescono a convivere senza contraddirsi",
    "qui esprimono una continuità cromatica piacevole",
    "qui stabiliscono un rapporto di forze equilibrato",
    "qui raggiungono una saturazione misurata",
    "qui dimostrano che il contrasto può essere gentile",
    "qui producono un effetto di insieme solido",
    "qui si intonano con un garbo raro",
    "qui si giustificano a vicenda dal punto di vista estetico",
    "qui interagiscono come fossero pensati in coppia",
    "qui creano un sistema visivo coerente",
    "qui trovano un registro comune credibile",
    "qui si sintonizzano senza prevaricare",
    "qui sviluppano una tensione cromatica piacevole",
    "qui dettano un mood preciso ma non rigido",
    "qui si modulano con naturalezza reciproca",
    "qui fanno squadra dal punto di vista estetico",
    "qui tessono una trama materica interessante",
    "qui definiscono un carattere visivo unitario",
    "qui riescono a essere complementari senza sforzo",
    "qui si organizzano in un racconto cromatico lineare",
    "qui producono un contrasto delicato ma presente",
    "qui si risolvono in un quadro d'insieme armonioso",
    "qui compongono un'immagine visiva centrata",
    "qui trovano un accordo che non è scontato",
    "qui mostrano una coesione estetica rara",
    "qui si affiancano con un senso musicale quasi",
    "qui restituiscono un tono caldo e ragionato",
    "qui si dispiegano in un effetto complessivo convincente",
    "qui lavorano su registri diversi ma compatibili",
    "qui si confrontano senza annullarsi",
    "qui fanno emergere una personalità cromatica chiara",
    "qui riescono a produrre un effetto memorabile",
    "qui giocano su tonalità che si valorizzano a vicenda",
    "qui suggeriscono un equilibrio pensato, non casuale",
    "qui confermano che l'accostamento è stato studiato bene",
    "qui dimostrano una coerenza progettuale evidente",
    "qui convivono in un rapporto che non stanca",
    "qui generano un'atmosfera precisa fin dal primo sguardo",
    "qui si sorreggono reciprocamente con mestiere",
    "qui propongono un patto cromatico solido",
    "qui parlano una lingua estetica comune",
    "qui costituiscono un insieme che si ricorda facilmente",
    "qui declinano una palette che ha una direzione chiara",
    "qui creano un campo visivo coeso e riconoscibile",
    "qui mettono in scena un dialogo materico efficace",
    "qui si compattano in un'immagine d'insieme forte",
    "qui delineano un'identità cromatica leggibile",
    "qui si presentano con una solidità estetica notevole",
    "qui dànno forma a un equilibrio non scontato",
    "qui custodiscono un rapporto di pesi ben calibrato",
    "qui disegnano un profilo cromatico che convince subito",
    "qui portano una coerenza che non è facile ottenere",
    "qui si raccordano con una sicurezza che colpisce",
    "qui impongono una logica visiva solida",
    "qui stringono un patto materico credibile",
    "qui fissano un punto fermo nella resa cromatica",
    "qui consegnano un effetto d'insieme di livello",
    "qui stabiliscono un'intesa visiva che si avverte subito",
    "qui scolpiscono un carattere cromatico netto",
    "qui confezionano un abbinamento che ha spessore",
    "qui inaugurano un dialogo di toni molto riuscito",
    "qui tratteggiano una combinazione che merita attenzione",
    "qui consolidano un insieme che ha una sua dignità",
    "qui forgiano un rapporto cromatico di sostanza",
    "qui cesellano un gioco di contrasti morbidi e precisi",
    "qui orchestrano una gamma tonale coerente",
    "qui allestiscono un quadro materico di tutto rispetto",
    "qui partoriscono un connubio estetico centrato",
]
PATTERNS["qui hanno trovato un equilibrio raro"] = _p1_verbs

# ---------------------------------------------------------------------------
# PATTERN 2: "dà identità, ma la cosa migliore è che" (114x)
# ---------------------------------------------------------------------------
_p2_parts_a = [
    "aggiunge carattere", "conferisce personalità", "dona un'impronta riconoscibile",
    "regala una nota propria", "trasmette un segno distintivo", "imprime un timbro",
    "porta con sé una voce precisa", "esprime un tratto identificativo",
    "restituisce un'identità chiara", "offre un profilo personale",
    "comunica una direzione stilistica", "definisce un carattere visivo",
    "costruisce un'atmosfera propria", "stabilisce un codice estetico",
    "racconta un'idea di stile", "scolpisce un tratto riconoscibile",
    "deposita una firma", "innesta una personalità",
    "incide un segno", "plasma un carattere",
    "marca un territorio stilistico", "forgia un'identità",
    "cesella un profilo", "disegna una fisionomia propria",
    "fissa un tono personale", "imposta una voce stilistica",
    "ancora un'estetica definita", "sigla un carattere",
    "assegna un ruolo preciso", "inaugura un registro",
]
_p2_parts_b = [
    ", e il bello è che",
    ", e ciò che conquista davvero è che",
    ", e l'aspetto più riuscito è che",
    ", e il vero punto di forza è che",
    ", e la parte che convince di più è che",
    ", e ciò che apprezzo soprattutto è che",
    ", e il dettaglio decisivo è che",
    ", e quello che li distingue è che",
    ", e la sorpresa concreta è che",
    ", e il lato che mi ha colpito è che",
    ", e il merito principale è che",
    ", e il vantaggio reale è che",
    ", e la qualità che spicca è che",
    ", e il tratto vincente è che",
    ", e l'elemento che pesa di più è che",
    ", e la conferma arriva dal fatto che",
    ", e il dato più interessante è che",
    ", e ciò che li rende speciali è che",
    ", e la nota che fa la differenza è che",
    ", e il pregio che noto di più è che",
]
_p2_alts = []
for a in _p2_parts_a:
    for b in _p2_parts_b:
        _p2_alts.append(a + b)
random.shuffle(_p2_alts)
PATTERNS["d\u00e0 identit\u00e0, ma la cosa migliore \u00e8 che"] = _p2_alts[:120]

# ---------------------------------------------------------------------------
# PATTERN 3: "Il motivo per cui mi fermo a quattro è che" (78x)
# ---------------------------------------------------------------------------
_p3 = [
    "Se non arrivo al massimo è perché",
    "Il punto che mi trattiene è che",
    "La ragione della mia riserva è che",
    "Quello che mi impedisce il voto pieno è che",
    "Non do cinque perché",
    "Il freno alla perfezione è che",
    "L'unico aspetto che pesa è che",
    "La nota che sottrae un punto è che",
    "Il dettaglio che mi trattiene è che",
    "Il limite che registro è che",
    "Se non raggiungo il punteggio massimo è perché",
    "Il fattore che mi fa esitare è che",
    "Quel che manca al voto pieno è che",
    "Il nodo che resta irrisolto è che",
    "La frenata arriva dal fatto che",
    "Il mio unico dubbio concreto è che",
    "L'elemento che sottrae mezzo voto è che",
    "Il freno reale è che",
    "La riserva che mantengo è che",
    "Dove non mi convince del tutto è che",
    "L'ostacolo al cinque stelle è che",
    "Il compromesso che accetto è che",
    "Il prezzo estetico da pagare è che",
    "Quel mezzo punto lo tolgo perché",
    "Il difetto che noto è che",
    "Il piccolo neo è che",
    "La mia esitazione nasce dal fatto che",
    "Il punto debole, se devo trovarne uno, è che",
    "L'unico sconto che faccio è che",
    "Il margine di miglioramento sta nel fatto che",
    "Ciò che mi separa dall'entusiasmo totale è che",
    "La perplessità residua riguarda il fatto che",
    "Il tallone d'Achille è che",
    "Il rovescio della medaglia è che",
    "La riserva che esprimo è che",
    "Il motivo della mia cautela è che",
    "Quello che non mi fa chiudere gli occhi è che",
    "Il dettaglio che raffredda un po' è che",
    "Il peso che sottraggo è dovuto al fatto che",
    "Se non li promuovo a pieni voti è perché",
    "La mia unica obiezione è che",
    "Il cruccio residuo è che",
    "L'asterisco che metto è che",
    "La ragione della stella mancante è che",
    "Il punto che mi lascia pensare è che",
    "Un solo aspetto mi frena: il fatto che",
    "Se qualcosa mi trattiene è che",
    "La sfumatura che abbassa il voto è che",
    "Il piccolo tribolo è che",
    "La nota stonata in un insieme buono è che",
    "L'ombra sul quadro è che",
    "Il dubbio che mi porto dietro è che",
    "L'unico freno alla piena promozione è che",
    "Il conto che mi resta da saldare è che",
    "La condizione che pongo è che",
    "L'incertezza che resiste è che",
    "La macchia su un quadro altrimenti buono è che",
    "Il solo appunto che mi sento di fare è che",
    "La zavorra che sento è che",
    "Il rovescio, se devo essere onesto, è che",
    "Il motivo del mezzo passo indietro è che",
    "L'ombra nel bilancio complessivo è che",
    "Il neo che non riesco a ignorare è che",
    "La clausola che aggiungo è che",
    "Il cavillo, se vogliamo, è che",
    "Il distinguo che faccio è che",
    "Il freno a mano lo tiro perché",
    "La riserva tecnica è che",
    "L'unico granello di sabbia è che",
    "Il contrappeso è che",
    "La zeppa nel meccanismo è che",
    "Il dettaglio che stona leggermente è che",
    "La crepa nel muro altrimenti solido è che",
    "Il sottotono che percepisco è che",
    "L'unica ombra è che",
    "La ruga nel tessuto è che",
    "Il punto su cui non chiudo un occhio è che",
    "La virgola che mi fa riflettere è che",
]
PATTERNS["Il motivo per cui mi fermo a quattro \u00e8 che"] = _p3

# ---------------------------------------------------------------------------
# PATTERN 4: "All'inizio ero più scettico che convinto." (67x)
# ---------------------------------------------------------------------------
_p4 = [
    "Partivo con più dubbi che certezze.",
    "Le mie aspettative iniziali erano basse.",
    "Non ero affatto sicuro al momento dell'acquisto.",
    "La prima reazione non era entusiasta.",
    "Confesso che all'apertura della scatola ero freddo.",
    "Non nascondo che li ho presi con scetticismo.",
    "Le premesse non mi convincevano granché.",
    "Ci sono arrivato con diffidenza.",
    "Ammetto di averli comprati senza grande convinzione.",
    "Il primo approccio è stato tiepido.",
    "Non li avrei scelti a prima vista.",
    "Sulle foto non mi avevano conquistato.",
    "Prima di provarli ero piuttosto perplesso.",
    "Il mio giudizio iniziale era molto cauto.",
    "Li guardavo con sospetto più che con interesse.",
    "Quando li ho ordinati non ero per niente convinto.",
    "Il feeling iniziale era tutto fuorché entusiastico.",
    "Non era il modello che mi avrebbe attirato in vetrina.",
    "L'impatto a freddo non prometteva bene.",
    "Se devo essere sincero, non partivo bene.",
    "Mi sono avvicinato con più perplessità che aspettativa.",
    "La mia fiducia iniziale era al minimo.",
    "Il primo contatto mi ha lasciato interdetto.",
    "Erano lontani da quello che cercavo di solito.",
    "Non li avrei mai notati da solo in negozio.",
    "Partivo con un pregiudizio abbastanza solido.",
    "La prima impressione non lavorava a loro favore.",
    "Li ho aperti senza nessuna fretta di innamorarmi.",
    "Ero il primo a non crederci.",
    "Le foto non mi avevano preparato bene.",
    "Il mio istinto iniziale diceva di lasciar perdere.",
    "Non erano neanche nella mia lista iniziale.",
    "Quando li ho visti per la prima volta ero dubbioso.",
    "La diffidenza era il mio stato d'animo al momento dell'unboxing.",
    "Non mi sono lanciato, anzi, ho esitato parecchio.",
    "I miei dubbi iniziali erano concreti.",
    "Ci ho girato intorno a lungo prima di decidermi.",
    "Non nascondo una certa ritrosia iniziale.",
    "Il pregiudizio, devo ammetterlo, era forte.",
    "Ho tardato a comprarli proprio perché non ero sicuro.",
    "A scanso di equivoci, non ero entusiasta.",
    "Il mio approccio era quello di chi non ha nulla da perdere.",
    "Le premesse, almeno per i miei gusti, non erano le migliori.",
    "Non c'era nessun colpo di fulmine iniziale.",
    "Li ho presi quasi per sfida, senza aspettative.",
    "La curiosità c'era, la fiducia molto meno.",
    "Ero praticamente convinto di doverli restituire.",
    "Il mio stato d'animo iniziale era una perplessità educata.",
    "Sono partito con il freno a mano tirato.",
    "Non è stato amore a prima vista, tutt'altro.",
    "Se c'è un modello che non avrei scommesso su, era questo.",
    "Davo per scontato che non avrebbero funzionato.",
    "La mia reazione alla scatola aperta è stata: vedremo.",
    "Il beneficio del dubbio era tutto quello che gli concedevo.",
    "Il primo sguardo non è stato incoraggiante.",
    "Aprendo la custodia pensavo già al reso.",
    "Non sono tipo da innamorarmi subito, e qui ancora meno.",
    "Il biglietto da visita iniziale non era dei migliori.",
    "Ci ho messo un po' a dargli una chance vera.",
    "La mia soglia di scetticismo era piuttosto alta.",
    "Non avrei puntato un centesimo su questo modello.",
    "La partenza è stata fredda, quasi ostile.",
    "Il mio primo pensiero è stato: troppo rischioso.",
    "Ero sinceramente titubante all'inizio.",
    "Non era il tipo di occhiale che mi avrebbe mai parlato.",
    "Il primo contatto è stato poco promettente.",
    "Ho iniziato questa prova con grande riserva.",
    "La prima occhiata non mi aveva catturato per niente.",
]
PATTERNS["All\u2019inizio ero pi\u00f9 scettico che convinto."] = _p4
# Anche con apostrofo dritto
PATTERNS["All'inizio ero pi\u00f9 scettico che convinto."] = _p4

# ---------------------------------------------------------------------------
# PATTERN 5: "Mi ci è voluto meno del previsto per inquadrarli." (59x)
# ---------------------------------------------------------------------------
_p5 = [
    "Li ho capiti più in fretta di quanto immaginassi.",
    "La comprensione è arrivata quasi subito.",
    "Ci ho messo meno del solito a orientarmi.",
    "Non ho avuto bisogno di tante prove per capirli.",
    "Mi sono fatto un'idea chiara in tempi brevissimi.",
    "L'impressione si è definita molto rapidamente.",
    "Sono bastati pochi utilizzi per avere le idee chiare.",
    "Ho trovato il bandolo della matassa prima del previsto.",
    "Il quadro si è composto quasi immediatamente.",
    "Li ho letti al volo.",
    "Non ho faticato a capire il loro linguaggio.",
    "La curva di apprendimento è stata più corta del solito.",
    "Un paio di uscite e il giudizio era già formato.",
    "Il primo giorno ha detto quasi tutto.",
    "La chiarezza è arrivata senza troppi giri.",
    "Non ho attraversato quella lunga fase di incertezza.",
    "Il verdetto si è formato con una rapidità inattesa.",
    "Ho avuto meno bisogno del solito di riflettere.",
    "Il mio giudizio si è stabilizzato presto.",
    "In poco tempo sapevo già cosa pensare.",
    "L'opinione si è cristallizzata prima del previsto.",
    "Non sono servite settimane per decidere.",
    "Il senso di questi occhiali mi è apparso subito.",
    "Due giorni e avevo già le idee chiare.",
    "Raramente mi succede di capire un modello così rapidamente.",
    "La valutazione è stata più istintiva del solito.",
    "Ho bruciato le tappe della conoscenza reciproca.",
    "Il tempo di prova è stato più breve del normale.",
    "L'impressione iniziale si è confermata senza attese.",
    "Il giudizio è maturato con una velocità insolita.",
    "Mi sono risparmiato il solito periodo di rodaggio mentale.",
    "Non c'è stato quel limbo fra entusiasmo e dubbio.",
    "La risposta è arrivata in modo più diretto del previsto.",
    "Ho saltato la fase delle perplessità prolungate.",
    "Il mio sistema di valutazione li ha processati in fretta.",
    "L'intesa è scattata a tempi record.",
    "Il verdetto è stato quasi istantaneo.",
    "Non ho avuto bisogno della solita settimana di prova.",
    "Li ho decodificati rapidamente.",
    "Già dopo il primo utilizzo sapevo cosa pensarne.",
    "Il processo decisionale è stato insolitamente breve.",
    "Mi sono chiarito le idee in un lampo.",
    "Non ho vissuto l'esitazione che temevo.",
    "Il mio parere si è consolidato molto prima del previsto.",
    "Il periodo di valutazione è stato più snello del consueto.",
    "La sintesi è arrivata subito, senza troppe mediazioni.",
    "Ho risparmiato tempo nella fase di acclimatamento.",
    "Il confronto con il mio stile è stato immediato.",
    "Non ho dovuto attraversare il solito percorso a ostacoli.",
    "L'analisi si è chiusa prima del previsto.",
    "Dal primo uso al giudizio finale è passato un attimo.",
    "Il segnale è arrivato forte e chiaro fin da subito.",
    "Non c'è stato bisogno di darsi tempo.",
    "Il dialogo con il mio viso si è instaurato velocemente.",
    "Sono atterrato su un parere in tempo record.",
    "L'inquadratura è stata netta fin dal principio.",
    "Nessun travaglio decisionale, questa volta.",
    "La lettura è stata più fluida del previsto.",
    "Ho raggiunto il dunque senza i soliti tentennamenti.",
    "L'idea che me ne sono fatto è stata quasi immediata.",
]
PATTERNS["Mi ci \u00e8 voluto meno del previsto per inquadrarli."] = _p5

# ---------------------------------------------------------------------------
# PATTERN 6: "lavorano insieme in un modo che mi piace molto." (58x)
# ---------------------------------------------------------------------------
_p6 = [
    "si integrano con un risultato che mi soddisfa.",
    "funzionano in coppia con un effetto che apprezzo molto.",
    "creano un dialogo estetico che mi convince.",
    "producono una sinergia che trovo efficace.",
    "collaborano in un esito che mi piace parecchio.",
    "si combinano con una resa che mi ha colpito.",
    "si fondono in un risultato che trovo riuscito.",
    "dialogano con un'armonia che ho apprezzato subito.",
    "interagiscono in un modo che trovo convincente.",
    "si completano con un effetto che mi conquista.",
    "si bilanciano in un risultato molto gradevole.",
    "generano un contrasto morbido che funziona bene.",
    "producono un effetto complessivo che mi ha sorpreso.",
    "si accompagnano con un risultato armonioso.",
    "costruiscono un gioco di toni che trovo azzeccato.",
    "esprimono una coesione estetica che mi convince.",
    "danno vita a un insieme che trovo elegante.",
    "si sostengono con un risultato che apprezzo.",
    "si accordano con una naturalezza che ho notato subito.",
    "offrono una resa d'insieme che mi piace davvero.",
    "tessono un equilibrio che trovo interessante.",
    "restituiscono un quadro che mi soddisfa pienamente.",
    "concorrono a un effetto che trovo ben calibrato.",
    "si modulano in un risultato che trovo maturo.",
    "si intrecciano con un esito che mi ha fatto piacere.",
    "si armonizzano in un modo che trovo centrato.",
    "producono un accordo cromatico che mi ha convinto.",
    "si temperano in un gioco che funziona benissimo sul viso.",
    "convergono in un risultato che trovo molto personale.",
    "si alternano con un ritmo che mi piace.",
    "compongono un mosaico estetico che funziona.",
    "si distribuiscono in un equilibrio che trovo riuscito.",
    "propongono un incastro che mi ha soddisfatto.",
    "tessono una trama visiva che trovo piacevole.",
    "cooperano in un effetto che mi convince nel complesso.",
    "raggiungono un'intesa visiva che trovo efficace.",
    "si risolvono in un risultato che apprezzo senza riserve.",
    "si amalgamano in un modo che mi trova d'accordo.",
    "si calibrano con un esito che trovo molto valido.",
    "si dispongono con un senso estetico che mi piace.",
    "si compenetrano con un risultato che considero forte.",
    "si raccordano in un modo che trovo equilibrato.",
    "sviluppano un confronto tonale che mi soddisfa.",
    "si sintonizzano in un risultato che trovo pulito.",
    "fanno sistema in un modo che sul mio viso funziona.",
    "si organizzano con un risultato che mi ha convinto subito.",
    "mettono in scena un dialogo cromatico che apprezzo.",
    "propongono un equilibrio che trovo credibile.",
    "formano un binomio estetico che mi piace davvero.",
    "si affiancano con un risultato che trovo solido.",
    "si stringono in un abbinamento che trovo riuscito.",
    "convergono in una resa che mi ha sorpreso favorevolmente.",
    "si innestano con un effetto che trovo molto pulito.",
    "si temperano in un modo che mi risulta gradevole.",
    "si confrontano con un risultato che trovo maturo.",
    "si sovrappongono in modo armonioso e convincente.",
    "creano una combinazione che mi ha colpito per equilibrio.",
    "si uniscono in un risultato complessivamente molto valido.",
]
PATTERNS["lavorano insieme in un modo che mi piace molto."] = _p6

# ---------------------------------------------------------------------------
# PATTERN 7: "e il colpo d'occhio è buono, ma" (55x)
# ---------------------------------------------------------------------------
_p7 = [
    "e la resa visiva convince, ma",
    "e l'impatto estetico è positivo, eppure",
    "e l'effetto a prima vista funziona, ma",
    "e il risultato d'insieme è gradevole, ma",
    "e il look complessivo è buono, però",
    "e la presenza sul viso piace, ma",
    "e visivamente sono centrati, ma",
    "e l'estetica è convincente, ma",
    "e la resa generale è buona, eppure",
    "e l'impressione visiva è riuscita, ma",
    "e dal punto di vista estetico ci siamo, ma",
    "e l'apparenza è quella giusta, però",
    "e la figura d'insieme è buona, ma",
    "e il quadro estetico regge, ma",
    "e la facciata è convincente, ma",
    "e il risultato visivo è apprezzabile, ma",
    "e il look funziona, ma",
    "e l'impatto è quello giusto, ma",
    "e la prima impressione è positiva, ma",
    "e il messaggio estetico arriva, ma",
    "e l'aspetto generale soddisfa, ma",
    "e la silhouette è azzeccata, ma",
    "e la linea sul viso è buona, ma",
    "e il design si fa notare bene, ma",
    "e l'effetto scenico c'è, ma",
    "e la resa formale è solida, ma",
    "e il profilo è interessante, ma",
    "e la presentazione funziona, però",
    "e il risultato esternamente è buono, ma",
    "e l'appeal estetico è innegabile, ma",
    "e da fuori l'effetto è convincente, ma",
    "e la tenuta visiva è buona, ma",
    "e il design non delude, ma",
    "e l'immagine complessiva è positiva, ma",
    "e la proposta estetica è di livello, ma",
    "e il messaggio visivo è chiaro, ma",
    "e la resa cromatica è piacevole, ma",
    "e il risultato formale è lusinghiero, ma",
    "e la sagoma è riuscita, ma",
    "e il tono visivo è giusto, ma",
    "e il primo effetto è promettente, ma",
    "e la composizione regge bene, ma",
    "e dall'esterno funzionano molto, ma",
    "e l'occhiale ha presenza, ma",
    "e il disegno si difende bene, ma",
    "e la costruzione visiva è curata, ma",
    "e il look d'insieme non tradisce, ma",
    "e l'impronta sul viso è positiva, ma",
    "e visivamente li promuovo, ma",
    "e il primo contatto estetico è buono, ma",
    "e la forma fa il suo dovere, ma",
    "e la scena estetica è buona, ma",
    "e il risultato a specchio piace, ma",
    "e il quadro visivo soddisfa, ma",
    "e l'effetto complessivo è valido, ma",
]
PATTERNS["e il colpo d\u2019occhio \u00e8 buono, ma"] = _p7
PATTERNS["e il colpo d'occhio \u00e8 buono, ma"] = _p7

# ---------------------------------------------------------------------------
# PATTERN 8: "Per questo resta un sì con riserva, non un sì assoluto." (55x)
# ---------------------------------------------------------------------------
_p8 = [
    "Per questo il giudizio è positivo ma non incondizionato.",
    "Ecco perché il mio sì ha una sfumatura di cautela.",
    "Per questo motivo la promozione non è piena.",
    "È un approvazione con asterisco, non un applauso totale.",
    "Il verdetto è favorevole, ma con una postilla.",
    "Li promuovo, anche se non a pieni voti.",
    "Il mio sì esiste, ma non è senza condizioni.",
    "Li approvo, con qualche riserva che non posso ignorare.",
    "È una promozione condizionata, non un trionfo.",
    "Il mio giudizio è positivo, ma pesato.",
    "Sono dentro al territorio del sì, ma non al centro.",
    "Il bilancio è buono, non eccezionale.",
    "Li porto volentieri, ma non con la stessa convinzione ogni volta.",
    "Per questo il voto è buono, non ottimo.",
    "Li consiglierei, con le giuste avvertenze.",
    "Per questo la mia opinione è favorevole, non entusiasta.",
    "È un sì ragionato, non un sì d'impulso.",
    "Per questo il mio entusiasmo ha dei limiti precisi.",
    "Il giudizio finale è lusinghiero, ma non incondizionato.",
    "Per questo siamo nel buono, senza toccare l'eccellente.",
    "Il mio pollice è su, ma non al massimo.",
    "Per questo il mio consenso ha una clausola.",
    "Li sostengo, ma senza chiudere gli occhi.",
    "Per questo l'apprezzamento è reale ma contenuto.",
    "Il saldo finale è in attivo, anche se non di molto.",
    "Li considero un buon acquisto, non un acquisto perfetto.",
    "Per questo la mia adesione ha un limite chiaro.",
    "Il parere è positivo, ma misurato.",
    "Per questo il gradimento c'è, senza però esaltazione.",
    "La mia valutazione è favorevole, con una nota a piè di pagina.",
    "Per questo il risultato è buono, ma non da standing ovation.",
    "Li promuovo con convinzione parziale.",
    "Per questo la resa è convincente, non folgorante.",
    "L'esperienza è positiva, ma con un margine di riserva.",
    "Per questo il mio giudizio è contenutamente positivo.",
    "Sono un acquisto riuscito, non un acquisto trionfale.",
    "La mia approvazione è sincera, ma non totalizzante.",
    "Per questo li metto fra i buoni, non fra gli eccezionali.",
    "Il responso è un sì pensato, non gridato.",
    "Li trattengo nella rotazione, ma non sono i primi che prendo.",
    "Per questo il mio plauso ha dei contorni definiti.",
    "La promozione c'è, ma con riserva di supplemento.",
    "Per questo l'entusiasmo è moderato ma genuino.",
    "È una vittoria ai punti, non per ko.",
    "Li salvo nel cassetto dei preferiti, ma non in cima.",
    "Per questo il mio apprezzamento è concreto, non illimitato.",
    "Restano un acquisto valido, con qualche ma.",
    "Per questo il voto è alto, senza però raggiungere il massimo.",
    "Sono nella zona del consigliabile, non dell'imperdibile.",
    "Per questo la mia fiducia è reale, anche se non cieca.",
    "L'esito è positivo, con quella riserva che non mi abbandona.",
    "Per questo il giudizio finale ha un asterisco piccolo ma presente.",
    "Il mio gradimento è solido, non incrollabile.",
    "Per questo il parere complessivo è buono, deliberatamente non perfetto.",
    "Sono nel campo dei promossi, ma non con lode.",
]
PATTERNS["Per questo resta un s\u00ec con riserva, non un s\u00ec assoluto."] = _p8

# ---------------------------------------------------------------------------
# PATTERN 9: "Qui la cosa che funziona è l'equilibrio:" (49x)
# ---------------------------------------------------------------------------
_p9 = [
    "Il punto forte è la coerenza d'insieme:",
    "Quello che funziona è il bilanciamento tra",
    "La chiave sta nell'armonia tra i dettagli:",
    "Il merito principale va alla proporzione fra",
    "La carta vincente è l'accordo fra gli elementi:",
    "Quello che convince è la calibrazione:",
    "L'aspetto più riuscito è l'equilibrio interno:",
    "La forza sta nella composizione fra",
    "Il fulcro è il dialogo fra le componenti:",
    "Il pezzo forte è la misura fra i toni:",
    "Ciò che tiene tutto insieme è l'armonia di",
    "La spina dorsale del modello è il rapporto tra",
    "Quello che lo eleva è la proporzione fra",
    "L'asse portante è il bilanciamento fra",
    "Il pregio più evidente è la coesione di",
    "Al centro c'è un equilibrio fra",
    "La cosa che funziona meglio è come si integrano",
    "L'ingrediente decisivo è la misura fra",
    "Il motore estetico è il rapporto fra",
    "La formula vincente sta nella sintonia tra",
    "Ciò che dà solidità è l'intesa fra",
    "L'elemento trainante è l'accordo fra",
    "Il nerbo del modello è il bilanciamento di",
    "La colonna vertebrale del design è il rapporto fra",
    "Quello che lo tiene in piedi è la calibratura tra",
    "La ragione del successo è nel dialogo fra",
    "L'anima di questo paio è nella proporzione di",
    "L'architettura che funziona è quella di",
    "Il baricentro estetico è nel rapporto fra",
    "La struttura si regge sull'equilibrio di",
    "L'asse centrale è la coerenza fra",
    "Il tessuto connettivo è l'armonia fra",
    "La chiave di volta è la misura fra",
    "L'impalcatura poggia sull'intesa tra",
    "Il centro di gravità è il bilanciamento di",
    "La sostanza è nell'accordo fra",
    "Il pilastro è il rapporto fra",
    "Il cemento è la proporzione fra",
    "La costante vincente è l'integrazione di",
    "L'equilibrio che regge il tutto è fra",
    "Il cardine estetico è il dialogo fra",
    "Il fondamento è la coesione tra",
    "La trama portante è l'armonia fra",
    "La base solida è il bilanciamento tra",
    "Il filo conduttore è la misura fra",
    "Il punto di forza è la coerenza di",
    "La radice del buon risultato è nel rapporto fra",
    "Ciò che lo rende credibile è la proporzione di",
    "L'ossatura è nell'equilibrio fra",
]
PATTERNS["Qui la cosa che funziona \u00e8 l\u2019equilibrio:"] = _p9
PATTERNS["Qui la cosa che funziona \u00e8 l'equilibrio:"] = _p9

# ---------------------------------------------------------------------------
# PATTERN 10: "senza bisogno di costruirgli attorno una sceneggiatura." (49x)
# ---------------------------------------------------------------------------
_p10 = [
    "senza necessità di raccontarci una storia attorno.",
    "senza doverci inventare un contesto per farli funzionare.",
    "senza bisogno di giustificazioni stilistiche.",
    "senza richiedere un outfit costruito ad arte.",
    "senza che serva un look elaborato per valorizzarli.",
    "senza alcuna fatica di abbinamento.",
    "senza chiedere sforzi interpretativi al resto del look.",
    "senza doverli contestualizzare troppo.",
    "senza che il resto del guardaroba debba adeguarsi.",
    "senza pretendere un'ambientazione particolare.",
    "senza la necessità di costruire il look attorno a loro.",
    "senza doverli spiegare a nessuno.",
    "senza bisogno di un palcoscenico apposito.",
    "senza esigere contorni elaborati.",
    "senza che serva un set fotografico per valorizzarli.",
    "senza forzature nell'abbinamento.",
    "senza dover creare un pretesto per indossarli.",
    "senza chiedere al guardaroba di ruotare attorno a loro.",
    "senza imporre regole al resto dell'outfit.",
    "senza che l'occasione debba essere quella giusta per forza.",
    "senza richiedere condizioni particolari per dare il meglio.",
    "senza mettere in difficoltà il resto del look.",
    "senza reclamare attenzioni speciali.",
    "senza pesare sull'equilibrio generale dell'outfit.",
    "senza la zavorra di un abbinamento obbligato.",
    "senza che il resto debba fare complimenti.",
    "senza bisogno di un contorno enfatico.",
    "senza doverli inserire in una narrazione stilistica.",
    "senza che il look debba essere pensato per loro.",
    "senza imporre vincoli al guardaroba.",
    "senza bisogno di una regia stilistica.",
    "senza chiedere mai troppo all'insieme.",
    "senza la necessità di un ecosistema ad hoc.",
    "senza vincolare il resto della giornata a una palette.",
    "senza che si debba costruire un personaggio attorno.",
    "senza aver bisogno di un contesto ideale.",
    "senza aspettare l'occasione perfetta.",
    "senza pretendere di essere al centro di un progetto estetico.",
    "senza dover apparecchiare nulla attorno.",
    "senza bisogno di giustificazioni di nessun tipo.",
    "senza esigere attenzioni particolari dal look.",
    "senza che il wardobe debba riallinearsi.",
    "senza necessità di filtri o ambientazioni favorevoli.",
    "senza che nulla debba venirgli in soccorso.",
    "senza richiedere un'intera produzione di stile attorno.",
    "senza la fatica di un abbinamento ragionato.",
    "senza vincoli estetici al contorno.",
    "senza doverci pensare troppo.",
    "senza bisogno di alcun supporto stilistico esterno.",
]
PATTERNS["senza bisogno di costruirgli attorno una sceneggiatura."] = _p10

# ---------------------------------------------------------------------------
# Continua nel file rewrite_reviews_part2.py
# ---------------------------------------------------------------------------
print("Parte 1 caricata: " + str(len(PATTERNS)) + " pattern definiti")
for k, v in PATTERNS.items():
    print(f"  {len(v):3d} alt. per: {k[:60]}")
